<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\DeclineChatJoinRequestRequest;
use App\Http\Responses\OpenApi\DeclineChatJoinRequestResponse;
use App\Http\Responses\OpenApi\ErrorResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class DeclineChatJoinRequestController extends Controller
{
    /**
     * POST /declineChatJoinRequest
     */
    abstract public function declineChatJoinRequest(
        DeclineChatJoinRequestRequest $request,
    ): DeclineChatJoinRequestResponse|ErrorResponse;
}
