<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\DeleteChatPhotoRequest;
use App\Http\Responses\OpenApi\DeleteChatPhotoResponse;
use App\Http\Responses\OpenApi\ErrorResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class DeleteChatPhotoController extends Controller
{
    /**
     * POST /deleteChatPhoto
     */
    abstract public function deleteChatPhoto(
        DeleteChatPhotoRequest $request,
    ): DeleteChatPhotoResponse|ErrorResponse;
}
