<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\GetChatAdministratorsRequest;
use App\Http\Responses\OpenApi\GetChatAdministratorsResponse;
use App\Http\Responses\OpenApi\ErrorResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class GetChatAdministratorController extends Controller
{
    /**
     * POST /getChatAdministrators
     */
    abstract public function getChatAdministrators(
        GetChatAdministratorsRequest $request,
    ): GetChatAdministratorsResponse|ErrorResponse;
}
