<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\SendMediaGroupRequest;
use App\Http\Responses\OpenApi\SendMediaGroupResponse;
use App\Http\Responses\OpenApi\ErrorResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class SendMediaGroupController extends Controller
{
    /**
     * POST /sendMediaGroup
     */
    abstract public function sendMediaGroup(
        SendMediaGroupRequest $request,
    ): SendMediaGroupResponse|ErrorResponse;
}
