<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\SendContactRequest;
use App\Http\Responses\OpenApi\SendContactResponse;
use App\Http\Responses\OpenApi\ErrorResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class SendContactController extends Controller
{
    /**
     * POST /sendContact
     */
    abstract public function sendContact(
        SendContactRequest $request,
    ): SendContactResponse|ErrorResponse;
}
