<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\SetChatTitleRequest;
use App\Http\Responses\OpenApi\SetChatTitleResponse;
use App\Http\Responses\OpenApi\ErrorResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class SetChatTitleController extends Controller
{
    /**
     * POST /setChatTitle
     */
    abstract public function setChatTitle(
        SetChatTitleRequest $request,
    ): SetChatTitleResponse|ErrorResponse;
}
