<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\SetPassportDataErrorsRequest;
use App\Http\Responses\OpenApi\SetPassportDataErrorsResponse;
use App\Http\Responses\OpenApi\ErrorResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class SetPassportDataErrorController extends Controller
{
    /**
     * POST /setPassportDataErrors
     */
    abstract public function setPassportDataErrors(
        SetPassportDataErrorsRequest $request,
    ): SetPassportDataErrorsResponse|ErrorResponse;
}
