<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Модель поста.
 *
 * Ref: #/components/schemas/Post
 */
final readonly class Post implements JsonSerializable
{
    public function __construct(
        public int $num,
        public int $parent,
        public string $board,
        public int $timestamp,
        public int $lasthit,
        public string $date,
        public OptString $email,
        public OptString $subject,
        public string $comment,
        /** @var File[] */
        public array $files,
        public int $views,
        public int $sticky,
        public int $endless,
        public int $closed,
        public int $banned,
        public int $op,
        public OptString $name,
        public OptString $icon,
        public OptString $trip,
        public OptString $tripStyle,
        public OptString $tags,
        public OptInt $likes,
        public OptInt $dislikes,
    ) {
        foreach ($this->files as $item) {
            if (!$item instanceof File) {
                throw new \InvalidArgumentException('Expected instance of File');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['num'] = $this->num;
        $result['parent'] = $this->parent;
        $result['board'] = $this->board;
        $result['timestamp'] = $this->timestamp;
        $result['lasthit'] = $this->lasthit;
        $result['date'] = $this->date;
        if ($this->email->set) {
            $result['email'] = $this->email->value;
        }
        if ($this->subject->set) {
            $result['subject'] = $this->subject->value;
        }
        $result['comment'] = $this->comment;
        $result['files'] = array_map(fn ($item) => $item->jsonSerialize(), $this->files);
        $result['views'] = $this->views;
        $result['sticky'] = $this->sticky;
        $result['endless'] = $this->endless;
        $result['closed'] = $this->closed;
        $result['banned'] = $this->banned;
        $result['op'] = $this->op;
        if ($this->name->set) {
            $result['name'] = $this->name->value;
        }
        if ($this->icon->set) {
            $result['icon'] = $this->icon->value;
        }
        if ($this->trip->set) {
            $result['trip'] = $this->trip->value;
        }
        if ($this->tripStyle->set) {
            $result['trip_style'] = $this->tripStyle->value;
        }
        if ($this->tags->set) {
            $result['tags'] = $this->tags->value;
        }
        if ($this->likes->set) {
            $result['likes'] = $this->likes->value;
        }
        if ($this->dislikes->set) {
            $result['dislikes'] = $this->dislikes->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            num: $data['num'],
            parent: $data['parent'],
            board: $data['board'],
            timestamp: $data['timestamp'],
            lasthit: $data['lasthit'],
            date: $data['date'],
            email: \array_key_exists('email', $data)
                ? OptString::some($data['email'])
                : OptString::none(),
            subject: \array_key_exists('subject', $data)
                ? OptString::some($data['subject'])
                : OptString::none(),
            comment: $data['comment'],
            files: array_map(File::fromArray(...), $data['files']),
            views: $data['views'],
            sticky: $data['sticky'],
            endless: $data['endless'],
            closed: $data['closed'],
            banned: $data['banned'],
            op: $data['op'],
            name: \array_key_exists('name', $data)
                ? OptString::some($data['name'])
                : OptString::none(),
            icon: \array_key_exists('icon', $data)
                ? OptString::some($data['icon'])
                : OptString::none(),
            trip: \array_key_exists('trip', $data)
                ? OptString::some($data['trip'])
                : OptString::none(),
            tripStyle: \array_key_exists('trip_style', $data)
                ? OptString::some($data['trip_style'])
                : OptString::none(),
            tags: \array_key_exists('tags', $data)
                ? OptString::some($data['tags'])
                : OptString::none(),
            likes: \array_key_exists('likes', $data)
                ? OptInt::some($data['likes'])
                : OptInt::none(),
            dislikes: \array_key_exists('dislikes', $data)
                ? OptInt::some($data['dislikes'])
                : OptInt::none(),
        );
    }
}
