<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\ApiLikeGetRequest;
use App\Http\Responses\OpenApi\ApiLikeGetResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class LikeController extends Controller
{
    /**
     * GET /api/like
     *
     * Добавление лайка на пост.
     */
    abstract public function apiLikeGet(
        ApiLikeGetRequest $request,
    ): ApiLikeGetResponse;
}
