<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserPassloginPostRequest;
use App\Http\Requests\UserPostingPostRequest;
use App\Http\Requests\UserReportPostRequest;
use App\Http\Responses\OpenApi\UserPassloginPostResponse;
use App\Http\Responses\OpenApi\UserPostingPostResponse;
use App\Http\Responses\OpenApi\UserReportPostResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class UserController extends Controller
{
    /**
     * POST /user/passlogin
     *
     * Авторизация пасскода.
     */
    abstract public function userPassloginPost(
        UserPassloginPostRequest $request,
    ): UserPassloginPostResponse;

    /**
     * POST /user/posting
     *
     * Создание нового поста или треда.
     */
    abstract public function userPostingPost(
        UserPostingPostRequest $request,
    ): UserPostingPostResponse;

    /**
     * POST /user/report
     *
     * Отправка жалобы.
     */
    abstract public function userReportPost(
        UserReportPostRequest $request,
    ): UserReportPostResponse;
}
