<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Requests\OpenApi;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Auto-generated form request from OpenAPI specification.
 *
 * Required request body
 */
abstract class TestRequestRequiredNumberInt32NullableArrayRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            '*' => ['nullable', 'integer', 'min:-2147483648', 'max:2147483647'],
        ];
    }
}
