<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class ActionsListSelfHostedRunnersForOrgOK implements JsonSerializable
{
    public function __construct(
        public int $totalCount,
        /** @var Runner[] */
        public array $runners,
    ) {
        foreach ($this->runners as $item) {
            if (!$item instanceof Runner) {
                throw new \InvalidArgumentException('Expected instance of Runner');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['total_count'] = $this->totalCount;
        $result['runners'] = array_map(fn ($item) => $item->jsonSerialize(), $this->runners);

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            totalCount: $data['total_count'],
            runners: array_map(Runner::fromArray(...), $data['runners']),
        );
    }
}
