<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class ActionsListSelfHostedRunnerGroupsForOrgOK implements JsonSerializable
{
    public function __construct(
        public float $totalCount,
        /** @var RunnerGroupsOrg[] */
        public array $runnerGroups,
    ) {
        foreach ($this->runnerGroups as $item) {
            if (!$item instanceof RunnerGroupsOrg) {
                throw new \InvalidArgumentException('Expected instance of RunnerGroupsOrg');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['total_count'] = $this->totalCount;
        $result['runner_groups'] = array_map(fn ($item) => $item->jsonSerialize(), $this->runnerGroups);

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            totalCount: $data['total_count'],
            runnerGroups: array_map(RunnerGroupsOrg::fromArray(...), $data['runner_groups']),
        );
    }
}
