<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class ActionsReviewPendingDeploymentsForRunReq implements JsonSerializable
{
    public function __construct(
        /** @var int[] */
        public array $environmentIds,
        public ActionsReviewPendingDeploymentsForRunReqState $state,
        public string $comment,
    ) {
        foreach ($this->environmentIds as $item) {
            if (!is_int($item)) {
                throw new \InvalidArgumentException('Expected int');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['environment_ids'] = $this->environmentIds;
        $result['state'] = $this->state->value;
        $result['comment'] = $this->comment;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            environmentIds: $data['environment_ids'],
            state: ActionsReviewPendingDeploymentsForRunReqState::from($data['state']),
            comment: $data['comment'],
        );
    }
}
