<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated Params DTO from OpenAPI specification.
 */
final readonly class ActivityListRepoNotificationsForAuthenticatedUserParams
{
    public function __construct(
        public OptBool $all,
        public OptBool $participating,
        public OptDateTime $since,
        public OptDateTime $before,
        public OptInt $perPage,
        public OptInt $page,
    ) {}

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            all: \array_key_exists('all', $data)
                ? OptBool::some($data['all'])
                : OptBool::none(),
            participating: \array_key_exists('participating', $data)
                ? OptBool::some($data['participating'])
                : OptBool::none(),
            since: \array_key_exists('since', $data)
                ? OptDateTime::some($data['since'])
                : OptDateTime::none(),
            before: \array_key_exists('before', $data)
                ? OptDateTime::some($data['before'])
                : OptDateTime::none(),
            perPage: \array_key_exists('per_page', $data)
                ? OptInt::some($data['per_page'])
                : OptInt::none(),
            page: \array_key_exists('page', $data)
                ? OptInt::some($data['page'])
                : OptInt::none(),
        );
    }
}
