<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class ActionsSetSelectedRepositoriesEnabledGithubActionsOrganizationReq implements JsonSerializable
{
    public function __construct(
        /** @var int[] */
        public array $selectedRepositoryIds,
    ) {
        foreach ($this->selectedRepositoryIds as $item) {
            if (!is_int($item)) {
                throw new \InvalidArgumentException('Expected int');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['selected_repository_ids'] = $this->selectedRepositoryIds;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            selectedRepositoryIds: $data['selected_repository_ids'],
        );
    }
}
