<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 * The level of permission to grant the access token for issues and related comments, assignees,
 * labels, and milestones. Can be one of: `read` or `write`.
 */
enum AppPermissionsIssues: string
{
    case AppPermissionsIssuesRead = 'read';
    case AppPermissionsIssuesWrite = 'write';
}
