<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated Params DTO from OpenAPI specification.
 */
final readonly class ChecksListForRefParams
{
    public function __construct(
        public OptString $checkName,
        public OptStatusParameter $status,
        public OptChecksListForRefFilter $filter,
        public OptInt $perPage,
        public OptInt $page,
        public OptInt $appId,
    ) {}

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            checkName: \array_key_exists('check_name', $data)
                ? OptString::some($data['check_name'])
                : OptString::none(),
            status: \array_key_exists('status', $data)
                ? OptStatusParameter::some($data['status'])
                : OptStatusParameter::none(),
            filter: \array_key_exists('filter', $data)
                ? OptChecksListForRefFilter::some($data['filter'])
                : OptChecksListForRefFilter::none(),
            perPage: \array_key_exists('per_page', $data)
                ? OptInt::some($data['per_page'])
                : OptInt::none(),
            page: \array_key_exists('page', $data)
                ? OptInt::some($data['page'])
                : OptInt::none(),
            appId: \array_key_exists('app_id', $data)
                ? OptInt::some($data['app_id'])
                : OptInt::none(),
        );
    }
}
