<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 */
enum CheckSuiteStatus: string
{
    case CheckSuiteStatusQueued = 'queued';
    case CheckSuiteStatusInProgress = 'in_progress';
    case CheckSuiteStatusCompleted = 'completed';
}
