<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class ChecksCreateReqSum0 implements JsonSerializable
{
    public function __construct(
        public ChecksCreateReqSum0Status $status,
        public array $additionalProps = [],
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['status'] = $this->status->value;
        $result = array_merge($result, $this->additionalProps);

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            status: ChecksCreateReqSum0Status::from($data['status']),
            additionalProps: $data,
        );
    }
}
