<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated Params DTO from OpenAPI specification.
 */
final readonly class CodeScanningListRecentAnalysesParams
{
    public function __construct(
        public OptCodeScanningAnalysisToolName $toolName,
        public OptNilCodeScanningAnalysisToolGuid $toolGuid,
        public OptInt $page,
        public OptInt $perPage,
        public OptCodeScanningRef $ref,
        public OptCodeScanningAnalysisSarifId $sarifId,
    ) {}

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            toolName: \array_key_exists('tool_name', $data)
                ? OptCodeScanningAnalysisToolName::some($data['tool_name'])
                : OptCodeScanningAnalysisToolName::none(),
            toolGuid: \array_key_exists('tool_guid', $data)
                ? OptNilCodeScanningAnalysisToolGuid::some($data['tool_guid'])
                : OptNilCodeScanningAnalysisToolGuid::none(),
            page: \array_key_exists('page', $data)
                ? OptInt::some($data['page'])
                : OptInt::none(),
            perPage: \array_key_exists('per_page', $data)
                ? OptInt::some($data['per_page'])
                : OptInt::none(),
            ref: \array_key_exists('ref', $data)
                ? OptCodeScanningRef::some($data['ref'])
                : OptCodeScanningRef::none(),
            sarifId: \array_key_exists('sarif_id', $data)
                ? OptCodeScanningAnalysisSarifId::some($data['sarif_id'])
                : OptCodeScanningAnalysisSarifId::none(),
        );
    }
}
