<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 *
 * Ref: #/components/schemas/code-scanning-alert
 */
final readonly class CodeScanningAlert implements JsonSerializable
{
    public function __construct(
        public int $number,
        public string $createdAt,
        public string $url,
        public string $htmlUrl,
        /** @deprecated */
        public mixed $instances,
        public string $instancesUrl,
        public CodeScanningAlertState $state,
        public ?NullableSimpleUser $dismissedBy,
        public ?string $dismissedAt,
        public ?CodeScanningAlertDismissedReason $dismissedReason,
        public CodeScanningAlertRule $rule,
        public CodeScanningAnalysisTool $tool,
        public CodeScanningAlertInstance $mostRecentInstance,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['number'] = $this->number;
        $result['created_at'] = $this->createdAt;
        $result['url'] = $this->url;
        $result['html_url'] = $this->htmlUrl;
        $result['instances'] = $this->instances;
        $result['instances_url'] = $this->instancesUrl;
        $result['state'] = $this->state->value;
        $result['dismissed_by'] = $this->dismissedBy;
        $result['dismissed_at'] = $this->dismissedAt;
        $result['dismissed_reason'] = $this->dismissedReason;
        $result['rule'] = $this->rule->jsonSerialize();
        $result['tool'] = $this->tool->jsonSerialize();
        $result['most_recent_instance'] = $this->mostRecentInstance->jsonSerialize();

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            number: $data['number'],
            createdAt: $data['created_at'],
            url: $data['url'],
            htmlUrl: $data['html_url'],
            instances: $data['instances'],
            instancesUrl: $data['instances_url'],
            state: CodeScanningAlertState::from($data['state']),
            dismissedBy: $data['dismissed_by'],
            dismissedAt: $data['dismissed_at'],
            dismissedReason: $data['dismissed_reason'],
            rule: CodeScanningAlertRule::fromArray($data['rule']),
            tool: CodeScanningAnalysisTool::fromArray($data['tool']),
            mostRecentInstance: CodeScanningAlertInstance::fromArray($data['most_recent_instance']),
        );
    }
}
