<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 * State of a code scanning alert.
 *
 * Ref: #/components/schemas/code-scanning-alert-state
 */
enum CodeScanningAlertState: string
{
    case CodeScanningAlertStateOpen = 'open';
    case CodeScanningAlertStateClosed = 'closed';
    case CodeScanningAlertStateDismissed = 'dismissed';
    case CodeScanningAlertStateFixed = 'fixed';
}
