<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 *
 * Ref: #/components/schemas/combined-billing-usage
 */
final readonly class CombinedBillingUsage implements JsonSerializable
{
    public function __construct(
        public int $daysLeftInBillingCycle,
        public int $estimatedPaidStorageForMonth,
        public int $estimatedStorageForMonth,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['days_left_in_billing_cycle'] = $this->daysLeftInBillingCycle;
        $result['estimated_paid_storage_for_month'] = $this->estimatedPaidStorageForMonth;
        $result['estimated_storage_for_month'] = $this->estimatedStorageForMonth;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            daysLeftInBillingCycle: $data['days_left_in_billing_cycle'],
            estimatedPaidStorageForMonth: $data['estimated_paid_storage_for_month'],
            estimatedStorageForMonth: $data['estimated_storage_for_month'],
        );
    }
}
