<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class ContentFileLinks implements JsonSerializable
{
    public function __construct(
        public ?string $git,
        public ?string $html,
        public string $self,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['git'] = $this->git;
        $result['html'] = $this->html;
        $result['self'] = $this->self;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            git: $data['git'],
            html: $data['html'],
            self: $data['self'],
        );
    }
}
