<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class EnterpriseAdminSetInformationForProvisionedEnterpriseUserReqEmailsItem implements JsonSerializable
{
    public function __construct(
        public string $value,
        public string $type,
        public bool $primary,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['value'] = $this->value;
        $result['type'] = $this->type;
        $result['primary'] = $this->primary;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            value: $data['value'],
            type: $data['type'],
            primary: $data['primary'],
        );
    }
}
