<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class EnterpriseAdminUpdateSelfHostedRunnerGroupForEnterpriseReq implements JsonSerializable
{
    public function __construct(
        public OptString $name,
        public OptEnterpriseAdminUpdateSelfHostedRunnerGroupForEnterpriseReqVisibility $visibility,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->name->set) {
            $result['name'] = $this->name->value;
        }
        if ($this->visibility->set) {
            $result['visibility'] = $this->visibility->value?->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            name: \array_key_exists('name', $data)
                ? OptString::some($data['name'])
                : OptString::none(),
            visibility: \array_key_exists('visibility', $data)
                ? OptEnterpriseAdminUpdateSelfHostedRunnerGroupForEnterpriseReqVisibility::some(EnterpriseAdminUpdateSelfHostedRunnerGroupForEnterpriseReqVisibility::from($data['visibility']))
                : OptEnterpriseAdminUpdateSelfHostedRunnerGroupForEnterpriseReqVisibility::none(),
        );
    }
}
