<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class EnterpriseAdminProvisionAndInviteEnterpriseUserReq implements JsonSerializable
{
    public function __construct(
        /** @var string[] */
        public array $schemas,
        public string $userName,
        public EnterpriseAdminProvisionAndInviteEnterpriseUserReqName $name,
        /** @var EnterpriseAdminProvisionAndInviteEnterpriseUserReqEmailsItem[] */
        public array $emails,
        /** @var EnterpriseAdminProvisionAndInviteEnterpriseUserReqGroupsItem[] */
        public array $groups,
    ) {
        foreach ($this->schemas as $item) {
            if (!is_string($item)) {
                throw new \InvalidArgumentException('Expected string');
            }
        }
        foreach ($this->emails as $item) {
            if (!$item instanceof EnterpriseAdminProvisionAndInviteEnterpriseUserReqEmailsItem) {
                throw new \InvalidArgumentException('Expected instance of EnterpriseAdminProvisionAndInviteEnterpriseUserReqEmailsItem');
            }
        }
        foreach ($this->groups as $item) {
            if (!$item instanceof EnterpriseAdminProvisionAndInviteEnterpriseUserReqGroupsItem) {
                throw new \InvalidArgumentException('Expected instance of EnterpriseAdminProvisionAndInviteEnterpriseUserReqGroupsItem');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['schemas'] = $this->schemas;
        $result['userName'] = $this->userName;
        $result['name'] = $this->name->jsonSerialize();
        $result['emails'] = array_map(fn ($item) => $item->jsonSerialize(), $this->emails);
        $result['groups'] = array_map(fn ($item) => $item->jsonSerialize(), $this->groups);

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            schemas: $data['schemas'],
            userName: $data['userName'],
            name: EnterpriseAdminProvisionAndInviteEnterpriseUserReqName::fromArray($data['name']),
            emails: array_map(EnterpriseAdminProvisionAndInviteEnterpriseUserReqEmailsItem::fromArray(...), $data['emails']),
            groups: array_map(EnterpriseAdminProvisionAndInviteEnterpriseUserReqGroupsItem::fromArray(...), $data['groups']),
        );
    }
}
