<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class EnterpriseAdminUpdateAttributeForEnterpriseUserReq implements JsonSerializable
{
    public function __construct(
        /** @var string[] */
        public array $schemas,
        public array $operations,
    ) {
        foreach ($this->schemas as $item) {
            if (!is_string($item)) {
                throw new \InvalidArgumentException('Expected string');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['schemas'] = $this->schemas;
        $result['Operations'] = $this->operations;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            schemas: $data['schemas'],
            operations: $data['Operations'],
        );
    }
}
