<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class GistSimpleForksItem implements JsonSerializable
{
    public function __construct(
        public OptString $id,
        public OptURI $url,
        public OptPublicUser $user,
        public OptDateTime $createdAt,
        public OptDateTime $updatedAt,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->id->set) {
            $result['id'] = $this->id->value;
        }
        if ($this->url->set) {
            $result['url'] = $this->url->value;
        }
        if ($this->user->set) {
            $result['user'] = $this->user->value?->jsonSerialize();
        }
        if ($this->createdAt->set) {
            $result['created_at'] = $this->createdAt->value;
        }
        if ($this->updatedAt->set) {
            $result['updated_at'] = $this->updatedAt->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: \array_key_exists('id', $data)
                ? OptString::some($data['id'])
                : OptString::none(),
            url: \array_key_exists('url', $data)
                ? OptURI::some($data['url'])
                : OptURI::none(),
            user: \array_key_exists('user', $data)
                ? OptPublicUser::some(PublicUser::fromArray($data['user']))
                : OptPublicUser::none(),
            createdAt: \array_key_exists('created_at', $data)
                ? OptDateTime::some($data['created_at'])
                : OptDateTime::none(),
            updatedAt: \array_key_exists('updated_at', $data)
                ? OptDateTime::some($data['updated_at'])
                : OptDateTime::none(),
        );
    }
}
