<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Gitignore Template.
 *
 * Ref: #/components/schemas/gitignore-template
 */
final readonly class GitignoreTemplate implements JsonSerializable
{
    public function __construct(
        public string $name,
        public string $source,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['name'] = $this->name;
        $result['source'] = $this->source;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            name: $data['name'],
            source: $data['source'],
        );
    }
}
