<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class GitRefObject implements JsonSerializable
{
    public function __construct(
        public string $type,
        public string $sha,
        public string $url,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['type'] = $this->type;
        $result['sha'] = $this->sha;
        $result['url'] = $this->url;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            type: $data['type'],
            sha: $data['sha'],
            url: $data['url'],
        );
    }
}
