<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class GpgKeySubkeysItem implements JsonSerializable
{
    public function __construct(
        public OptInt $id,
        public OptInt $primaryKeyId,
        public OptString $keyId,
        public OptString $publicKey,
        public array $emails,
        public array $subkeys,
        public OptBool $canSign,
        public OptBool $canEncryptComms,
        public OptBool $canEncryptStorage,
        public OptBool $canCertify,
        public OptString $createdAt,
        public OptNilString $expiresAt,
        public OptNilString $rawKey,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->id->set) {
            $result['id'] = $this->id->value;
        }
        if ($this->primaryKeyId->set) {
            $result['primary_key_id'] = $this->primaryKeyId->value;
        }
        if ($this->keyId->set) {
            $result['key_id'] = $this->keyId->value;
        }
        if ($this->publicKey->set) {
            $result['public_key'] = $this->publicKey->value;
        }
        $result['emails'] = $this->emails;
        $result['subkeys'] = $this->subkeys;
        if ($this->canSign->set) {
            $result['can_sign'] = $this->canSign->value;
        }
        if ($this->canEncryptComms->set) {
            $result['can_encrypt_comms'] = $this->canEncryptComms->value;
        }
        if ($this->canEncryptStorage->set) {
            $result['can_encrypt_storage'] = $this->canEncryptStorage->value;
        }
        if ($this->canCertify->set) {
            $result['can_certify'] = $this->canCertify->value;
        }
        if ($this->createdAt->set) {
            $result['created_at'] = $this->createdAt->value;
        }
        if ($this->expiresAt->set) {
            $result['expires_at'] = $this->expiresAt->value;
        }
        if ($this->rawKey->set) {
            $result['raw_key'] = $this->rawKey->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: \array_key_exists('id', $data)
                ? OptInt::some($data['id'])
                : OptInt::none(),
            primaryKeyId: \array_key_exists('primary_key_id', $data)
                ? OptInt::some($data['primary_key_id'])
                : OptInt::none(),
            keyId: \array_key_exists('key_id', $data)
                ? OptString::some($data['key_id'])
                : OptString::none(),
            publicKey: \array_key_exists('public_key', $data)
                ? OptString::some($data['public_key'])
                : OptString::none(),
            emails: $data['emails'],
            subkeys: $data['subkeys'],
            canSign: \array_key_exists('can_sign', $data)
                ? OptBool::some($data['can_sign'])
                : OptBool::none(),
            canEncryptComms: \array_key_exists('can_encrypt_comms', $data)
                ? OptBool::some($data['can_encrypt_comms'])
                : OptBool::none(),
            canEncryptStorage: \array_key_exists('can_encrypt_storage', $data)
                ? OptBool::some($data['can_encrypt_storage'])
                : OptBool::none(),
            canCertify: \array_key_exists('can_certify', $data)
                ? OptBool::some($data['can_certify'])
                : OptBool::none(),
            createdAt: \array_key_exists('created_at', $data)
                ? OptString::some($data['created_at'])
                : OptString::none(),
            expiresAt: \array_key_exists('expires_at', $data)
                ? OptNilString::some($data['expires_at'])
                : OptNilString::none(),
            rawKey: \array_key_exists('raw_key', $data)
                ? OptNilString::some($data['raw_key'])
                : OptNilString::none(),
        );
    }
}
