<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Delivery made by a webhook.
 *
 * Ref: #/components/schemas/hook-delivery
 */
final readonly class HookDelivery implements JsonSerializable
{
    public function __construct(
        public int $id,
        public string $guid,
        public string $deliveredAt,
        public bool $redelivery,
        public float $duration,
        public string $status,
        public int $statusCode,
        public string $event,
        public ?string $action,
        public ?int $installationId,
        public ?int $repositoryId,
        public OptString $url,
        public HookDeliveryRequest $request,
        public HookDeliveryResponse $response,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['id'] = $this->id;
        $result['guid'] = $this->guid;
        $result['delivered_at'] = $this->deliveredAt;
        $result['redelivery'] = $this->redelivery;
        $result['duration'] = $this->duration;
        $result['status'] = $this->status;
        $result['status_code'] = $this->statusCode;
        $result['event'] = $this->event;
        $result['action'] = $this->action;
        $result['installation_id'] = $this->installationId;
        $result['repository_id'] = $this->repositoryId;
        if ($this->url->set) {
            $result['url'] = $this->url->value;
        }
        $result['request'] = $this->request->jsonSerialize();
        $result['response'] = $this->response->jsonSerialize();

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            guid: $data['guid'],
            deliveredAt: $data['delivered_at'],
            redelivery: $data['redelivery'],
            duration: $data['duration'],
            status: $data['status'],
            statusCode: $data['status_code'],
            event: $data['event'],
            action: $data['action'],
            installationId: $data['installation_id'],
            repositoryId: $data['repository_id'],
            url: \array_key_exists('url', $data)
                ? OptString::some($data['url'])
                : OptString::none(),
            request: HookDeliveryRequest::fromArray($data['request']),
            response: HookDeliveryResponse::fromArray($data['response']),
        );
    }
}
