<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Issue Search Result Item.
 *
 * Ref: #/components/schemas/issue-search-result-item
 */
final readonly class IssueSearchResultItem implements JsonSerializable
{
    public function __construct(
        public string $url,
        public string $repositoryUrl,
        public string $labelsUrl,
        public string $commentsUrl,
        public string $eventsUrl,
        public string $htmlUrl,
        public int $id,
        public string $nodeId,
        public int $number,
        public string $title,
        public bool $locked,
        public OptNilString $activeLockReason,
        public OptNilSimpleUserArray $assignees,
        public ?NullableSimpleUser $user,
        /** @var IssueSearchResultItemLabelsItem[] */
        public array $labels,
        public string $state,
        public ?NullableSimpleUser $assignee,
        public ?NullableMilestone $milestone,
        public int $comments,
        public string $createdAt,
        public string $updatedAt,
        public ?string $closedAt,
        public SearchResultTextMatches $textMatches,
        public OptIssueSearchResultItemPullRequest $pullRequest,
        public OptString $body,
        public float $score,
        public AuthorAssociation $authorAssociation,
        public OptBool $draft,
        public OptRepository $repository,
        public OptString $bodyHtml,
        public OptString $bodyText,
        public OptURI $timelineUrl,
        public OptNilNullableIntegration $performedViaGithubApp,
    ) {
        foreach ($this->labels as $item) {
            if (!$item instanceof IssueSearchResultItemLabelsItem) {
                throw new \InvalidArgumentException('Expected instance of IssueSearchResultItemLabelsItem');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['url'] = $this->url;
        $result['repository_url'] = $this->repositoryUrl;
        $result['labels_url'] = $this->labelsUrl;
        $result['comments_url'] = $this->commentsUrl;
        $result['events_url'] = $this->eventsUrl;
        $result['html_url'] = $this->htmlUrl;
        $result['id'] = $this->id;
        $result['node_id'] = $this->nodeId;
        $result['number'] = $this->number;
        $result['title'] = $this->title;
        $result['locked'] = $this->locked;
        if ($this->activeLockReason->set) {
            $result['active_lock_reason'] = $this->activeLockReason->value;
        }
        if ($this->assignees->set) {
            $result['assignees'] = array_map(fn ($item) => $item->jsonSerialize(), $this->assignees->value);
        }
        $result['user'] = $this->user;
        $result['labels'] = array_map(fn ($item) => $item->jsonSerialize(), $this->labels);
        $result['state'] = $this->state;
        $result['assignee'] = $this->assignee;
        $result['milestone'] = $this->milestone;
        $result['comments'] = $this->comments;
        $result['created_at'] = $this->createdAt;
        $result['updated_at'] = $this->updatedAt;
        $result['closed_at'] = $this->closedAt;
        $result['text_matches'] = $this->textMatches->jsonSerialize();
        if ($this->pullRequest->set) {
            $result['pull_request'] = $this->pullRequest->value?->jsonSerialize();
        }
        if ($this->body->set) {
            $result['body'] = $this->body->value;
        }
        $result['score'] = $this->score;
        $result['author_association'] = $this->authorAssociation->value;
        if ($this->draft->set) {
            $result['draft'] = $this->draft->value;
        }
        if ($this->repository->set) {
            $result['repository'] = $this->repository->value?->jsonSerialize();
        }
        if ($this->bodyHtml->set) {
            $result['body_html'] = $this->bodyHtml->value;
        }
        if ($this->bodyText->set) {
            $result['body_text'] = $this->bodyText->value;
        }
        if ($this->timelineUrl->set) {
            $result['timeline_url'] = $this->timelineUrl->value;
        }
        if ($this->performedViaGithubApp->set) {
            $result['performed_via_github_app'] = $this->performedViaGithubApp->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            url: $data['url'],
            repositoryUrl: $data['repository_url'],
            labelsUrl: $data['labels_url'],
            commentsUrl: $data['comments_url'],
            eventsUrl: $data['events_url'],
            htmlUrl: $data['html_url'],
            id: $data['id'],
            nodeId: $data['node_id'],
            number: $data['number'],
            title: $data['title'],
            locked: $data['locked'],
            activeLockReason: \array_key_exists('active_lock_reason', $data)
                ? OptNilString::some($data['active_lock_reason'])
                : OptNilString::none(),
            assignees: \array_key_exists('assignees', $data)
                ? OptNilSimpleUserArray::some(array_map(SimpleUser::fromArray(...), $data['assignees']))
                : OptNilSimpleUserArray::none(),
            user: $data['user'],
            labels: array_map(IssueSearchResultItemLabelsItem::fromArray(...), $data['labels']),
            state: $data['state'],
            assignee: $data['assignee'],
            milestone: $data['milestone'],
            comments: $data['comments'],
            createdAt: $data['created_at'],
            updatedAt: $data['updated_at'],
            closedAt: $data['closed_at'],
            textMatches: SearchResultTextMatches::fromArray($data['text_matches']),
            pullRequest: \array_key_exists('pull_request', $data)
                ? OptIssueSearchResultItemPullRequest::some(IssueSearchResultItemPullRequest::fromArray($data['pull_request']))
                : OptIssueSearchResultItemPullRequest::none(),
            body: \array_key_exists('body', $data)
                ? OptString::some($data['body'])
                : OptString::none(),
            score: $data['score'],
            authorAssociation: AuthorAssociation::from($data['author_association']),
            draft: \array_key_exists('draft', $data)
                ? OptBool::some($data['draft'])
                : OptBool::none(),
            repository: \array_key_exists('repository', $data)
                ? OptRepository::some(Repository::fromArray($data['repository']))
                : OptRepository::none(),
            bodyHtml: \array_key_exists('body_html', $data)
                ? OptString::some($data['body_html'])
                : OptString::none(),
            bodyText: \array_key_exists('body_text', $data)
                ? OptString::some($data['body_text'])
                : OptString::none(),
            timelineUrl: \array_key_exists('timeline_url', $data)
                ? OptURI::some($data['timeline_url'])
                : OptURI::none(),
            performedViaGithubApp: \array_key_exists('performed_via_github_app', $data)
                ? OptNilNullableIntegration::some(NullableIntegration::fromArray($data['performed_via_github_app']))
                : OptNilNullableIntegration::none(),
        );
    }
}
