<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class IssuesCreateReqLabelsItem1 implements JsonSerializable
{
    public function __construct(
        public OptInt $id,
        public OptString $name,
        public OptNilString $description,
        public OptNilString $color,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->id->set) {
            $result['id'] = $this->id->value;
        }
        if ($this->name->set) {
            $result['name'] = $this->name->value;
        }
        if ($this->description->set) {
            $result['description'] = $this->description->value;
        }
        if ($this->color->set) {
            $result['color'] = $this->color->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: \array_key_exists('id', $data)
                ? OptInt::some($data['id'])
                : OptInt::none(),
            name: \array_key_exists('name', $data)
                ? OptString::some($data['name'])
                : OptString::none(),
            description: \array_key_exists('description', $data)
                ? OptNilString::some($data['description'])
                : OptNilString::none(),
            color: \array_key_exists('color', $data)
                ? OptNilString::some($data['color'])
                : OptNilString::none(),
        );
    }
}
