<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 */
enum IssuesListForAuthenticatedUserState: string
{
    case IssuesListForAuthenticatedUserStateOpen = 'open';
    case IssuesListForAuthenticatedUserStateClosed = 'closed';
    case IssuesListForAuthenticatedUserStateAll = 'all';
}
