<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Issue Event.
 *
 * Ref: #/components/schemas/issue-event
 */
final readonly class IssueEvent implements JsonSerializable
{
    public function __construct(
        public int $id,
        public string $nodeId,
        public string $url,
        public ?NullableSimpleUser $actor,
        public string $event,
        public ?string $commitId,
        public ?string $commitUrl,
        public string $createdAt,
        public OptIssueSimple $issue,
        public OptIssueEventLabel $label,
        public OptNilNullableSimpleUser $assignee,
        public OptNilNullableSimpleUser $assigner,
        public OptNilNullableSimpleUser $reviewRequester,
        public OptNilNullableSimpleUser $requestedReviewer,
        public OptTeam $requestedTeam,
        public OptIssueEventDismissedReview $dismissedReview,
        public OptIssueEventMilestone $milestone,
        public OptIssueEventProjectCard $projectCard,
        public OptIssueEventRename $rename,
        public OptAuthorAssociation $authorAssociation,
        public OptNilString $lockReason,
        public OptNilNullableIntegration $performedViaGithubApp,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['id'] = $this->id;
        $result['node_id'] = $this->nodeId;
        $result['url'] = $this->url;
        $result['actor'] = $this->actor;
        $result['event'] = $this->event;
        $result['commit_id'] = $this->commitId;
        $result['commit_url'] = $this->commitUrl;
        $result['created_at'] = $this->createdAt;
        if ($this->issue->set) {
            $result['issue'] = $this->issue->value?->jsonSerialize();
        }
        if ($this->label->set) {
            $result['label'] = $this->label->value?->jsonSerialize();
        }
        if ($this->assignee->set) {
            $result['assignee'] = $this->assignee->value?->jsonSerialize();
        }
        if ($this->assigner->set) {
            $result['assigner'] = $this->assigner->value?->jsonSerialize();
        }
        if ($this->reviewRequester->set) {
            $result['review_requester'] = $this->reviewRequester->value?->jsonSerialize();
        }
        if ($this->requestedReviewer->set) {
            $result['requested_reviewer'] = $this->requestedReviewer->value?->jsonSerialize();
        }
        if ($this->requestedTeam->set) {
            $result['requested_team'] = $this->requestedTeam->value?->jsonSerialize();
        }
        if ($this->dismissedReview->set) {
            $result['dismissed_review'] = $this->dismissedReview->value?->jsonSerialize();
        }
        if ($this->milestone->set) {
            $result['milestone'] = $this->milestone->value?->jsonSerialize();
        }
        if ($this->projectCard->set) {
            $result['project_card'] = $this->projectCard->value?->jsonSerialize();
        }
        if ($this->rename->set) {
            $result['rename'] = $this->rename->value?->jsonSerialize();
        }
        if ($this->authorAssociation->set) {
            $result['author_association'] = $this->authorAssociation->value?->value;
        }
        if ($this->lockReason->set) {
            $result['lock_reason'] = $this->lockReason->value;
        }
        if ($this->performedViaGithubApp->set) {
            $result['performed_via_github_app'] = $this->performedViaGithubApp->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            nodeId: $data['node_id'],
            url: $data['url'],
            actor: $data['actor'],
            event: $data['event'],
            commitId: $data['commit_id'],
            commitUrl: $data['commit_url'],
            createdAt: $data['created_at'],
            issue: \array_key_exists('issue', $data)
                ? OptIssueSimple::some(IssueSimple::fromArray($data['issue']))
                : OptIssueSimple::none(),
            label: \array_key_exists('label', $data)
                ? OptIssueEventLabel::some(IssueEventLabel::fromArray($data['label']))
                : OptIssueEventLabel::none(),
            assignee: \array_key_exists('assignee', $data)
                ? OptNilNullableSimpleUser::some(NullableSimpleUser::fromArray($data['assignee']))
                : OptNilNullableSimpleUser::none(),
            assigner: \array_key_exists('assigner', $data)
                ? OptNilNullableSimpleUser::some(NullableSimpleUser::fromArray($data['assigner']))
                : OptNilNullableSimpleUser::none(),
            reviewRequester: \array_key_exists('review_requester', $data)
                ? OptNilNullableSimpleUser::some(NullableSimpleUser::fromArray($data['review_requester']))
                : OptNilNullableSimpleUser::none(),
            requestedReviewer: \array_key_exists('requested_reviewer', $data)
                ? OptNilNullableSimpleUser::some(NullableSimpleUser::fromArray($data['requested_reviewer']))
                : OptNilNullableSimpleUser::none(),
            requestedTeam: \array_key_exists('requested_team', $data)
                ? OptTeam::some(Team::fromArray($data['requested_team']))
                : OptTeam::none(),
            dismissedReview: \array_key_exists('dismissed_review', $data)
                ? OptIssueEventDismissedReview::some(IssueEventDismissedReview::fromArray($data['dismissed_review']))
                : OptIssueEventDismissedReview::none(),
            milestone: \array_key_exists('milestone', $data)
                ? OptIssueEventMilestone::some(IssueEventMilestone::fromArray($data['milestone']))
                : OptIssueEventMilestone::none(),
            projectCard: \array_key_exists('project_card', $data)
                ? OptIssueEventProjectCard::some(IssueEventProjectCard::fromArray($data['project_card']))
                : OptIssueEventProjectCard::none(),
            rename: \array_key_exists('rename', $data)
                ? OptIssueEventRename::some(IssueEventRename::fromArray($data['rename']))
                : OptIssueEventRename::none(),
            authorAssociation: \array_key_exists('author_association', $data)
                ? OptAuthorAssociation::some(AuthorAssociation::from($data['author_association']))
                : OptAuthorAssociation::none(),
            lockReason: \array_key_exists('lock_reason', $data)
                ? OptNilString::some($data['lock_reason'])
                : OptNilString::none(),
            performedViaGithubApp: \array_key_exists('performed_via_github_app', $data)
                ? OptNilNullableIntegration::some(NullableIntegration::fromArray($data['performed_via_github_app']))
                : OptNilNullableIntegration::none(),
        );
    }
}
