<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class IssueSearchResultItemLabelsItem implements JsonSerializable
{
    public function __construct(
        public OptInt64 $id,
        public OptString $nodeId,
        public OptString $url,
        public OptString $name,
        public OptString $color,
        public OptBool $default,
        public OptNilString $description,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->id->set) {
            $result['id'] = $this->id->value;
        }
        if ($this->nodeId->set) {
            $result['node_id'] = $this->nodeId->value;
        }
        if ($this->url->set) {
            $result['url'] = $this->url->value;
        }
        if ($this->name->set) {
            $result['name'] = $this->name->value;
        }
        if ($this->color->set) {
            $result['color'] = $this->color->value;
        }
        if ($this->default->set) {
            $result['default'] = $this->default->value;
        }
        if ($this->description->set) {
            $result['description'] = $this->description->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: \array_key_exists('id', $data)
                ? OptInt64::some($data['id'])
                : OptInt64::none(),
            nodeId: \array_key_exists('node_id', $data)
                ? OptString::some($data['node_id'])
                : OptString::none(),
            url: \array_key_exists('url', $data)
                ? OptString::some($data['url'])
                : OptString::none(),
            name: \array_key_exists('name', $data)
                ? OptString::some($data['name'])
                : OptString::none(),
            color: \array_key_exists('color', $data)
                ? OptString::some($data['color'])
                : OptString::none(),
            default: \array_key_exists('default', $data)
                ? OptBool::some($data['default'])
                : OptBool::none(),
            description: \array_key_exists('description', $data)
                ? OptNilString::some($data['description'])
                : OptNilString::none(),
        );
    }
}
