<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 * The reason for locking the issue or pull request conversation. Lock will fail if you don't use one
 * of these reasons:
 * \* `off-topic`
 * \* `too heated`
 * \* `resolved`
 * \* `spam`.
 */
enum IssuesLockReqLockReason: string
{
    case IssuesLockReqLockReasonOffTopic = 'off-topic';
    case IssuesLockReqLockReasonTooHeated = 'too heated';
    case IssuesLockReqLockReasonResolved = 'resolved';
    case IssuesLockReqLockReasonSpam = 'spam';
}
