<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class MarkdownRenderReq implements JsonSerializable
{
    public function __construct(
        public string $text,
        public OptMarkdownRenderReqMode $mode,
        public OptString $context,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['text'] = $this->text;
        if ($this->mode->set) {
            $result['mode'] = $this->mode->value?->value;
        }
        if ($this->context->set) {
            $result['context'] = $this->context->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            text: $data['text'],
            mode: \array_key_exists('mode', $data)
                ? OptMarkdownRenderReqMode::some(MarkdownRenderReqMode::from($data['mode']))
                : OptMarkdownRenderReqMode::none(),
            context: \array_key_exists('context', $data)
                ? OptString::some($data['context'])
                : OptString::none(),
        );
    }
}
