<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class MigrationsUpdateImportReq implements JsonSerializable
{
    public function __construct(
        public OptString $vcsUsername,
        public OptString $vcsPassword,
        public OptString $vcs,
        public OptString $tfvcProject,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->vcsUsername->set) {
            $result['vcs_username'] = $this->vcsUsername->value;
        }
        if ($this->vcsPassword->set) {
            $result['vcs_password'] = $this->vcsPassword->value;
        }
        if ($this->vcs->set) {
            $result['vcs'] = $this->vcs->value;
        }
        if ($this->tfvcProject->set) {
            $result['tfvc_project'] = $this->tfvcProject->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            vcsUsername: \array_key_exists('vcs_username', $data)
                ? OptString::some($data['vcs_username'])
                : OptString::none(),
            vcsPassword: \array_key_exists('vcs_password', $data)
                ? OptString::some($data['vcs_password'])
                : OptString::none(),
            vcs: \array_key_exists('vcs', $data)
                ? OptString::some($data['vcs'])
                : OptString::none(),
            tfvcProject: \array_key_exists('tfvc_project', $data)
                ? OptString::some($data['tfvc_project'])
                : OptString::none(),
        );
    }
}
