<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * NilNullableIntegration is nullable NullableIntegration.
 */
final readonly class NilNullableIntegration
{
    public function __construct(
        public ?NullableIntegration $value,
        public bool $null,
    ) {}
}
