<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * NilNullableSimpleCommitAuthor is nullable NullableSimpleCommitAuthor.
 */
final readonly class NilNullableSimpleCommitAuthor
{
    public function __construct(
        public ?NullableSimpleCommitAuthor $value,
        public bool $null,
    ) {}
}
