<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * NilReposUpdateBranchProtectionReqRestrictions is nullable ReposUpdateBranchProtectionReqRestrictions.
 */
final readonly class NilReposUpdateBranchProtectionReqRestrictions
{
    public function __construct(
        public ?ReposUpdateBranchProtectionReqRestrictions $value,
        public bool $null,
    ) {}
}
