<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * The set of permissions for the GitHub app.
 */
final readonly class NullableIntegrationPermissions implements JsonSerializable
{
    public function __construct(
        public OptString $issues,
        public OptString $checks,
        public OptString $metadata,
        public OptString $contents,
        public OptString $deployments,
        public array $additionalProps = [],
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->issues->set) {
            $result['issues'] = $this->issues->value;
        }
        if ($this->checks->set) {
            $result['checks'] = $this->checks->value;
        }
        if ($this->metadata->set) {
            $result['metadata'] = $this->metadata->value;
        }
        if ($this->contents->set) {
            $result['contents'] = $this->contents->value;
        }
        if ($this->deployments->set) {
            $result['deployments'] = $this->deployments->value;
        }
        $result = array_merge($result, $this->additionalProps);

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            issues: \array_key_exists('issues', $data)
                ? OptString::some($data['issues'])
                : OptString::none(),
            checks: \array_key_exists('checks', $data)
                ? OptString::some($data['checks'])
                : OptString::none(),
            metadata: \array_key_exists('metadata', $data)
                ? OptString::some($data['metadata'])
                : OptString::none(),
            contents: \array_key_exists('contents', $data)
                ? OptString::some($data['contents'])
                : OptString::none(),
            deployments: \array_key_exists('deployments', $data)
                ? OptString::some($data['deployments'])
                : OptString::none(),
            additionalProps: $data,
        );
    }
}
