<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class OauthAuthorizationsCreateAuthorizationReq implements JsonSerializable
{
    public function __construct(
        public OptNilStringArray $scopes,
        public OptString $note,
        public OptString $noteUrl,
        public OptString $clientId,
        public OptString $clientSecret,
        public OptString $fingerprint,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->scopes->set) {
            $result['scopes'] = $this->scopes->value;
        }
        if ($this->note->set) {
            $result['note'] = $this->note->value;
        }
        if ($this->noteUrl->set) {
            $result['note_url'] = $this->noteUrl->value;
        }
        if ($this->clientId->set) {
            $result['client_id'] = $this->clientId->value;
        }
        if ($this->clientSecret->set) {
            $result['client_secret'] = $this->clientSecret->value;
        }
        if ($this->fingerprint->set) {
            $result['fingerprint'] = $this->fingerprint->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            scopes: \array_key_exists('scopes', $data)
                ? OptNilStringArray::some($data['scopes'])
                : OptNilStringArray::none(),
            note: \array_key_exists('note', $data)
                ? OptString::some($data['note'])
                : OptString::none(),
            noteUrl: \array_key_exists('note_url', $data)
                ? OptString::some($data['note_url'])
                : OptString::none(),
            clientId: \array_key_exists('client_id', $data)
                ? OptString::some($data['client_id'])
                : OptString::none(),
            clientSecret: \array_key_exists('client_secret', $data)
                ? OptString::some($data['client_secret'])
                : OptString::none(),
            fingerprint: \array_key_exists('fingerprint', $data)
                ? OptString::some($data['fingerprint'])
                : OptString::none(),
        );
    }
}
