<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * OptNilSecretScanningAlertResolution is optional nullable SecretScanningAlertResolution.
 */
final readonly class OptNilSecretScanningAlertResolution
{
    public function __construct(
        public ?SecretScanningAlertResolution $value,
        public bool $set,
    ) {}

    /**
     * Create an unset optional.
     */
    public static function none(): self
    {
        return new self(null, false);
    }

    /**
     * Create a set optional with the given value.
     */
    public static function some(?SecretScanningAlertResolution $value): self
    {
        return new self($value, true);
    }
}
