<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * OptValidationErrorErrorsItemValue is optional mixed|string|int|array.
 */
final readonly class OptValidationErrorErrorsItemValue
{
    public function __construct(
        public null|mixed|string|int|array $value,
        public bool $set,
    ) {}

    /**
     * Create an unset optional.
     */
    public static function none(): self
    {
        return new self(null, false);
    }

    /**
     * Create a set optional with the given value.
     */
    public static function some(mixed|string|int|array $value): self
    {
        return new self($value, true);
    }
}
