<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Secrets for GitHub Actions for an organization.
 *
 * Ref: #/components/schemas/organization-actions-secret
 */
final readonly class OrganizationActionsSecret implements JsonSerializable
{
    public function __construct(
        public string $name,
        public string $createdAt,
        public string $updatedAt,
        public OrganizationActionsSecretVisibility $visibility,
        public OptURI $selectedRepositoriesUrl,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['name'] = $this->name;
        $result['created_at'] = $this->createdAt;
        $result['updated_at'] = $this->updatedAt;
        $result['visibility'] = $this->visibility->value;
        if ($this->selectedRepositoriesUrl->set) {
            $result['selected_repositories_url'] = $this->selectedRepositoriesUrl->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            name: $data['name'],
            createdAt: $data['created_at'],
            updatedAt: $data['updated_at'],
            visibility: OrganizationActionsSecretVisibility::from($data['visibility']),
            selectedRepositoriesUrl: \array_key_exists('selected_repositories_url', $data)
                ? OptURI::some($data['selected_repositories_url'])
                : OptURI::none(),
        );
    }
}
