<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 * Specify role for new member. Can be one of:
 * \* `admin` - Organization owners with full administrative rights to the organization and complete
 * access to all repositories and teams.
 * \* `direct_member` - Non-owner organization members with ability to see other members and join
 * teams by invitation.
 * \* `billing_manager` - Non-owner organization members with ability to manage the billing settings
 * of your organization.
 */
enum OrgsCreateInvitationReqRole: string
{
    case OrgsCreateInvitationReqRoleAdmin = 'admin';
    case OrgsCreateInvitationReqRoleDirectMember = 'direct_member';
    case OrgsCreateInvitationReqRoleBillingManager = 'billing_manager';
}
