<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated Params DTO from OpenAPI specification.
 */
final readonly class OrgsGetAuditLogParams
{
    public function __construct(
        public OptString $phrase,
        public OptAuditLogInclude $include,
        public OptString $after,
        public OptString $before,
        public OptAuditLogOrder $order,
        public OptInt $perPage,
        public OptInt $page,
    ) {}

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            phrase: \array_key_exists('phrase', $data)
                ? OptString::some($data['phrase'])
                : OptString::none(),
            include: \array_key_exists('include', $data)
                ? OptAuditLogInclude::some($data['include'])
                : OptAuditLogInclude::none(),
            after: \array_key_exists('after', $data)
                ? OptString::some($data['after'])
                : OptString::none(),
            before: \array_key_exists('before', $data)
                ? OptString::some($data['before'])
                : OptString::none(),
            order: \array_key_exists('order', $data)
                ? OptAuditLogOrder::some($data['order'])
                : OptAuditLogOrder::none(),
            perPage: \array_key_exists('per_page', $data)
                ? OptInt::some($data['per_page'])
                : OptInt::none(),
            page: \array_key_exists('page', $data)
                ? OptInt::some($data['page'])
                : OptInt::none(),
        );
    }
}
