<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 */
enum PackagesGetAllPackageVersionsForPackageOwnedByAuthenticatedUserState: string
{
    case PackagesGetAllPackageVersionsForPackageOwnedByAuthenticatedUserStateActive = 'active';
    case PackagesGetAllPackageVersionsForPackageOwnedByAuthenticatedUserStateDeleted = 'deleted';
}
