<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Pages Health Check Status.
 *
 * Ref: #/components/schemas/pages-health-check
 */
final readonly class PagesHealthCheck implements JsonSerializable
{
    public function __construct(
        public OptPagesHealthCheckDomain $domain,
        public OptNilPagesHealthCheckAltDomain $altDomain,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->domain->set) {
            $result['domain'] = $this->domain->value?->jsonSerialize();
        }
        if ($this->altDomain->set) {
            $result['alt_domain'] = $this->altDomain->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            domain: \array_key_exists('domain', $data)
                ? OptPagesHealthCheckDomain::some(PagesHealthCheckDomain::fromArray($data['domain']))
                : OptPagesHealthCheckDomain::none(),
            altDomain: \array_key_exists('alt_domain', $data)
                ? OptNilPagesHealthCheckAltDomain::some(PagesHealthCheckAltDomain::fromArray($data['alt_domain']))
                : OptNilPagesHealthCheckAltDomain::none(),
        );
    }
}
