<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Porter Large File.
 *
 * Ref: #/components/schemas/porter-large-file
 */
final readonly class PorterLargeFile implements JsonSerializable
{
    public function __construct(
        public string $refName,
        public string $path,
        public string $oid,
        public int $size,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['ref_name'] = $this->refName;
        $result['path'] = $this->path;
        $result['oid'] = $this->oid;
        $result['size'] = $this->size;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            refName: $data['ref_name'],
            path: $data['path'],
            oid: $data['oid'],
            size: $data['size'],
        );
    }
}
