<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class ProjectsUpdateReq implements JsonSerializable
{
    public function __construct(
        public OptString $name,
        public OptNilString $body,
        public OptString $state,
        public OptProjectsUpdateReqOrganizationPermission $organizationPermission,
        public OptBool $private,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->name->set) {
            $result['name'] = $this->name->value;
        }
        if ($this->body->set) {
            $result['body'] = $this->body->value;
        }
        if ($this->state->set) {
            $result['state'] = $this->state->value;
        }
        if ($this->organizationPermission->set) {
            $result['organization_permission'] = $this->organizationPermission->value?->value;
        }
        if ($this->private->set) {
            $result['private'] = $this->private->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            name: \array_key_exists('name', $data)
                ? OptString::some($data['name'])
                : OptString::none(),
            body: \array_key_exists('body', $data)
                ? OptNilString::some($data['body'])
                : OptNilString::none(),
            state: \array_key_exists('state', $data)
                ? OptString::some($data['state'])
                : OptString::none(),
            organizationPermission: \array_key_exists('organization_permission', $data)
                ? OptProjectsUpdateReqOrganizationPermission::some(ProjectsUpdateReqOrganizationPermission::from($data['organization_permission']))
                : OptProjectsUpdateReqOrganizationPermission::none(),
            private: \array_key_exists('private', $data)
                ? OptBool::some($data['private'])
                : OptBool::none(),
        );
    }
}
