<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class ProjectsCreateForOrgReq implements JsonSerializable
{
    public function __construct(
        public string $name,
        public OptString $body,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['name'] = $this->name;
        if ($this->body->set) {
            $result['body'] = $this->body->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            name: $data['name'],
            body: \array_key_exists('body', $data)
                ? OptString::some($data['body'])
                : OptString::none(),
        );
    }
}
