<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Protected Branch Pull Request Review.
 *
 * Ref: #/components/schemas/protected-branch-pull-request-review
 */
final readonly class ProtectedBranchPullRequestReview implements JsonSerializable
{
    public function __construct(
        public OptURI $url,
        public OptProtectedBranchPullRequestReviewDismissalRestrictions $dismissalRestrictions,
        public bool $dismissStaleReviews,
        public bool $requireCodeOwnerReviews,
        public OptInt $requiredApprovingReviewCount,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->url->set) {
            $result['url'] = $this->url->value;
        }
        if ($this->dismissalRestrictions->set) {
            $result['dismissal_restrictions'] = $this->dismissalRestrictions->value?->jsonSerialize();
        }
        $result['dismiss_stale_reviews'] = $this->dismissStaleReviews;
        $result['require_code_owner_reviews'] = $this->requireCodeOwnerReviews;
        if ($this->requiredApprovingReviewCount->set) {
            $result['required_approving_review_count'] = $this->requiredApprovingReviewCount->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            url: \array_key_exists('url', $data)
                ? OptURI::some($data['url'])
                : OptURI::none(),
            dismissalRestrictions: \array_key_exists('dismissal_restrictions', $data)
                ? OptProtectedBranchPullRequestReviewDismissalRestrictions::some(ProtectedBranchPullRequestReviewDismissalRestrictions::fromArray($data['dismissal_restrictions']))
                : OptProtectedBranchPullRequestReviewDismissalRestrictions::none(),
            dismissStaleReviews: $data['dismiss_stale_reviews'],
            requireCodeOwnerReviews: $data['require_code_owner_reviews'],
            requiredApprovingReviewCount: \array_key_exists('required_approving_review_count', $data)
                ? OptInt::some($data['required_approving_review_count'])
                : OptInt::none(),
        );
    }
}
