<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 * Merge method to use. Possible values are `merge`, `squash` or `rebase`. Default is `merge`.
 */
enum PullsMergeReqMergeMethod: string
{
    case PullsMergeReqMergeMethodMerge = 'merge';
    case PullsMergeReqMergeMethodSquash = 'squash';
    case PullsMergeReqMergeMethodRebase = 'rebase';
}
