<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 * **Required when using multi-line comments**. To create multi-line comments, you must use the
 * `comfort-fade` preview header. The `start_side` is the starting side of the diff that the comment
 * applies to. Can be `LEFT` or `RIGHT`. To learn more about multi-line comments, see "[Commenting on
 * a pull request](https://help.github.
 * com/en/articles/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request)" in the
 * GitHub Help documentation. See `side` in this table for additional context.
 */
enum PullsCreateReviewCommentReqStartSide: string
{
    case PullsCreateReviewCommentReqStartSideLEFT = 'LEFT';
    case PullsCreateReviewCommentReqStartSideRIGHT = 'RIGHT';
    case PullsCreateReviewCommentReqStartSideSide = 'side';
}
