<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class PullsCreateReq implements JsonSerializable
{
    public function __construct(
        public OptString $title,
        public string $head,
        public string $base,
        public OptString $body,
        public OptBool $maintainerCanModify,
        public OptBool $draft,
        public OptInt $issue,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->title->set) {
            $result['title'] = $this->title->value;
        }
        $result['head'] = $this->head;
        $result['base'] = $this->base;
        if ($this->body->set) {
            $result['body'] = $this->body->value;
        }
        if ($this->maintainerCanModify->set) {
            $result['maintainer_can_modify'] = $this->maintainerCanModify->value;
        }
        if ($this->draft->set) {
            $result['draft'] = $this->draft->value;
        }
        if ($this->issue->set) {
            $result['issue'] = $this->issue->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            title: \array_key_exists('title', $data)
                ? OptString::some($data['title'])
                : OptString::none(),
            head: $data['head'],
            base: $data['base'],
            body: \array_key_exists('body', $data)
                ? OptString::some($data['body'])
                : OptString::none(),
            maintainerCanModify: \array_key_exists('maintainer_can_modify', $data)
                ? OptBool::some($data['maintainer_can_modify'])
                : OptBool::none(),
            draft: \array_key_exists('draft', $data)
                ? OptBool::some($data['draft'])
                : OptBool::none(),
            issue: \array_key_exists('issue', $data)
                ? OptInt::some($data['issue'])
                : OptInt::none(),
        );
    }
}
