<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Pull Request Review Comments are comments on a portion of the Pull Request's diff.
 *
 * Ref: #/components/schemas/pull-request-review-comment
 */
final readonly class PullRequestReviewComment implements JsonSerializable
{
    public function __construct(
        public string $url,
        public ?int $pullRequestReviewId,
        public int $id,
        public string $nodeId,
        public string $diffHunk,
        public string $path,
        public int $position,
        public int $originalPosition,
        public string $commitId,
        public string $originalCommitId,
        public OptInt $inReplyToId,
        public SimpleUser $user,
        public string $body,
        public string $createdAt,
        public string $updatedAt,
        public string $htmlUrl,
        public string $pullRequestUrl,
        public AuthorAssociation $authorAssociation,
        public PullRequestReviewCommentLinks $links,
        public OptNilInt $startLine,
        public OptNilInt $originalStartLine,
        public OptNilPullRequestReviewCommentStartSide $startSide,
        public OptInt $line,
        public OptInt $originalLine,
        public OptPullRequestReviewCommentSide $side,
        public OptReactionRollup $reactions,
        public OptString $bodyHtml,
        public OptString $bodyText,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['url'] = $this->url;
        $result['pull_request_review_id'] = $this->pullRequestReviewId;
        $result['id'] = $this->id;
        $result['node_id'] = $this->nodeId;
        $result['diff_hunk'] = $this->diffHunk;
        $result['path'] = $this->path;
        $result['position'] = $this->position;
        $result['original_position'] = $this->originalPosition;
        $result['commit_id'] = $this->commitId;
        $result['original_commit_id'] = $this->originalCommitId;
        if ($this->inReplyToId->set) {
            $result['in_reply_to_id'] = $this->inReplyToId->value;
        }
        $result['user'] = $this->user->jsonSerialize();
        $result['body'] = $this->body;
        $result['created_at'] = $this->createdAt;
        $result['updated_at'] = $this->updatedAt;
        $result['html_url'] = $this->htmlUrl;
        $result['pull_request_url'] = $this->pullRequestUrl;
        $result['author_association'] = $this->authorAssociation->value;
        $result['_links'] = $this->links->jsonSerialize();
        if ($this->startLine->set) {
            $result['start_line'] = $this->startLine->value;
        }
        if ($this->originalStartLine->set) {
            $result['original_start_line'] = $this->originalStartLine->value;
        }
        if ($this->startSide->set) {
            $result['start_side'] = $this->startSide->value?->value;
        }
        if ($this->line->set) {
            $result['line'] = $this->line->value;
        }
        if ($this->originalLine->set) {
            $result['original_line'] = $this->originalLine->value;
        }
        if ($this->side->set) {
            $result['side'] = $this->side->value?->value;
        }
        if ($this->reactions->set) {
            $result['reactions'] = $this->reactions->value?->jsonSerialize();
        }
        if ($this->bodyHtml->set) {
            $result['body_html'] = $this->bodyHtml->value;
        }
        if ($this->bodyText->set) {
            $result['body_text'] = $this->bodyText->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            url: $data['url'],
            pullRequestReviewId: $data['pull_request_review_id'],
            id: $data['id'],
            nodeId: $data['node_id'],
            diffHunk: $data['diff_hunk'],
            path: $data['path'],
            position: $data['position'],
            originalPosition: $data['original_position'],
            commitId: $data['commit_id'],
            originalCommitId: $data['original_commit_id'],
            inReplyToId: \array_key_exists('in_reply_to_id', $data)
                ? OptInt::some($data['in_reply_to_id'])
                : OptInt::none(),
            user: SimpleUser::fromArray($data['user']),
            body: $data['body'],
            createdAt: $data['created_at'],
            updatedAt: $data['updated_at'],
            htmlUrl: $data['html_url'],
            pullRequestUrl: $data['pull_request_url'],
            authorAssociation: AuthorAssociation::from($data['author_association']),
            links: PullRequestReviewCommentLinks::fromArray($data['_links']),
            startLine: \array_key_exists('start_line', $data)
                ? OptNilInt::some($data['start_line'])
                : OptNilInt::none(),
            originalStartLine: \array_key_exists('original_start_line', $data)
                ? OptNilInt::some($data['original_start_line'])
                : OptNilInt::none(),
            startSide: \array_key_exists('start_side', $data)
                ? OptNilPullRequestReviewCommentStartSide::some(PullRequestReviewCommentStartSide::from($data['start_side']))
                : OptNilPullRequestReviewCommentStartSide::none(),
            line: \array_key_exists('line', $data)
                ? OptInt::some($data['line'])
                : OptInt::none(),
            originalLine: \array_key_exists('original_line', $data)
                ? OptInt::some($data['original_line'])
                : OptInt::none(),
            side: \array_key_exists('side', $data)
                ? OptPullRequestReviewCommentSide::some(PullRequestReviewCommentSide::from($data['side']))
                : OptPullRequestReviewCommentSide::none(),
            reactions: \array_key_exists('reactions', $data)
                ? OptReactionRollup::some(ReactionRollup::fromArray($data['reactions']))
                : OptReactionRollup::none(),
            bodyHtml: \array_key_exists('body_html', $data)
                ? OptString::some($data['body_html'])
                : OptString::none(),
            bodyText: \array_key_exists('body_text', $data)
                ? OptString::some($data['body_text'])
                : OptString::none(),
        );
    }
}
