<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class PullRequestMinimalHead implements JsonSerializable
{
    public function __construct(
        public string $ref,
        public string $sha,
        public PullRequestMinimalHeadRepo $repo,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['ref'] = $this->ref;
        $result['sha'] = $this->sha;
        $result['repo'] = $this->repo->jsonSerialize();

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            ref: $data['ref'],
            sha: $data['sha'],
            repo: PullRequestMinimalHeadRepo::fromArray($data['repo']),
        );
    }
}
