<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class PullRequestHeadRepoLicense implements JsonSerializable
{
    public function __construct(
        public string $key,
        public string $name,
        public ?string $url,
        public ?string $spdxId,
        public string $nodeId,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['key'] = $this->key;
        $result['name'] = $this->name;
        $result['url'] = $this->url;
        $result['spdx_id'] = $this->spdxId;
        $result['node_id'] = $this->nodeId;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            key: $data['key'],
            name: $data['name'],
            url: $data['url'],
            spdxId: $data['spdx_id'],
            nodeId: $data['node_id'],
        );
    }
}
