<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Pull Request Review Request.
 *
 * Ref: #/components/schemas/pull-request-review-request
 */
final readonly class PullRequestReviewRequest implements JsonSerializable
{
    public function __construct(
        /** @var SimpleUser[] */
        public array $users,
        /** @var Team[] */
        public array $teams,
    ) {
        foreach ($this->users as $item) {
            if (!$item instanceof SimpleUser) {
                throw new \InvalidArgumentException('Expected instance of SimpleUser');
            }
        }
        foreach ($this->teams as $item) {
            if (!$item instanceof Team) {
                throw new \InvalidArgumentException('Expected instance of Team');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['users'] = array_map(fn ($item) => $item->jsonSerialize(), $this->users);
        $result['teams'] = array_map(fn ($item) => $item->jsonSerialize(), $this->teams);

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            users: array_map(SimpleUser::fromArray(...), $data['users']),
            teams: array_map(Team::fromArray(...), $data['teams']),
        );
    }
}
