<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 * The [reaction type](https://docs.github.com/rest/reference/reactions#reaction-types) to add to the
 * pull request review comment.
 */
enum ReactionsCreateForPullRequestReviewCommentReqContent: string
{
    case ReactionsCreateForPullRequestReviewCommentReqContentPlus1 = '+1';
    case ReactionsCreateForPullRequestReviewCommentReqContentMinus1 = '-1';
    case ReactionsCreateForPullRequestReviewCommentReqContentLaugh = 'laugh';
    case ReactionsCreateForPullRequestReviewCommentReqContentConfused = 'confused';
    case ReactionsCreateForPullRequestReviewCommentReqContentHeart = 'heart';
    case ReactionsCreateForPullRequestReviewCommentReqContentHooray = 'hooray';
    case ReactionsCreateForPullRequestReviewCommentReqContentRocket = 'rocket';
    case ReactionsCreateForPullRequestReviewCommentReqContentEyes = 'eyes';
}
