<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Reactions to conversations provide a way to help people express their feelings more simply and
 * effectively.
 *
 * Ref: #/components/schemas/reaction
 */
final readonly class Reaction implements JsonSerializable
{
    public function __construct(
        public int $id,
        public string $nodeId,
        public ?NullableSimpleUser $user,
        public ReactionContent $content,
        public string $createdAt,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['id'] = $this->id;
        $result['node_id'] = $this->nodeId;
        $result['user'] = $this->user;
        $result['content'] = $this->content->value;
        $result['created_at'] = $this->createdAt;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            nodeId: $data['node_id'],
            user: $data['user'],
            content: ReactionContent::from($data['content']),
            createdAt: $data['created_at'],
        );
    }
}
