<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated Params DTO from OpenAPI specification.
 */
final readonly class ReactionsListForPullRequestReviewCommentParams
{
    public function __construct(
        public OptReactionsListForPullRequestReviewCommentContent $content,
        public OptInt $perPage,
        public OptInt $page,
    ) {}

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            content: \array_key_exists('content', $data)
                ? OptReactionsListForPullRequestReviewCommentContent::some($data['content'])
                : OptReactionsListForPullRequestReviewCommentContent::none(),
            perPage: \array_key_exists('per_page', $data)
                ? OptInt::some($data['per_page'])
                : OptInt::none(),
            page: \array_key_exists('page', $data)
                ? OptInt::some($data['page'])
                : OptInt::none(),
        );
    }
}
