<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 * State of the release asset.
 */
enum ReleaseAssetState: string
{
    case ReleaseAssetStateUploaded = 'uploaded';
    case ReleaseAssetStateOpen = 'open';
}
