<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class ReposCreateOrUpdateFileContentsReq implements JsonSerializable
{
    public function __construct(
        public string $message,
        public string $content,
        public OptString $sha,
        public OptString $branch,
        public OptReposCreateOrUpdateFileContentsReqCommitter $committer,
        public OptReposCreateOrUpdateFileContentsReqAuthor $author,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['message'] = $this->message;
        $result['content'] = $this->content;
        if ($this->sha->set) {
            $result['sha'] = $this->sha->value;
        }
        if ($this->branch->set) {
            $result['branch'] = $this->branch->value;
        }
        if ($this->committer->set) {
            $result['committer'] = $this->committer->value?->jsonSerialize();
        }
        if ($this->author->set) {
            $result['author'] = $this->author->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            message: $data['message'],
            content: $data['content'],
            sha: \array_key_exists('sha', $data)
                ? OptString::some($data['sha'])
                : OptString::none(),
            branch: \array_key_exists('branch', $data)
                ? OptString::some($data['branch'])
                : OptString::none(),
            committer: \array_key_exists('committer', $data)
                ? OptReposCreateOrUpdateFileContentsReqCommitter::some(ReposCreateOrUpdateFileContentsReqCommitter::fromArray($data['committer']))
                : OptReposCreateOrUpdateFileContentsReqCommitter::none(),
            author: \array_key_exists('author', $data)
                ? OptReposCreateOrUpdateFileContentsReqAuthor::some(ReposCreateOrUpdateFileContentsReqAuthor::fromArray($data['author']))
                : OptReposCreateOrUpdateFileContentsReqAuthor::none(),
        );
    }
}
