<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Repository invitations let you manage who you collaborate with.
 *
 * Ref: #/components/schemas/repository-subscription
 */
final readonly class RepositorySubscription implements JsonSerializable
{
    public function __construct(
        public bool $subscribed,
        public bool $ignored,
        public ?string $reason,
        public string $createdAt,
        public string $url,
        public string $repositoryUrl,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['subscribed'] = $this->subscribed;
        $result['ignored'] = $this->ignored;
        $result['reason'] = $this->reason;
        $result['created_at'] = $this->createdAt;
        $result['url'] = $this->url;
        $result['repository_url'] = $this->repositoryUrl;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            subscribed: $data['subscribed'],
            ignored: $data['ignored'],
            reason: $data['reason'],
            createdAt: $data['created_at'],
            url: $data['url'],
            repositoryUrl: $data['repository_url'],
        );
    }
}
