<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated Params DTO from OpenAPI specification.
 */
final readonly class ReposGetReadmeInDirectoryParams
{
    public function __construct(
        public OptString $ref,
    ) {}

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            ref: \array_key_exists('ref', $data)
                ? OptString::some($data['ref'])
                : OptString::none(),
        );
    }
}
