<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 */
enum ReposListForOrgType: string
{
    case ReposListForOrgTypeAll = 'all';
    case ReposListForOrgTypePublic = 'public';
    case ReposListForOrgTypePrivate = 'private';
    case ReposListForOrgTypeForks = 'forks';
    case ReposListForOrgTypeSources = 'sources';
    case ReposListForOrgTypeMember = 'member';
    case ReposListForOrgTypeInternal = 'internal';
}
