<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class ReposGetPunchCardStatsOKApplicationJson implements JsonSerializable
{
    /**
     * @param CodeFrequencyStat[] $items
     */
    public function __construct(
        public array $items,
    ) {
    }

    /**
     * @return array<int, mixed>
     */
    public function jsonSerialize(): array
    {
        return $this->items;
    }

    /**
     * @param array<int, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self($data);
    }
}
