<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class ReposUpdateWebhookReq implements JsonSerializable
{
    public function __construct(
        public OptReposUpdateWebhookReqConfig $config,
        /** @var string[] */
        public array $events,
        /** @var string[] */
        public array $addEvents,
        /** @var string[] */
        public array $removeEvents,
        public OptBool $active,
    ) {
        foreach ($this->events as $item) {
            if (!is_string($item)) {
                throw new \InvalidArgumentException('Expected string');
            }
        }
        foreach ($this->addEvents as $item) {
            if (!is_string($item)) {
                throw new \InvalidArgumentException('Expected string');
            }
        }
        foreach ($this->removeEvents as $item) {
            if (!is_string($item)) {
                throw new \InvalidArgumentException('Expected string');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->config->set) {
            $result['config'] = $this->config->value?->jsonSerialize();
        }
        $result['events'] = $this->events;
        $result['add_events'] = $this->addEvents;
        $result['remove_events'] = $this->removeEvents;
        if ($this->active->set) {
            $result['active'] = $this->active->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            config: \array_key_exists('config', $data)
                ? OptReposUpdateWebhookReqConfig::some(ReposUpdateWebhookReqConfig::fromArray($data['config']))
                : OptReposUpdateWebhookReqConfig::none(),
            events: $data['events'],
            addEvents: $data['add_events'],
            removeEvents: $data['remove_events'],
            active: \array_key_exists('active', $data)
                ? OptBool::some($data['active'])
                : OptBool::none(),
        );
    }
}
