<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated Params DTO from OpenAPI specification.
 */
final readonly class ReposListAutolinksParams
{
    public function __construct(
        public OptInt $page,
    ) {}

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            page: \array_key_exists('page', $data)
                ? OptInt::some($data['page'])
                : OptInt::none(),
        );
    }
}
