<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 */
enum ReposListCollaboratorsAffiliation: string
{
    case ReposListCollaboratorsAffiliationOutside = 'outside';
    case ReposListCollaboratorsAffiliationDirect = 'direct';
    case ReposListCollaboratorsAffiliationAll = 'all';
}
