<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Use the `status` property to enable or disable GitHub Advanced Security for this repository. For
 * more information, see "[About GitHub Advanced
 * Security](/github/getting-started-with-github/learning-about-github/about-github-advanced-security).".
 */
final readonly class ReposUpdateReqSecurityAndAnalysisAdvancedSecurity implements JsonSerializable
{
    public function __construct(
        public OptString $status,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->status->set) {
            $result['status'] = $this->status->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            status: \array_key_exists('status', $data)
                ? OptString::some($data['status'])
                : OptString::none(),
        );
    }
}
