<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class ReposCreateCommitCommentReq implements JsonSerializable
{
    public function __construct(
        public string $body,
        public OptString $path,
        public OptInt $position,
        public OptInt $line,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['body'] = $this->body;
        if ($this->path->set) {
            $result['path'] = $this->path->value;
        }
        if ($this->position->set) {
            $result['position'] = $this->position->value;
        }
        if ($this->line->set) {
            $result['line'] = $this->line->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            body: $data['body'],
            path: \array_key_exists('path', $data)
                ? OptString::some($data['path'])
                : OptString::none(),
            position: \array_key_exists('position', $data)
                ? OptInt::some($data['position'])
                : OptInt::none(),
            line: \array_key_exists('line', $data)
                ? OptInt::some($data['line'])
                : OptInt::none(),
        );
    }
}
