<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 * The side of the first line of the range for a multi-line comment.
 */
enum ReviewCommentStartSide: string
{
    case ReviewCommentStartSideLEFT = 'LEFT';
    case ReviewCommentStartSideRIGHT = 'RIGHT';
}
