<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Runner Application.
 *
 * Ref: #/components/schemas/runner-application
 */
final readonly class RunnerApplication implements JsonSerializable
{
    public function __construct(
        public string $os,
        public string $architecture,
        public string $downloadUrl,
        public string $filename,
        public OptString $tempDownloadToken,
        public OptString $sha256Checksum,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['os'] = $this->os;
        $result['architecture'] = $this->architecture;
        $result['download_url'] = $this->downloadUrl;
        $result['filename'] = $this->filename;
        if ($this->tempDownloadToken->set) {
            $result['temp_download_token'] = $this->tempDownloadToken->value;
        }
        if ($this->sha256Checksum->set) {
            $result['sha256_checksum'] = $this->sha256Checksum->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            os: $data['os'],
            architecture: $data['architecture'],
            downloadUrl: $data['download_url'],
            filename: $data['filename'],
            tempDownloadToken: \array_key_exists('temp_download_token', $data)
                ? OptString::some($data['temp_download_token'])
                : OptString::none(),
            sha256Checksum: \array_key_exists('sha256_checksum', $data)
                ? OptString::some($data['sha256_checksum'])
                : OptString::none(),
        );
    }
}
