<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 *
 * Ref: #/components/schemas/runner-groups-org
 */
final readonly class RunnerGroupsOrg implements JsonSerializable
{
    public function __construct(
        public float $id,
        public string $name,
        public string $visibility,
        public bool $default,
        public OptString $selectedRepositoriesUrl,
        public string $runnersUrl,
        public bool $inherited,
        public OptBool $inheritedAllowsPublicRepositories,
        public bool $allowsPublicRepositories,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['id'] = $this->id;
        $result['name'] = $this->name;
        $result['visibility'] = $this->visibility;
        $result['default'] = $this->default;
        if ($this->selectedRepositoriesUrl->set) {
            $result['selected_repositories_url'] = $this->selectedRepositoriesUrl->value;
        }
        $result['runners_url'] = $this->runnersUrl;
        $result['inherited'] = $this->inherited;
        if ($this->inheritedAllowsPublicRepositories->set) {
            $result['inherited_allows_public_repositories'] = $this->inheritedAllowsPublicRepositories->value;
        }
        $result['allows_public_repositories'] = $this->allowsPublicRepositories;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            name: $data['name'],
            visibility: $data['visibility'],
            default: $data['default'],
            selectedRepositoriesUrl: \array_key_exists('selected_repositories_url', $data)
                ? OptString::some($data['selected_repositories_url'])
                : OptString::none(),
            runnersUrl: $data['runners_url'],
            inherited: $data['inherited'],
            inheritedAllowsPublicRepositories: \array_key_exists('inherited_allows_public_repositories', $data)
                ? OptBool::some($data['inherited_allows_public_repositories'])
                : OptBool::none(),
            allowsPublicRepositories: $data['allows_public_repositories'],
        );
    }
}
