<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class SearchIssuesAndPullRequestsOK implements JsonSerializable
{
    public function __construct(
        public int $totalCount,
        public bool $incompleteResults,
        /** @var IssueSearchResultItem[] */
        public array $items,
    ) {
        foreach ($this->items as $item) {
            if (!$item instanceof IssueSearchResultItem) {
                throw new \InvalidArgumentException('Expected instance of IssueSearchResultItem');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['total_count'] = $this->totalCount;
        $result['incomplete_results'] = $this->incompleteResults;
        $result['items'] = array_map(fn ($item) => $item->jsonSerialize(), $this->items);

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            totalCount: $data['total_count'],
            incompleteResults: $data['incomplete_results'],
            items: array_map(IssueSearchResultItem::fromArray(...), $data['items']),
        );
    }
}
