<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 *
 * Ref: #/components/schemas/simple-commit-status
 */
final readonly class SimpleCommitStatus implements JsonSerializable
{
    public function __construct(
        public ?string $description,
        public int $id,
        public string $nodeId,
        public string $state,
        public string $context,
        public string $targetUrl,
        public OptNilBool $required,
        public ?string $avatarUrl,
        public string $url,
        public string $createdAt,
        public string $updatedAt,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['description'] = $this->description;
        $result['id'] = $this->id;
        $result['node_id'] = $this->nodeId;
        $result['state'] = $this->state;
        $result['context'] = $this->context;
        $result['target_url'] = $this->targetUrl;
        if ($this->required->set) {
            $result['required'] = $this->required->value;
        }
        $result['avatar_url'] = $this->avatarUrl;
        $result['url'] = $this->url;
        $result['created_at'] = $this->createdAt;
        $result['updated_at'] = $this->updatedAt;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            description: $data['description'],
            id: $data['id'],
            nodeId: $data['node_id'],
            state: $data['state'],
            context: $data['context'],
            targetUrl: $data['target_url'],
            required: \array_key_exists('required', $data)
                ? OptNilBool::some($data['required'])
                : OptNilBool::none(),
            avatarUrl: $data['avatar_url'],
            url: $data['url'],
            createdAt: $data['created_at'],
            updatedAt: $data['updated_at'],
        );
    }
}
