<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class TeamsCreateOrUpdateIdpGroupConnectionsLegacyReqGroupsItem implements JsonSerializable
{
    public function __construct(
        public string $groupId,
        public string $groupName,
        public string $groupDescription,
        public OptString $id,
        public OptString $name,
        public OptString $description,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['group_id'] = $this->groupId;
        $result['group_name'] = $this->groupName;
        $result['group_description'] = $this->groupDescription;
        if ($this->id->set) {
            $result['id'] = $this->id->value;
        }
        if ($this->name->set) {
            $result['name'] = $this->name->value;
        }
        if ($this->description->set) {
            $result['description'] = $this->description->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            groupId: $data['group_id'],
            groupName: $data['group_name'],
            groupDescription: $data['group_description'],
            id: \array_key_exists('id', $data)
                ? OptString::some($data['id'])
                : OptString::none(),
            name: \array_key_exists('name', $data)
                ? OptString::some($data['name'])
                : OptString::none(),
            description: \array_key_exists('description', $data)
                ? OptString::some($data['description'])
                : OptString::none(),
        );
    }
}
