<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class TeamsCreateDiscussionInOrgReq implements JsonSerializable
{
    public function __construct(
        public string $title,
        public string $body,
        public OptBool $private,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['title'] = $this->title;
        $result['body'] = $this->body;
        if ($this->private->set) {
            $result['private'] = $this->private->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            title: $data['title'],
            body: $data['body'],
            private: \array_key_exists('private', $data)
                ? OptBool::some($data['private'])
                : OptBool::none(),
        );
    }
}
