<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class TeamsAddOrUpdateMembershipForUserInOrgReq implements JsonSerializable
{
    public function __construct(
        public OptTeamsAddOrUpdateMembershipForUserInOrgReqRole $role,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->role->set) {
            $result['role'] = $this->role->value?->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            role: \array_key_exists('role', $data)
                ? OptTeamsAddOrUpdateMembershipForUserInOrgReqRole::some(TeamsAddOrUpdateMembershipForUserInOrgReqRole::from($data['role']))
                : OptTeamsAddOrUpdateMembershipForUserInOrgReqRole::none(),
        );
    }
}
