<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 * The role of the user in the team.
 */
enum TeamMembershipRole: string
{
    case TeamMembershipRoleMember = 'member';
    case TeamMembershipRoleMaintainer = 'maintainer';
}
