<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class TeamPermissions implements JsonSerializable
{
    public function __construct(
        public bool $pull,
        public bool $triage,
        public bool $push,
        public bool $maintain,
        public bool $admin,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['pull'] = $this->pull;
        $result['triage'] = $this->triage;
        $result['push'] = $this->push;
        $result['maintain'] = $this->maintain;
        $result['admin'] = $this->admin;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            pull: $data['pull'],
            triage: $data['triage'],
            push: $data['push'],
            maintain: $data['maintain'],
            admin: $data['admin'],
        );
    }
}
