<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class UsersCreateGpgKeyForAuthenticatedReq implements JsonSerializable
{
    public function __construct(
        public string $armoredPublicKey,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['armored_public_key'] = $this->armoredPublicKey;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            armoredPublicKey: $data['armored_public_key'],
        );
    }
}
