<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Deletes one or more email addresses from your GitHub account. Must contain at least one email
 * address. **Note:** Alternatively, you can pass a single email address or an `array` of emails
 * addresses directly, but we recommend that you pass an object using the `emails` key.
 */
final readonly class UsersDeleteEmailForAuthenticatedReq0 implements JsonSerializable
{
    public function __construct(
        /** @var string[] */
        public array $emails,
    ) {
        foreach ($this->emails as $item) {
            if (!is_string($item)) {
                throw new \InvalidArgumentException('Expected string');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['emails'] = $this->emails;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            emails: $data['emails'],
        );
    }
}
