<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * View Traffic.
 *
 * Ref: #/components/schemas/view-traffic
 */
final readonly class ViewTraffic implements JsonSerializable
{
    public function __construct(
        public int $count,
        public int $uniques,
        /** @var Traffic[] */
        public array $views,
    ) {
        foreach ($this->views as $item) {
            if (!$item instanceof Traffic) {
                throw new \InvalidArgumentException('Expected instance of Traffic');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['count'] = $this->count;
        $result['uniques'] = $this->uniques;
        $result['views'] = array_map(fn ($item) => $item->jsonSerialize(), $this->views);

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            count: $data['count'],
            uniques: $data['uniques'],
            views: array_map(Traffic::fromArray(...), $data['views']),
        );
    }
}
