<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Workflow Run Usage.
 *
 * Ref: #/components/schemas/workflow-run-usage
 */
final readonly class WorkflowRunUsage implements JsonSerializable
{
    public function __construct(
        public WorkflowRunUsageBillable $billable,
        public OptInt $runDurationMs,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['billable'] = $this->billable->jsonSerialize();
        if ($this->runDurationMs->set) {
            $result['run_duration_ms'] = $this->runDurationMs->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            billable: WorkflowRunUsageBillable::fromArray($data['billable']),
            runDurationMs: \array_key_exists('run_duration_ms', $data)
                ? OptInt::some($data['run_duration_ms'])
                : OptInt::none(),
        );
    }
}
