<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class WorkflowRunUsageBillableUBUNTU implements JsonSerializable
{
    public function __construct(
        public int $totalMs,
        public int $jobs,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['total_ms'] = $this->totalMs;
        $result['jobs'] = $this->jobs;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            totalMs: $data['total_ms'],
            jobs: $data['jobs'],
        );
    }
}
