<?php

// Code generated by lcodegen, DO NOT EDIT.

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CaptchaController;
use App\Http\Controllers\DislikeController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\MobileController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Auto-generated API routes from OpenAPI specification.
|
| To include these routes in your application, add the following line
| to routes/web.php or routes/api.php:
|
| require __DIR__.'/openapi.php';
|
*/

// Captcha routes
Route::get('/api/captcha/2chcaptcha/id', [CaptchaController::class, 'apiCaptcha2chcaptchaIdGet'])
    ->name('captcha.api_captcha2chcaptcha_id_get');
Route::get('/api/captcha/2chcaptcha/show', [CaptchaController::class, 'apiCaptcha2chcaptchaShowGet'])
    ->name('captcha.api_captcha2chcaptcha_show_get');
Route::get('/api/captcha/app/id/{public_key}', [CaptchaController::class, 'apiCaptchaAppIdPublicKeyGet'])
    ->name('captcha.api_captcha_app_id_public_key_get');
Route::get('/api/captcha/invisible_recaptcha/id', [CaptchaController::class, 'apiCaptchaInvisibleRecaptchaIdGet'])
    ->name('captcha.api_captcha_invisible_recaptcha_id_get');
Route::get('/api/captcha/invisible_recaptcha/mobile', [CaptchaController::class, 'apiCaptchaInvisibleRecaptchaMobileGet'])
    ->name('captcha.api_captcha_invisible_recaptcha_mobile_get');
Route::get('/api/captcha/recaptcha/id', [CaptchaController::class, 'apiCaptchaRecaptchaIdGet'])
    ->name('captcha.api_captcha_recaptcha_id_get');
Route::get('/api/captcha/recaptcha/mobile', [CaptchaController::class, 'apiCaptchaRecaptchaMobileGet'])
    ->name('captcha.api_captcha_recaptcha_mobile_get');

// Dislike routes
Route::get('/api/dislike', [DislikeController::class, 'apiDislikeGet'])
    ->name('dislike.api_dislike_get');

// Like routes
Route::get('/api/like', [LikeController::class, 'apiLikeGet'])
    ->name('like.api_like_get');

// Mobile routes
Route::get('/api/mobile/v2/after/{board}/{thread}/{num}', [MobileController::class, 'apiMobileV2AfterBoardThreadNumGet'])
    ->name('mobile.api_mobile_v2_after_board_thread_num_get');
Route::get('/api/mobile/v2/boards', [MobileController::class, 'apiMobileV2BoardsGet'])
    ->name('mobile.api_mobile_v2_boards_get');
Route::get('/api/mobile/v2/info/{board}/{thread}', [MobileController::class, 'apiMobileV2InfoBoardThreadGet'])
    ->name('mobile.api_mobile_v2_info_board_thread_get');
Route::get('/api/mobile/v2/post/{board}/{num}', [MobileController::class, 'apiMobileV2PostBoardNumGet'])
    ->name('mobile.api_mobile_v2_post_board_num_get');

// User routes
Route::post('/user/passlogin', [UserController::class, 'userPassloginPost'])
    ->name('user.user_passlogin_post');
Route::post('/user/posting', [UserController::class, 'userPostingPost'])
    ->name('user.user_posting_post');
Route::post('/user/report', [UserController::class, 'userReportPost'])
    ->name('user.user_report_post');
