<?php

// Code generated by lcodegen, DO NOT EDIT.

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AnswerController;
use App\Http\Controllers\AudioController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\ClassificationController;
use App\Http\Controllers\CompletionController;
use App\Http\Controllers\EditController;
use App\Http\Controllers\EmbeddingController;
use App\Http\Controllers\EngineController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\FineTuneController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\ModelController;
use App\Http\Controllers\ModerationController;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Auto-generated API routes from OpenAPI specification.
|
| To include these routes in your application, add the following line
| to routes/web.php or routes/api.php:
|
| require __DIR__.'/openapi.php';
|
*/

// Answer routes
Route::post('/answers', [AnswerController::class, 'createAnswer'])
    ->name('answer.create_answer');

// Audio routes
Route::post('/audio/transcriptions', [AudioController::class, 'createTranscription'])
    ->name('audio.create_transcription');
Route::post('/audio/translations', [AudioController::class, 'createTranslation'])
    ->name('audio.create_translation');

// Chat routes
Route::post('/chat/completions', [ChatController::class, 'createChatCompletion'])
    ->name('chat.create_chat_completion');

// Classification routes
Route::post('/classifications', [ClassificationController::class, 'createClassification'])
    ->name('classification.create_classification');

// Completion routes
Route::post('/completions', [CompletionController::class, 'createCompletion'])
    ->name('completion.create_completion');

// Edit routes
Route::post('/edits', [EditController::class, 'createEdit'])
    ->name('edit.create_edit');

// Embedding routes
Route::post('/embeddings', [EmbeddingController::class, 'createEmbedding'])
    ->name('embedding.create_embedding');

// Engine routes
Route::post('/engines/{engine_id}/search', [EngineController::class, 'createSearch'])
    ->name('engine.create_search');
Route::get('/engines', [EngineController::class, 'listEngines'])
    ->name('engine.list_engines');
Route::get('/engines/{engine_id}', [EngineController::class, 'retrieveEngine'])
    ->name('engine.retrieve_engine');

// File routes
Route::post('/files', [FileController::class, 'createFile'])
    ->name('file.create_file');
Route::delete('/files/{file_id}', [FileController::class, 'deleteFile'])
    ->name('file.delete_file');
Route::get('/files/{file_id}/content', [FileController::class, 'downloadFile'])
    ->name('file.download_file');
Route::get('/files', [FileController::class, 'listFiles'])
    ->name('file.list_files');
Route::get('/files/{file_id}', [FileController::class, 'retrieveFile'])
    ->name('file.retrieve_file');

// FineTune routes
Route::post('/fine-tunes/{fine_tune_id}/cancel', [FineTuneController::class, 'cancelFineTune'])
    ->name('finetune.cancel_fine_tune');
Route::post('/fine-tunes', [FineTuneController::class, 'createFineTune'])
    ->name('finetune.create_fine_tune');
Route::get('/fine-tunes/{fine_tune_id}/events', [FineTuneController::class, 'listFineTuneEvents'])
    ->name('finetune.list_fine_tune_events');
Route::get('/fine-tunes', [FineTuneController::class, 'listFineTunes'])
    ->name('finetune.list_fine_tunes');
Route::get('/fine-tunes/{fine_tune_id}', [FineTuneController::class, 'retrieveFineTune'])
    ->name('finetune.retrieve_fine_tune');

// Image routes
Route::post('/images/generations', [ImageController::class, 'createImage'])
    ->name('image.create_image');
Route::post('/images/edits', [ImageController::class, 'createImageEdit'])
    ->name('image.create_image_edit');
Route::post('/images/variations', [ImageController::class, 'createImageVariation'])
    ->name('image.create_image_variation');

// Model routes
Route::delete('/models/{model}', [ModelController::class, 'deleteModel'])
    ->name('model.delete_model');
Route::get('/models', [ModelController::class, 'listModels'])
    ->name('model.list_models');
Route::get('/models/{model}', [ModelController::class, 'retrieveModel'])
    ->name('model.retrieve_model');

// Moderation routes
Route::post('/moderations', [ModerationController::class, 'createModeration'])
    ->name('moderation.create_moderation');
