<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class CreateSearchResponseDataItem implements JsonSerializable
{
    public function __construct(
        public OptString $object,
        public OptInt $document,
        public OptFloat64 $score,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->object->set) {
            $result['object'] = $this->object->value;
        }
        if ($this->document->set) {
            $result['document'] = $this->document->value;
        }
        if ($this->score->set) {
            $result['score'] = $this->score->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            object: \array_key_exists('object', $data)
                ? OptString::some($data['object'])
                : OptString::none(),
            document: \array_key_exists('document', $data)
                ? OptInt::some($data['document'])
                : OptInt::none(),
            score: \array_key_exists('score', $data)
                ? OptFloat64::some($data['score'])
                : OptFloat64::none(),
        );
    }
}
