<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class CreateClassificationResponseSelectedExamplesItem implements JsonSerializable
{
    public function __construct(
        public OptInt $document,
        public OptString $text,
        public OptString $label,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->document->set) {
            $result['document'] = $this->document->value;
        }
        if ($this->text->set) {
            $result['text'] = $this->text->value;
        }
        if ($this->label->set) {
            $result['label'] = $this->label->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            document: \array_key_exists('document', $data)
                ? OptInt::some($data['document'])
                : OptInt::none(),
            text: \array_key_exists('text', $data)
                ? OptString::some($data['text'])
                : OptString::none(),
            label: \array_key_exists('label', $data)
                ? OptString::some($data['label'])
                : OptString::none(),
        );
    }
}
