<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 *
 * Ref: #/components/schemas/CreateEmbeddingRequest
 */
final readonly class CreateEmbeddingRequest implements JsonSerializable
{
    public function __construct(
        public string $model,
        public string|array $input,
        public OptString $user,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['model'] = $this->model;
        $result['input'] = $this->input;
        if ($this->user->set) {
            $result['user'] = $this->user->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            model: $data['model'],
            input: $data['input'],
            user: \array_key_exists('user', $data)
                ? OptString::some($data['user'])
                : OptString::none(),
        );
    }
}
