<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 * The format in which the generated images are returned. Must be one of `url` or `b64_json`.
 */
enum CreateImageRequestResponseFormat: string
{
    case CreateImageRequestResponseFormatUrl = 'url';
    case CreateImageRequestResponseFormatB64Json = 'b64_json';
}
