<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class CreateCompletionResponseChoicesItemLogprobs implements JsonSerializable
{
    public function __construct(
        /** @var string[] */
        public array $tokens,
        /** @var float[] */
        public array $tokenLogprobs,
        public array $topLogprobs,
        /** @var int[] */
        public array $textOffset,
    ) {
        foreach ($this->tokens as $item) {
            if (!is_string($item)) {
                throw new \InvalidArgumentException('Expected string');
            }
        }
        foreach ($this->tokenLogprobs as $item) {
            if (!is_float($item)) {
                throw new \InvalidArgumentException('Expected float');
            }
        }
        foreach ($this->textOffset as $item) {
            if (!is_int($item)) {
                throw new \InvalidArgumentException('Expected int');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['tokens'] = $this->tokens;
        $result['token_logprobs'] = $this->tokenLogprobs;
        $result['top_logprobs'] = $this->topLogprobs;
        $result['text_offset'] = $this->textOffset;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            tokens: $data['tokens'],
            tokenLogprobs: $data['token_logprobs'],
            topLogprobs: $data['top_logprobs'],
            textOffset: $data['text_offset'],
        );
    }
}
