<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 *
 * Ref: #/components/schemas/CreateImageVariationRequest
 */
final readonly class CreateImageVariationRequestMultipart implements JsonSerializable
{
    public function __construct(
        public \Illuminate\Http\UploadedFile $image,
        public OptNilInt $n,
        public OptNilCreateImageVariationRequestMultipartSize $size,
        public OptNilCreateImageVariationRequestMultipartResponseFormat $responseFormat,
        public OptString $user,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['image'] = $this->image;
        if ($this->n->set) {
            $result['n'] = $this->n->value;
        }
        if ($this->size->set) {
            $result['size'] = $this->size->value?->value;
        }
        if ($this->responseFormat->set) {
            $result['response_format'] = $this->responseFormat->value?->value;
        }
        if ($this->user->set) {
            $result['user'] = $this->user->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            image: $data['image'],
            n: \array_key_exists('n', $data)
                ? OptNilInt::some($data['n'])
                : OptNilInt::none(),
            size: \array_key_exists('size', $data)
                ? OptNilCreateImageVariationRequestMultipartSize::some(CreateImageVariationRequestMultipartSize::from($data['size']))
                : OptNilCreateImageVariationRequestMultipartSize::none(),
            responseFormat: \array_key_exists('response_format', $data)
                ? OptNilCreateImageVariationRequestMultipartResponseFormat::some(CreateImageVariationRequestMultipartResponseFormat::from($data['response_format']))
                : OptNilCreateImageVariationRequestMultipartResponseFormat::none(),
            user: \array_key_exists('user', $data)
                ? OptString::some($data['user'])
                : OptString::none(),
        );
    }
}
