<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Describes the balloon device statistics.
 *
 * Ref: #/components/schemas/BalloonStats
 */
final readonly class BalloonStats implements JsonSerializable
{
    public function __construct(
        public int $targetPages,
        public int $actualPages,
        public int $targetMib,
        public int $actualMib,
        public OptInt64 $swapIn,
        public OptInt64 $swapOut,
        public OptInt64 $majorFaults,
        public OptInt64 $minorFaults,
        public OptInt64 $freeMemory,
        public OptInt64 $totalMemory,
        public OptInt64 $availableMemory,
        public OptInt64 $diskCaches,
        public OptInt64 $hugetlbAllocations,
        public OptInt64 $hugetlbFailures,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['target_pages'] = $this->targetPages;
        $result['actual_pages'] = $this->actualPages;
        $result['target_mib'] = $this->targetMib;
        $result['actual_mib'] = $this->actualMib;
        if ($this->swapIn->set) {
            $result['swap_in'] = $this->swapIn->value;
        }
        if ($this->swapOut->set) {
            $result['swap_out'] = $this->swapOut->value;
        }
        if ($this->majorFaults->set) {
            $result['major_faults'] = $this->majorFaults->value;
        }
        if ($this->minorFaults->set) {
            $result['minor_faults'] = $this->minorFaults->value;
        }
        if ($this->freeMemory->set) {
            $result['free_memory'] = $this->freeMemory->value;
        }
        if ($this->totalMemory->set) {
            $result['total_memory'] = $this->totalMemory->value;
        }
        if ($this->availableMemory->set) {
            $result['available_memory'] = $this->availableMemory->value;
        }
        if ($this->diskCaches->set) {
            $result['disk_caches'] = $this->diskCaches->value;
        }
        if ($this->hugetlbAllocations->set) {
            $result['hugetlb_allocations'] = $this->hugetlbAllocations->value;
        }
        if ($this->hugetlbFailures->set) {
            $result['hugetlb_failures'] = $this->hugetlbFailures->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            targetPages: $data['target_pages'],
            actualPages: $data['actual_pages'],
            targetMib: $data['target_mib'],
            actualMib: $data['actual_mib'],
            swapIn: \array_key_exists('swap_in', $data)
                ? OptInt64::some($data['swap_in'])
                : OptInt64::none(),
            swapOut: \array_key_exists('swap_out', $data)
                ? OptInt64::some($data['swap_out'])
                : OptInt64::none(),
            majorFaults: \array_key_exists('major_faults', $data)
                ? OptInt64::some($data['major_faults'])
                : OptInt64::none(),
            minorFaults: \array_key_exists('minor_faults', $data)
                ? OptInt64::some($data['minor_faults'])
                : OptInt64::none(),
            freeMemory: \array_key_exists('free_memory', $data)
                ? OptInt64::some($data['free_memory'])
                : OptInt64::none(),
            totalMemory: \array_key_exists('total_memory', $data)
                ? OptInt64::some($data['total_memory'])
                : OptInt64::none(),
            availableMemory: \array_key_exists('available_memory', $data)
                ? OptInt64::some($data['available_memory'])
                : OptInt64::none(),
            diskCaches: \array_key_exists('disk_caches', $data)
                ? OptInt64::some($data['disk_caches'])
                : OptInt64::none(),
            hugetlbAllocations: \array_key_exists('hugetlb_allocations', $data)
                ? OptInt64::some($data['hugetlb_allocations'])
                : OptInt64::none(),
            hugetlbFailures: \array_key_exists('hugetlb_failures', $data)
                ? OptInt64::some($data['hugetlb_failures'])
                : OptInt64::none(),
        );
    }
}
