<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 * The CPU Template defines a set of flags to be disabled from the microvm so that the features
 * exposed to the guest are the same as in the selected instance type.
 *
 * Ref: #/components/schemas/CpuTemplate
 */
enum CpuTemplate: string
{
    case CpuTemplateC3 = 'C3';
    case CpuTemplateT2 = 'T2';
}
