<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 * Type of snapshot to create. It is optional and by default, a full snapshot is created.
 */
enum SnapshotCreateParamsSnapshotType: string
{
    case SnapshotCreateParamsSnapshotTypeFull = 'Full';
    case SnapshotCreateParamsSnapshotTypeDiff = 'Diff';
}
