<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 */
enum VmState: string
{
    case VmStatePaused = 'Paused';
    case VmStateResumed = 'Resumed';
}
