<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Defines a vsock device, backed by a set of Unix Domain Sockets, on the host side. For
 * host-initiated connections, Firecracker will be listening on the Unix socket identified by the
 * path `uds_path`. Firecracker will create this socket, bind and listen on it. Host-initiated
 * connections will be performed by connection to this socket and issuing a connection forwarding
 * request to the desired guest-side vsock port (i.e. `CONNECT 52\n`, to connect to port 52). For
 * guest-initiated connections, Firecracker will expect host software to be bound and listening on
 * Unix sockets at `uds_path_<PORT>`. E.g. "/path/to/host_vsock.sock_52" for port number 52.
 *
 * Ref: #/components/schemas/Vsock
 */
final readonly class Vsock implements JsonSerializable
{
    public function __construct(
        public int $guestCid,
        public string $udsPath,
        public string $vsockId,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['guest_cid'] = $this->guestCid;
        $result['uds_path'] = $this->udsPath;
        $result['vsock_id'] = $this->vsockId;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            guestCid: $data['guest_cid'],
            udsPath: $data['uds_path'],
            vsockId: $data['vsock_id'],
        );
    }
}
