<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Responses\OpenApi\GetCoreAPIVersionsResponse;
use App\Http\Responses\OpenApi\GetCoreV1APIResourcesResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class DefaultController extends Controller
{
    /**
     * GET /api/
     *
     * Get available API versions.
     */
    abstract public function getCoreAPIVersions(
    ): GetCoreAPIVersionsResponse;

    /**
     * GET /api/v1/
     *
     * Get available resources.
     */
    abstract public function getCoreV1APIResources(
    ): GetCoreV1APIResourcesResponse;
}
