<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\ListCoreV1PersistentVolumeClaimForAllNamespacesRequest;
use App\Http\Responses\OpenApi\ListCoreV1PersistentVolumeClaimForAllNamespacesResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class PersistentvolumeclaimController extends Controller
{
    /**
     * GET /api/v1/persistentvolumeclaims
     *
     * List or watch objects of kind PersistentVolumeClaim.
     */
    abstract public function listCoreV1PersistentVolumeClaimForAllNamespaces(
        ListCoreV1PersistentVolumeClaimForAllNamespacesRequest $request,
    ): ListCoreV1PersistentVolumeClaimForAllNamespacesResponse;
}
