<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 *
 * Ref: #/components/schemas/Currency
 */
enum Currency: string
{
    case CurrencyRUB = 'RUB';
    case CurrencyUSD = 'USD';
    case CurrencyEUR = 'EUR';
    case CurrencyGBP = 'GBP';
    case CurrencyHKD = 'HKD';
    case CurrencyCHF = 'CHF';
    case CurrencyJPY = 'JPY';
    case CurrencyCNY = 'CNY';
    case CurrencyTRY = 'TRY';
}
