<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 *
 * Ref: #/components/schemas/SearchMarketInstrumentResponse
 */
final readonly class SearchMarketInstrumentResponse implements JsonSerializable
{
    public function __construct(
        public string $trackingId,
        public string $status,
        public SearchMarketInstrument $payload,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['trackingId'] = $this->trackingId;
        $result['status'] = $this->status;
        $result['payload'] = $this->payload->jsonSerialize();

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            trackingId: $data['trackingId'],
            status: $data['status'],
            payload: SearchMarketInstrument::fromArray($data['payload']),
        );
    }
}
