<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 *
 * Ref: #/components/schemas/Tag
 */
final readonly class Tag implements JsonSerializable
{
    public function __construct(
        public OptInt64 $id,
        public OptString $name,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->id->set) {
            $result['id'] = $this->id->value;
        }
        if ($this->name->set) {
            $result['name'] = $this->name->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: \array_key_exists('id', $data)
                ? OptInt64::some($data['id'])
                : OptInt64::none(),
            name: \array_key_exists('name', $data)
                ? OptString::some($data['name'])
                : OptString::none(),
        );
    }
}
