<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Input for deleteStickerFromSet.
 *
 * Ref: #/components/schemas/deleteStickerFromSet
 */
final readonly class DeleteStickerFromSet implements JsonSerializable
{
    public function __construct(
        public string $sticker,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['sticker'] = $this->sticker;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            sticker: $data['sticker'],
        );
    }
}
