<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Input for getFile.
 *
 * Ref: #/components/schemas/getFile
 */
final readonly class GetFile implements JsonSerializable
{
    public function __construct(
        public string $fileId,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['file_id'] = $this->fileId;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            fileId: $data['file_id'],
        );
    }
}
