<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Represents a link to a file. By default, this file will be sent by the user with an optional
 * caption. Alternatively, you can use input_message_content to send a message with the specified
 * content instead of the file. Currently, only .PDF and .ZIP files can be sent using this method.
 *
 * Ref: #/components/schemas/InlineQueryResultDocument
 */
final readonly class InlineQueryResultDocument implements JsonSerializable
{
    public function __construct(
        public string $type,
        public string $id,
        public string $title,
        public OptString $caption,
        public OptString $parseMode,
        /** @var MessageEntity[] */
        public array $captionEntities,
        public string $documentUrl,
        public string $mimeType,
        public OptString $description,
        public OptInlineKeyboardMarkup $replyMarkup,
        public OptInputMessageContent $inputMessageContent,
        public OptString $thumbUrl,
        public OptInt $thumbWidth,
        public OptInt $thumbHeight,
    ) {
        foreach ($this->captionEntities as $item) {
            if (!$item instanceof MessageEntity) {
                throw new \InvalidArgumentException('Expected instance of MessageEntity');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['type'] = $this->type;
        $result['id'] = $this->id;
        $result['title'] = $this->title;
        if ($this->caption->set) {
            $result['caption'] = $this->caption->value;
        }
        if ($this->parseMode->set) {
            $result['parse_mode'] = $this->parseMode->value;
        }
        $result['caption_entities'] = array_map(fn ($item) => $item->jsonSerialize(), $this->captionEntities);
        $result['document_url'] = $this->documentUrl;
        $result['mime_type'] = $this->mimeType;
        if ($this->description->set) {
            $result['description'] = $this->description->value;
        }
        if ($this->replyMarkup->set) {
            $result['reply_markup'] = $this->replyMarkup->value?->jsonSerialize();
        }
        if ($this->inputMessageContent->set) {
            $result['input_message_content'] = $this->inputMessageContent->value;
        }
        if ($this->thumbUrl->set) {
            $result['thumb_url'] = $this->thumbUrl->value;
        }
        if ($this->thumbWidth->set) {
            $result['thumb_width'] = $this->thumbWidth->value;
        }
        if ($this->thumbHeight->set) {
            $result['thumb_height'] = $this->thumbHeight->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            type: $data['type'],
            id: $data['id'],
            title: $data['title'],
            caption: \array_key_exists('caption', $data)
                ? OptString::some($data['caption'])
                : OptString::none(),
            parseMode: \array_key_exists('parse_mode', $data)
                ? OptString::some($data['parse_mode'])
                : OptString::none(),
            captionEntities: array_map(MessageEntity::fromArray(...), $data['caption_entities']),
            documentUrl: $data['document_url'],
            mimeType: $data['mime_type'],
            description: \array_key_exists('description', $data)
                ? OptString::some($data['description'])
                : OptString::none(),
            replyMarkup: \array_key_exists('reply_markup', $data)
                ? OptInlineKeyboardMarkup::some(InlineKeyboardMarkup::fromArray($data['reply_markup']))
                : OptInlineKeyboardMarkup::none(),
            inputMessageContent: \array_key_exists('input_message_content', $data)
                ? OptInputMessageContent::some($data['input_message_content'])
                : OptInputMessageContent::none(),
            thumbUrl: \array_key_exists('thumb_url', $data)
                ? OptString::some($data['thumb_url'])
                : OptString::none(),
            thumbWidth: \array_key_exists('thumb_width', $data)
                ? OptInt::some($data['thumb_width'])
                : OptInt::none(),
            thumbHeight: \array_key_exists('thumb_height', $data)
                ? OptInt::some($data['thumb_height'])
                : OptInt::none(),
        );
    }
}
