<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Represents a venue. By default, the venue will be sent by the user. Alternatively, you can use
 * input_message_content to send a message with the specified content instead of the venue.
 *
 * Ref: #/components/schemas/InlineQueryResultVenue
 */
final readonly class InlineQueryResultVenue implements JsonSerializable
{
    public function __construct(
        public string $type,
        public string $id,
        public float $latitude,
        public float $longitude,
        public string $title,
        public string $address,
        public OptString $foursquareId,
        public OptString $foursquareType,
        public OptString $googlePlaceId,
        public OptString $googlePlaceType,
        public OptInlineKeyboardMarkup $replyMarkup,
        public OptInputMessageContent $inputMessageContent,
        public OptString $thumbUrl,
        public OptInt $thumbWidth,
        public OptInt $thumbHeight,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['type'] = $this->type;
        $result['id'] = $this->id;
        $result['latitude'] = $this->latitude;
        $result['longitude'] = $this->longitude;
        $result['title'] = $this->title;
        $result['address'] = $this->address;
        if ($this->foursquareId->set) {
            $result['foursquare_id'] = $this->foursquareId->value;
        }
        if ($this->foursquareType->set) {
            $result['foursquare_type'] = $this->foursquareType->value;
        }
        if ($this->googlePlaceId->set) {
            $result['google_place_id'] = $this->googlePlaceId->value;
        }
        if ($this->googlePlaceType->set) {
            $result['google_place_type'] = $this->googlePlaceType->value;
        }
        if ($this->replyMarkup->set) {
            $result['reply_markup'] = $this->replyMarkup->value?->jsonSerialize();
        }
        if ($this->inputMessageContent->set) {
            $result['input_message_content'] = $this->inputMessageContent->value;
        }
        if ($this->thumbUrl->set) {
            $result['thumb_url'] = $this->thumbUrl->value;
        }
        if ($this->thumbWidth->set) {
            $result['thumb_width'] = $this->thumbWidth->value;
        }
        if ($this->thumbHeight->set) {
            $result['thumb_height'] = $this->thumbHeight->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            type: $data['type'],
            id: $data['id'],
            latitude: $data['latitude'],
            longitude: $data['longitude'],
            title: $data['title'],
            address: $data['address'],
            foursquareId: \array_key_exists('foursquare_id', $data)
                ? OptString::some($data['foursquare_id'])
                : OptString::none(),
            foursquareType: \array_key_exists('foursquare_type', $data)
                ? OptString::some($data['foursquare_type'])
                : OptString::none(),
            googlePlaceId: \array_key_exists('google_place_id', $data)
                ? OptString::some($data['google_place_id'])
                : OptString::none(),
            googlePlaceType: \array_key_exists('google_place_type', $data)
                ? OptString::some($data['google_place_type'])
                : OptString::none(),
            replyMarkup: \array_key_exists('reply_markup', $data)
                ? OptInlineKeyboardMarkup::some(InlineKeyboardMarkup::fromArray($data['reply_markup']))
                : OptInlineKeyboardMarkup::none(),
            inputMessageContent: \array_key_exists('input_message_content', $data)
                ? OptInputMessageContent::some($data['input_message_content'])
                : OptInputMessageContent::none(),
            thumbUrl: \array_key_exists('thumb_url', $data)
                ? OptString::some($data['thumb_url'])
                : OptString::none(),
            thumbWidth: \array_key_exists('thumb_width', $data)
                ? OptInt::some($data['thumb_width'])
                : OptInt::none(),
            thumbHeight: \array_key_exists('thumb_height', $data)
                ? OptInt::some($data['thumb_height'])
                : OptInt::none(),
        );
    }
}
