<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * OptMenuButton is optional MenuButtonCommands|MenuButtonWebApp|MenuButtonDefault.
 */
final readonly class OptMenuButton
{
    public function __construct(
        public null|MenuButtonCommands|MenuButtonWebApp|MenuButtonDefault $value,
        public bool $set,
    ) {}

    /**
     * Create an unset optional.
     */
    public static function none(): self
    {
        return new self(null, false);
    }

    /**
     * Create a set optional with the given value.
     */
    public static function some(MenuButtonCommands|MenuButtonWebApp|MenuButtonDefault $value): self
    {
        return new self($value, true);
    }
}
