<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Input for unpinChatMessage.
 *
 * Ref: #/components/schemas/unpinChatMessage
 */
final readonly class UnpinChatMessage implements JsonSerializable
{
    public function __construct(
        public string|int $chatId,
        public OptInt $messageId,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['chat_id'] = $this->chatId;
        if ($this->messageId->set) {
            $result['message_id'] = $this->messageId->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            chatId: $data['chat_id'],
            messageId: \array_key_exists('message_id', $data)
                ? OptInt::some($data['message_id'])
                : OptInt::none(),
        );
    }
}
