<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * This object represents a Telegram user or bot.
 *
 * Ref: #/components/schemas/User
 */
final readonly class User implements JsonSerializable
{
    public function __construct(
        public int $id,
        public bool $isBot,
        public string $firstName,
        public OptString $lastName,
        public OptString $username,
        public OptString $languageCode,
        public OptBool $canJoinGroups,
        public OptBool $canReadAllGroupMessages,
        public OptBool $supportsInlineQueries,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['id'] = $this->id;
        $result['is_bot'] = $this->isBot;
        $result['first_name'] = $this->firstName;
        if ($this->lastName->set) {
            $result['last_name'] = $this->lastName->value;
        }
        if ($this->username->set) {
            $result['username'] = $this->username->value;
        }
        if ($this->languageCode->set) {
            $result['language_code'] = $this->languageCode->value;
        }
        if ($this->canJoinGroups->set) {
            $result['can_join_groups'] = $this->canJoinGroups->value;
        }
        if ($this->canReadAllGroupMessages->set) {
            $result['can_read_all_group_messages'] = $this->canReadAllGroupMessages->value;
        }
        if ($this->supportsInlineQueries->set) {
            $result['supports_inline_queries'] = $this->supportsInlineQueries->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            id: $data['id'],
            isBot: $data['is_bot'],
            firstName: $data['first_name'],
            lastName: \array_key_exists('last_name', $data)
                ? OptString::some($data['last_name'])
                : OptString::none(),
            username: \array_key_exists('username', $data)
                ? OptString::some($data['username'])
                : OptString::none(),
            languageCode: \array_key_exists('language_code', $data)
                ? OptString::some($data['language_code'])
                : OptString::none(),
            canJoinGroups: \array_key_exists('can_join_groups', $data)
                ? OptBool::some($data['can_join_groups'])
                : OptBool::none(),
            canReadAllGroupMessages: \array_key_exists('can_read_all_group_messages', $data)
                ? OptBool::some($data['can_read_all_group_messages'])
                : OptBool::none(),
            supportsInlineQueries: \array_key_exists('supports_inline_queries', $data)
                ? OptBool::some($data['supports_inline_queries'])
                : OptBool::none(),
        );
    }
}
