<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Requests\OpenApi;

use App\Http\Dto\OpenApi as Dto;
use Illuminate\Foundation\Http\FormRequest;

/**
 * Auto-generated form request from OpenAPI specification.
 */
abstract class GitUpdateRefRequest extends FormRequest
{
    /**
     * Prepare the data for validation.
     */
    protected function prepareForValidation(): void
    {
        if ($this->missing('force')) {
            $this->getInputSource()->set('force', false);
        }
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'sha' => ['required', 'string'],
            'force' => ['sometimes', 'boolean'],
        ];
    }

    /**
     * Get the validated data from the request.
     *
     * @param array|int|string|null $key
     * @param mixed $default
     * @return Dto\GitUpdateRefReq|mixed
     */
    public function validated($key = null, $default = null): mixed
    {
        $validated = parent::validated($key, $default);
        if ($key === null) {
            return Dto\GitUpdateRefReq::fromArray($validated);
        }

        return $validated;
    }
}
