<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Requests\OpenApi;

use App\Http\Dto\OpenApi as Dto;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Auto-generated form request from OpenAPI specification.
 */
abstract class MigrationsStartForAuthenticatedUserRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'lock_repositories' => ['sometimes', 'boolean'],
            'exclude_attachments' => ['sometimes', 'boolean'],
            'exclude_releases' => ['sometimes', 'boolean'],
            'exclude_owner_projects' => ['sometimes', 'boolean'],
            'exclude' => ['sometimes', 'array'],
            'repositories' => ['required', 'array'],
        ];
    }

    /**
     * Get the validated data from the request.
     *
     * @param array|int|string|null $key
     * @param mixed $default
     * @return Dto\MigrationsStartForAuthenticatedUserReq|mixed
     */
    public function validated($key = null, $default = null): mixed
    {
        $validated = parent::validated($key, $default);
        if ($key === null) {
            return Dto\MigrationsStartForAuthenticatedUserReq::fromArray($validated);
        }

        return $validated;
    }
}
