<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Requests\OpenApi;

use App\Http\Dto\OpenApi as Dto;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Auto-generated form request from OpenAPI specification.
 */
abstract class ReposListDeploymentsRequest extends FormRequest
{
    /**
     * Prepare the data for validation.
     */
    protected function prepareForValidation(): void
    {
        if ($this->missing('sha')) {
            $this->getInputSource()->set('sha', 'none');
        }
        if ($this->missing('ref')) {
            $this->getInputSource()->set('ref', 'none');
        }
        if ($this->missing('task')) {
            $this->getInputSource()->set('task', 'none');
        }
        if ($this->missing('environment')) {
            $this->getInputSource()->set('environment', 'none');
        }
        if ($this->missing('per_page')) {
            $this->getInputSource()->set('per_page', 30);
        }
        if ($this->missing('page')) {
            $this->getInputSource()->set('page', 1);
        }
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'sha' => ['sometimes', 'string'],
            'ref' => ['sometimes', 'string'],
            'task' => ['sometimes', 'string'],
            'environment' => ['sometimes', 'string'],
            'per_page' => ['sometimes', 'integer'],
            'page' => ['sometimes', 'integer'],
        ];
    }

    /**
     * Get the validated data from the request.
     *
     * @param array|int|string|null $key
     * @param mixed $default
     * @return Dto\ReposListDeploymentsParams|mixed
     */
    public function validated($key = null, $default = null): mixed
    {
        $validated = parent::validated($key, $default);
        if ($key === null) {
            return Dto\ReposListDeploymentsParams::fromArray($validated);
        }

        return $validated;
    }
}
