<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringUint64NullableArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringUint64NullableArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringUint64NullableArrayController extends Controller
{
    /**
     * POST /test_request_string_uint64_nullable_array
     */
    abstract public function testRequestStringUint64NullableArray(
        TestRequestStringUint64NullableArrayRequest $request,
    ): TestRequestStringUint64NullableArrayResponse;
}
