<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseStringUriNullableArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseStringUriNullableArrayController extends Controller
{
    /**
     * POST /test_response_string_uri_nullable_array
     */
    abstract public function testResponseStringUriNullableArray(
        Request $request,
    ): TestResponseStringUriNullableArrayResponse;
}
