<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseStringUnixArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseStringUnixArrayController extends Controller
{
    /**
     * POST /test_response_string_unix_array
     */
    abstract public function testResponseStringUnixArray(
        Request $request,
    ): TestResponseStringUnixArrayResponse;
}
