<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredStringIpv6NullableArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredStringIpv6NullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringIpv6NullableArrayArrayController extends Controller
{
    /**
     * POST /test_request_required_string_ipv6_nullable_array_array
     */
    abstract public function testRequestRequiredStringIpv6NullableArrayArray(
        TestRequestRequiredStringIpv6NullableArrayArrayRequest $request,
    ): TestRequestRequiredStringIpv6NullableArrayArrayResponse;
}
