<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestRequestIntegerUint8NullableResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestIntegerUint8NullableController extends Controller
{
    /**
     * POST /test_request_integer_uint8_nullable
     */
    abstract public function testRequestIntegerUint8Nullable(
        Request $request,
    ): TestRequestIntegerUint8NullableResponse;
}
