<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringUnixSecondsNullableArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringUnixSecondsNullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringUnixSecondsNullableArrayArrayController extends Controller
{
    /**
     * POST /test_request_string_unix-seconds_nullable_array_array
     */
    abstract public function testRequestStringUnixSecondsNullableArrayArray(
        TestRequestStringUnixSecondsNullableArrayArrayRequest $request,
    ): TestRequestStringUnixSecondsNullableArrayArrayResponse;
}
