<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredStringIpNullableArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredStringIpNullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringIpNullableArrayArrayController extends Controller
{
    /**
     * POST /test_request_required_string_ip_nullable_array_array
     */
    abstract public function testRequestRequiredStringIpNullableArrayArray(
        TestRequestRequiredStringIpNullableArrayArrayRequest $request,
    ): TestRequestRequiredStringIpNullableArrayArrayResponse;
}
