<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseIntegerUnixMicroArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseIntegerUnixMicroArrayArrayController extends Controller
{
    /**
     * POST /test_response_integer_unix-micro_array_array
     */
    abstract public function testResponseIntegerUnixMicroArrayArray(
        Request $request,
    ): TestResponseIntegerUnixMicroArrayArrayResponse;
}
