<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredNullNullableArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredNullNullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredNullNullableArrayArrayController extends Controller
{
    /**
     * POST /test_request_required_null_nullable_array_array
     */
    abstract public function testRequestRequiredNullNullableArrayArray(
        TestRequestRequiredNullNullableArrayArrayRequest $request,
    ): TestRequestRequiredNullNullableArrayArrayResponse;
}
