<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseStringIntArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseStringIntArrayController extends Controller
{
    /**
     * POST /test_response_string_int_array
     */
    abstract public function testResponseStringIntArray(
        Request $request,
    ): TestResponseStringIntArrayResponse;
}
