<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredIntegerInt16ArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredIntegerInt16ArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredIntegerInt16ArrayController extends Controller
{
    /**
     * POST /test_request_required_integer_int16_array
     */
    abstract public function testRequestRequiredIntegerInt16Array(
        TestRequestRequiredIntegerInt16ArrayRequest $request,
    ): TestRequestRequiredIntegerInt16ArrayResponse;
}
