<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredStringIntNullableArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredStringIntNullableArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringIntNullableArrayController extends Controller
{
    /**
     * POST /test_request_required_string_int_nullable_array
     */
    abstract public function testRequestRequiredStringIntNullableArray(
        TestRequestRequiredStringIntNullableArrayRequest $request,
    ): TestRequestRequiredStringIntNullableArrayResponse;
}
