<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseStringFloat32ArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseStringFloat32ArrayController extends Controller
{
    /**
     * POST /test_response_string_float32_array
     */
    abstract public function testResponseStringFloat32Array(
        Request $request,
    ): TestResponseStringFloat32ArrayResponse;
}
