<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestIntegerUintNullableArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestIntegerUintNullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestIntegerUintNullableArrayArrayController extends Controller
{
    /**
     * POST /test_request_integer_uint_nullable_array_array
     */
    abstract public function testRequestIntegerUintNullableArrayArray(
        TestRequestIntegerUintNullableArrayArrayRequest $request,
    ): TestRequestIntegerUintNullableArrayArrayResponse;
}
