<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestRequestStringUint16Response;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringUint16Controller extends Controller
{
    /**
     * POST /test_request_string_uint16
     */
    abstract public function testRequestStringUint16(
        Request $request,
    ): TestRequestStringUint16Response;
}
