<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringUnixMilliArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringUnixMilliArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringUnixMilliArrayArrayController extends Controller
{
    /**
     * POST /test_request_string_unix-milli_array_array
     */
    abstract public function testRequestStringUnixMilliArrayArray(
        TestRequestStringUnixMilliArrayArrayRequest $request,
    ): TestRequestStringUnixMilliArrayArrayResponse;
}
