<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringUint16ArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringUint16ArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringUint16ArrayArrayController extends Controller
{
    /**
     * POST /test_request_string_uint16_array_array
     */
    abstract public function testRequestStringUint16ArrayArray(
        TestRequestStringUint16ArrayArrayRequest $request,
    ): TestRequestStringUint16ArrayArrayResponse;
}
