<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredStringDateTimeArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredStringDateTimeArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringDateTimeArrayController extends Controller
{
    /**
     * POST /test_request_required_string_date-time_array
     */
    abstract public function testRequestRequiredStringDateTimeArray(
        TestRequestRequiredStringDateTimeArrayRequest $request,
    ): TestRequestRequiredStringDateTimeArrayResponse;
}
