<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringFloat64ArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringFloat64ArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringFloat64ArrayController extends Controller
{
    /**
     * POST /test_request_string_float64_array
     */
    abstract public function testRequestStringFloat64Array(
        TestRequestStringFloat64ArrayRequest $request,
    ): TestRequestStringFloat64ArrayResponse;
}
