<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredStringUnixMicroNullableArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredStringUnixMicroNullableArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringUnixMicroNullableArrayController extends Controller
{
    /**
     * POST /test_request_required_string_unix-micro_nullable_array
     */
    abstract public function testRequestRequiredStringUnixMicroNullableArray(
        TestRequestRequiredStringUnixMicroNullableArrayRequest $request,
    ): TestRequestRequiredStringUnixMicroNullableArrayResponse;
}
