<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringHostnameArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringHostnameArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringHostnameArrayArrayController extends Controller
{
    /**
     * POST /test_request_string_hostname_array_array
     */
    abstract public function testRequestStringHostnameArrayArray(
        TestRequestStringHostnameArrayArrayRequest $request,
    ): TestRequestStringHostnameArrayArrayResponse;
}
