<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseNumberNullableResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseNumberNullableController extends Controller
{
    /**
     * POST /test_response_number_nullable
     */
    abstract public function testResponseNumberNullable(
        Request $request,
    ): TestResponseNumberNullableResponse;
}
