<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestIntegerInt32NullableArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestIntegerInt32NullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestIntegerInt32NullableArrayArrayController extends Controller
{
    /**
     * POST /test_request_integer_int32_nullable_array_array
     */
    abstract public function testRequestIntegerInt32NullableArrayArray(
        TestRequestIntegerInt32NullableArrayArrayRequest $request,
    ): TestRequestIntegerInt32NullableArrayArrayResponse;
}
