<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseIntegerInt64ArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseIntegerInt64ArrayArrayController extends Controller
{
    /**
     * POST /test_response_integer_int64_array_array
     */
    abstract public function testResponseIntegerInt64ArrayArray(
        Request $request,
    ): TestResponseIntegerInt64ArrayArrayResponse;
}
