<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseStringInt32NullableResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseStringInt32NullableController extends Controller
{
    /**
     * POST /test_response_string_int32_nullable
     */
    abstract public function testResponseStringInt32Nullable(
        Request $request,
    ): TestResponseStringInt32NullableResponse;
}
