<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredNumberInt32NullableArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredNumberInt32NullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredNumberInt32NullableArrayArrayController extends Controller
{
    /**
     * POST /test_request_required_number_int32_nullable_array_array
     */
    abstract public function testRequestRequiredNumberInt32NullableArrayArray(
        TestRequestRequiredNumberInt32NullableArrayArrayRequest $request,
    ): TestRequestRequiredNumberInt32NullableArrayArrayResponse;
}
