<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredIntegerInt8NullableArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredIntegerInt8NullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredIntegerInt8NullableArrayArrayController extends Controller
{
    /**
     * POST /test_request_required_integer_int8_nullable_array_array
     */
    abstract public function testRequestRequiredIntegerInt8NullableArrayArray(
        TestRequestRequiredIntegerInt8NullableArrayArrayRequest $request,
    ): TestRequestRequiredIntegerInt8NullableArrayArrayResponse;
}
