<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestNullNullableArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestNullNullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestNullNullableArrayArrayController extends Controller
{
    /**
     * POST /test_request_null_nullable_array_array
     */
    abstract public function testRequestNullNullableArrayArray(
        TestRequestNullNullableArrayArrayRequest $request,
    ): TestRequestNullNullableArrayArrayResponse;
}
