<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredIntegerInt16ArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredIntegerInt16ArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredIntegerInt16ArrayArrayController extends Controller
{
    /**
     * POST /test_request_required_integer_int16_array_array
     */
    abstract public function testRequestRequiredIntegerInt16ArrayArray(
        TestRequestRequiredIntegerInt16ArrayArrayRequest $request,
    ): TestRequestRequiredIntegerInt16ArrayArrayResponse;
}
