<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestRequestStringUint32NullableResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringUint32NullableController extends Controller
{
    /**
     * POST /test_request_string_uint32_nullable
     */
    abstract public function testRequestStringUint32Nullable(
        Request $request,
    ): TestRequestStringUint32NullableResponse;
}
