<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestRequestStringUint32Response;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringUint32Controller extends Controller
{
    /**
     * POST /test_request_string_uint32
     */
    abstract public function testRequestStringUint32(
        Request $request,
    ): TestRequestStringUint32Response;
}
