<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseIntegerUint32NullableResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseIntegerUint32NullableController extends Controller
{
    /**
     * POST /test_response_integer_uint32_nullable
     */
    abstract public function testResponseIntegerUint32Nullable(
        Request $request,
    ): TestResponseIntegerUint32NullableResponse;
}
