<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestRequestRequiredStringUint32Response;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringUint32Controller extends Controller
{
    /**
     * POST /test_request_required_string_uint32
     */
    abstract public function testRequestRequiredStringUint32(
        Request $request,
    ): TestRequestRequiredStringUint32Response;
}
