<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringUintNullableArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringUintNullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringUintNullableArrayArrayController extends Controller
{
    /**
     * POST /test_request_string_uint_nullable_array_array
     */
    abstract public function testRequestStringUintNullableArrayArray(
        TestRequestStringUintNullableArrayArrayRequest $request,
    ): TestRequestStringUintNullableArrayArrayResponse;
}
