<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseStringUint16NullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseStringUint16NullableArrayArrayController extends Controller
{
    /**
     * POST /test_response_string_uint16_nullable_array_array
     */
    abstract public function testResponseStringUint16NullableArrayArray(
        Request $request,
    ): TestResponseStringUint16NullableArrayArrayResponse;
}
