<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringFloat32ArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringFloat32ArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringFloat32ArrayController extends Controller
{
    /**
     * POST /test_request_string_float32_array
     */
    abstract public function testRequestStringFloat32Array(
        TestRequestStringFloat32ArrayRequest $request,
    ): TestRequestStringFloat32ArrayResponse;
}
