<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseIntegerUnixSecondsResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseIntegerUnixSecondController extends Controller
{
    /**
     * POST /test_response_integer_unix-seconds
     */
    abstract public function testResponseIntegerUnixSeconds(
        Request $request,
    ): TestResponseIntegerUnixSecondsResponse;
}
