<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringUint64ArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringUint64ArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringUint64ArrayArrayController extends Controller
{
    /**
     * POST /test_request_string_uint64_array_array
     */
    abstract public function testRequestStringUint64ArrayArray(
        TestRequestStringUint64ArrayArrayRequest $request,
    ): TestRequestStringUint64ArrayArrayResponse;
}
