<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringDecimalNullableArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringDecimalNullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringDecimalNullableArrayArrayController extends Controller
{
    /**
     * POST /test_request_string_decimal_nullable_array_array
     */
    abstract public function testRequestStringDecimalNullableArrayArray(
        TestRequestStringDecimalNullableArrayArrayRequest $request,
    ): TestRequestStringDecimalNullableArrayArrayResponse;
}
