<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestIntegerUnixSecondsNullableArrayRequest;
use App\Http\Responses\OpenApi\TestRequestIntegerUnixSecondsNullableArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestIntegerUnixSecondsNullableArrayController extends Controller
{
    /**
     * POST /test_request_integer_unix-seconds_nullable_array
     */
    abstract public function testRequestIntegerUnixSecondsNullableArray(
        TestRequestIntegerUnixSecondsNullableArrayRequest $request,
    ): TestRequestIntegerUnixSecondsNullableArrayResponse;
}
