<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringDecimalArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringDecimalArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringDecimalArrayArrayController extends Controller
{
    /**
     * POST /test_request_string_decimal_array_array
     */
    abstract public function testRequestStringDecimalArrayArray(
        TestRequestStringDecimalArrayArrayRequest $request,
    ): TestRequestStringDecimalArrayArrayResponse;
}
