<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestRequestRequiredStringInt64Response;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringInt64Controller extends Controller
{
    /**
     * POST /test_request_required_string_int64
     */
    abstract public function testRequestRequiredStringInt64(
        Request $request,
    ): TestRequestRequiredStringInt64Response;
}
