<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestIntegerUnixSecondsNullableArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestIntegerUnixSecondsNullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestIntegerUnixSecondsNullableArrayArrayController extends Controller
{
    /**
     * POST /test_request_integer_unix-seconds_nullable_array_array
     */
    abstract public function testRequestIntegerUnixSecondsNullableArrayArray(
        TestRequestIntegerUnixSecondsNullableArrayArrayRequest $request,
    ): TestRequestIntegerUnixSecondsNullableArrayArrayResponse;
}
