<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredStringPasswordArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredStringPasswordArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringPasswordArrayController extends Controller
{
    /**
     * POST /test_request_required_string_password_array
     */
    abstract public function testRequestRequiredStringPasswordArray(
        TestRequestRequiredStringPasswordArrayRequest $request,
    ): TestRequestRequiredStringPasswordArrayResponse;
}
