<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseIntegerInt64NullableArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseIntegerInt64NullableArrayController extends Controller
{
    /**
     * POST /test_response_integer_int64_nullable_array
     */
    abstract public function testResponseIntegerInt64NullableArray(
        Request $request,
    ): TestResponseIntegerInt64NullableArrayResponse;
}
