<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestIntegerUint64ArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestIntegerUint64ArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestIntegerUint64ArrayArrayController extends Controller
{
    /**
     * POST /test_request_integer_uint64_array_array
     */
    abstract public function testRequestIntegerUint64ArrayArray(
        TestRequestIntegerUint64ArrayArrayRequest $request,
    ): TestRequestIntegerUint64ArrayArrayResponse;
}
