<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredStringUintArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredStringUintArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringUintArrayArrayController extends Controller
{
    /**
     * POST /test_request_required_string_uint_array_array
     */
    abstract public function testRequestRequiredStringUintArrayArray(
        TestRequestRequiredStringUintArrayArrayRequest $request,
    ): TestRequestRequiredStringUintArrayArrayResponse;
}
