<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseIntegerUnixSecondsNullableResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseIntegerUnixSecondsNullableController extends Controller
{
    /**
     * POST /test_response_integer_unix-seconds_nullable
     */
    abstract public function testResponseIntegerUnixSecondsNullable(
        Request $request,
    ): TestResponseIntegerUnixSecondsNullableResponse;
}
