<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestRequestIntegerUint16NullableResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestIntegerUint16NullableController extends Controller
{
    /**
     * POST /test_request_integer_uint16_nullable
     */
    abstract public function testRequestIntegerUint16Nullable(
        Request $request,
    ): TestRequestIntegerUint16NullableResponse;
}
