<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestRequestRequiredBooleanNullableResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredBooleanNullableController extends Controller
{
    /**
     * POST /test_request_required_boolean_nullable
     */
    abstract public function testRequestRequiredBooleanNullable(
        Request $request,
    ): TestRequestRequiredBooleanNullableResponse;
}
