<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseStringIpv4NullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseStringIpv4NullableArrayArrayController extends Controller
{
    /**
     * POST /test_response_string_ipv4_nullable_array_array
     */
    abstract public function testResponseStringIpv4NullableArrayArray(
        Request $request,
    ): TestResponseStringIpv4NullableArrayArrayResponse;
}
