<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringInt16ArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringInt16ArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringInt16ArrayController extends Controller
{
    /**
     * POST /test_request_string_int16_array
     */
    abstract public function testRequestStringInt16Array(
        TestRequestStringInt16ArrayRequest $request,
    ): TestRequestStringInt16ArrayResponse;
}
