<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestRequestRequiredStringDateResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringDateController extends Controller
{
    /**
     * POST /test_request_required_string_date
     */
    abstract public function testRequestRequiredStringDate(
        Request $request,
    ): TestRequestRequiredStringDateResponse;
}
