<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestRequestRequiredStringBinaryResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringBinaryController extends Controller
{
    /**
     * POST /test_request_required_string_binary
     */
    abstract public function testRequestRequiredStringBinary(
        Request $request,
    ): TestRequestRequiredStringBinaryResponse;
}
