<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringPasswordArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringPasswordArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringPasswordArrayArrayController extends Controller
{
    /**
     * POST /test_request_string_password_array_array
     */
    abstract public function testRequestStringPasswordArrayArray(
        TestRequestStringPasswordArrayArrayRequest $request,
    ): TestRequestStringPasswordArrayArrayResponse;
}
