<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredStringEmailNullableArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredStringEmailNullableArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringEmailNullableArrayController extends Controller
{
    /**
     * POST /test_request_required_string_email_nullable_array
     */
    abstract public function testRequestRequiredStringEmailNullableArray(
        TestRequestRequiredStringEmailNullableArrayRequest $request,
    ): TestRequestRequiredStringEmailNullableArrayResponse;
}
