<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestRequestNumberResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestNumberController extends Controller
{
    /**
     * POST /test_request_number
     */
    abstract public function testRequestNumber(
        Request $request,
    ): TestRequestNumberResponse;
}
