<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredStringUint8ArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredStringUint8ArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringUint8ArrayArrayController extends Controller
{
    /**
     * POST /test_request_required_string_uint8_array_array
     */
    abstract public function testRequestRequiredStringUint8ArrayArray(
        TestRequestRequiredStringUint8ArrayArrayRequest $request,
    ): TestRequestRequiredStringUint8ArrayArrayResponse;
}
