<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseStringBase64ArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseStringBase64ArrayController extends Controller
{
    /**
     * POST /test_response_string_base64_array
     */
    abstract public function testResponseStringBase64Array(
        Request $request,
    ): TestResponseStringBase64ArrayResponse;
}
