<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestRequestStringUnixMilliResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringUnixMilliController extends Controller
{
    /**
     * POST /test_request_string_unix-milli
     */
    abstract public function testRequestStringUnixMilli(
        Request $request,
    ): TestRequestStringUnixMilliResponse;
}
