<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredStringUnixNanoArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredStringUnixNanoArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringUnixNanoArrayArrayController extends Controller
{
    /**
     * POST /test_request_required_string_unix-nano_array_array
     */
    abstract public function testRequestRequiredStringUnixNanoArrayArray(
        TestRequestRequiredStringUnixNanoArrayArrayRequest $request,
    ): TestRequestRequiredStringUnixNanoArrayArrayResponse;
}
