<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestIntegerInt16ArrayRequest;
use App\Http\Responses\OpenApi\TestRequestIntegerInt16ArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestIntegerInt16ArrayController extends Controller
{
    /**
     * POST /test_request_integer_int16_array
     */
    abstract public function testRequestIntegerInt16Array(
        TestRequestIntegerInt16ArrayRequest $request,
    ): TestRequestIntegerInt16ArrayResponse;
}
