<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredNumberInt32ArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredNumberInt32ArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredNumberInt32ArrayArrayController extends Controller
{
    /**
     * POST /test_request_required_number_int32_array_array
     */
    abstract public function testRequestRequiredNumberInt32ArrayArray(
        TestRequestRequiredNumberInt32ArrayArrayRequest $request,
    ): TestRequestRequiredNumberInt32ArrayArrayResponse;
}
