<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredNumberDecimalArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredNumberDecimalArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredNumberDecimalArrayArrayController extends Controller
{
    /**
     * POST /test_request_required_number_decimal_array_array
     */
    abstract public function testRequestRequiredNumberDecimalArrayArray(
        TestRequestRequiredNumberDecimalArrayArrayRequest $request,
    ): TestRequestRequiredNumberDecimalArrayArrayResponse;
}
