<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestIntegerUint16ArrayRequest;
use App\Http\Responses\OpenApi\TestRequestIntegerUint16ArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestIntegerUint16ArrayController extends Controller
{
    /**
     * POST /test_request_integer_uint16_array
     */
    abstract public function testRequestIntegerUint16Array(
        TestRequestIntegerUint16ArrayRequest $request,
    ): TestRequestIntegerUint16ArrayResponse;
}
