<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringInt32ArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringInt32ArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringInt32ArrayController extends Controller
{
    /**
     * POST /test_request_string_int32_array
     */
    abstract public function testRequestStringInt32Array(
        TestRequestStringInt32ArrayRequest $request,
    ): TestRequestStringInt32ArrayResponse;
}
