<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseIntegerUintResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseIntegerUintController extends Controller
{
    /**
     * POST /test_response_integer_uint
     */
    abstract public function testResponseIntegerUint(
        Request $request,
    ): TestResponseIntegerUintResponse;
}
