<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredStringEmailNullableArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredStringEmailNullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringEmailNullableArrayArrayController extends Controller
{
    /**
     * POST /test_request_required_string_email_nullable_array_array
     */
    abstract public function testRequestRequiredStringEmailNullableArrayArray(
        TestRequestRequiredStringEmailNullableArrayArrayRequest $request,
    ): TestRequestRequiredStringEmailNullableArrayArrayResponse;
}
