<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredStringBase64NullableArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredStringBase64NullableArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringBase64NullableArrayController extends Controller
{
    /**
     * POST /test_request_required_string_base64_nullable_array
     */
    abstract public function testRequestRequiredStringBase64NullableArray(
        TestRequestRequiredStringBase64NullableArrayRequest $request,
    ): TestRequestRequiredStringBase64NullableArrayResponse;
}
