<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseNumberInt32ArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseNumberInt32ArrayController extends Controller
{
    /**
     * POST /test_response_number_int32_array
     */
    abstract public function testResponseNumberInt32Array(
        Request $request,
    ): TestResponseNumberInt32ArrayResponse;
}
