<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredStringInt16NullableArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredStringInt16NullableArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringInt16NullableArrayController extends Controller
{
    /**
     * POST /test_request_required_string_int16_nullable_array
     */
    abstract public function testRequestRequiredStringInt16NullableArray(
        TestRequestRequiredStringInt16NullableArrayRequest $request,
    ): TestRequestRequiredStringInt16NullableArrayResponse;
}
