<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestIntegerUnixMilliArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestIntegerUnixMilliArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestIntegerUnixMilliArrayArrayController extends Controller
{
    /**
     * POST /test_request_integer_unix-milli_array_array
     */
    abstract public function testRequestIntegerUnixMilliArrayArray(
        TestRequestIntegerUnixMilliArrayArrayRequest $request,
    ): TestRequestIntegerUnixMilliArrayArrayResponse;
}
