<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringBinaryNullableArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringBinaryNullableArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringBinaryNullableArrayArrayController extends Controller
{
    /**
     * POST /test_request_string_binary_nullable_array_array
     */
    abstract public function testRequestStringBinaryNullableArrayArray(
        TestRequestStringBinaryNullableArrayArrayRequest $request,
    ): TestRequestStringBinaryNullableArrayArrayResponse;
}
