<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestStringPasswordArrayRequest;
use App\Http\Responses\OpenApi\TestRequestStringPasswordArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestStringPasswordArrayController extends Controller
{
    /**
     * POST /test_request_string_password_array
     */
    abstract public function testRequestStringPasswordArray(
        TestRequestStringPasswordArrayRequest $request,
    ): TestRequestStringPasswordArrayResponse;
}
