<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseStringIpv6ArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseStringIpv6ArrayArrayController extends Controller
{
    /**
     * POST /test_response_string_ipv6_array_array
     */
    abstract public function testResponseStringIpv6ArrayArray(
        Request $request,
    ): TestResponseStringIpv6ArrayArrayResponse;
}
