<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestIntegerUnixMicroArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestIntegerUnixMicroArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestIntegerUnixMicroArrayArrayController extends Controller
{
    /**
     * POST /test_request_integer_unix-micro_array_array
     */
    abstract public function testRequestIntegerUnixMicroArrayArray(
        TestRequestIntegerUnixMicroArrayArrayRequest $request,
    ): TestRequestIntegerUnixMicroArrayArrayResponse;
}
