<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestResponseStringUnixMilliNullableResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestResponseStringUnixMilliNullableController extends Controller
{
    /**
     * POST /test_response_string_unix-milli_nullable
     */
    abstract public function testResponseStringUnixMilliNullable(
        Request $request,
    ): TestResponseStringUnixMilliNullableResponse;
}
