<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\TestRequestRequiredStringUnixMilliArrayArrayRequest;
use App\Http\Responses\OpenApi\TestRequestRequiredStringUnixMilliArrayArrayResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredStringUnixMilliArrayArrayController extends Controller
{
    /**
     * POST /test_request_required_string_unix-milli_array_array
     */
    abstract public function testRequestRequiredStringUnixMilliArrayArray(
        TestRequestRequiredStringUnixMilliArrayArrayRequest $request,
    ): TestRequestRequiredStringUnixMilliArrayArrayResponse;
}
