<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Responses\OpenApi\TestRequestRequiredIntegerUnixResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class TestRequestRequiredIntegerUnixController extends Controller
{
    /**
     * POST /test_request_required_integer_unix
     */
    abstract public function testRequestRequiredIntegerUnix(
        Request $request,
    ): TestRequestRequiredIntegerUnixResponse;
}
