<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Requests\OpenApi;

use App\Http\Dto\OpenApi as Dto;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Auto-generated form request from OpenAPI specification.
 */
abstract class EditMessageCaptionRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'chat_id' => ['sometimes'],
            'message_id' => ['sometimes', 'integer'],
            'inline_message_id' => ['sometimes', 'string'],
            'caption' => ['sometimes', 'string', 'max:1024'],
            'parse_mode' => ['sometimes', 'string'],
            'caption_entities' => ['sometimes', 'array'],
            'reply_markup' => ['sometimes', 'array'],
        ];
    }

    /**
     * Get the validated data from the request.
     *
     * @param array|int|string|null $key
     * @param mixed $default
     * @return Dto\EditMessageCaption|mixed
     */
    public function validated($key = null, $default = null): mixed
    {
        $validated = parent::validated($key, $default);
        if ($key === null) {
            return Dto\EditMessageCaption::fromArray($validated);
        }

        return $validated;
    }
}
