<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Requests\OpenApi;

use App\Http\Dto\OpenApi as Dto;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Auto-generated form request from OpenAPI specification.
 */
abstract class SendContactRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'chat_id' => ['required'],
            'phone_number' => ['required', 'string'],
            'first_name' => ['required', 'string'],
            'last_name' => ['sometimes', 'string'],
            'vcard' => ['sometimes', 'string', 'max:2048'],
            'disable_notification' => ['sometimes', 'boolean'],
            'reply_to_message_id' => ['sometimes', 'integer'],
            'allow_sending_without_reply' => ['sometimes', 'boolean'],
            'reply_markup' => ['sometimes'],
        ];
    }

    /**
     * Get the validated data from the request.
     *
     * @param array|int|string|null $key
     * @param mixed $default
     * @return Dto\SendContact|mixed
     */
    public function validated($key = null, $default = null): mixed
    {
        $validated = parent::validated($key, $default);
        if ($key === null) {
            return Dto\SendContact::fromArray($validated);
        }

        return $validated;
    }
}
