<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Requests\OpenApi;

use App\Http\Dto\OpenApi as Dto;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Auto-generated form request from OpenAPI specification.
 */
abstract class UserPostingPostRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'captcha_type' => ['required', 'string', Rule::enum(\App\Http\Dto\OpenApi\CaptchaType::class)],
            'board' => ['required', 'string'],
            'thread' => ['sometimes', 'integer'],
            'name' => ['sometimes', 'string'],
            'email' => ['sometimes', 'string'],
            'tags' => ['sometimes', 'string'],
            'subject' => ['sometimes', 'string'],
            'comment' => ['sometimes', 'string'],
            'icon' => ['sometimes', 'integer'],
            'op_mark' => ['sometimes', 'integer'],
            'file[]' => ['sometimes', 'file'],
        ];
    }

    /**
     * Get the validated data from the request.
     *
     * @param array|int|string|null $key
     * @param mixed $default
     * @return Dto\UserPostingPostReq|mixed
     */
    public function validated($key = null, $default = null): mixed
    {
        $validated = parent::validated($key, $default);
        if ($key === null) {
            return Dto\UserPostingPostReq::fromArray($validated);
        }

        return $validated;
    }
}
