<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Requests\OpenApi;

use App\Http\Dto\OpenApi as Dto;
use Illuminate\Foundation\Http\FormRequest;

/**
 * Auto-generated form request from OpenAPI specification.
 */
abstract class SendVenueRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'chat_id' => ['required'],
            'latitude' => ['required', 'numeric'],
            'longitude' => ['required', 'numeric'],
            'title' => ['required', 'string'],
            'address' => ['required', 'string'],
            'foursquare_id' => ['sometimes', 'string'],
            'foursquare_type' => ['sometimes', 'string'],
            'google_place_id' => ['sometimes', 'string'],
            'google_place_type' => ['sometimes', 'string'],
            'disable_notification' => ['sometimes', 'boolean'],
            'protect_content' => ['sometimes', 'boolean'],
            'reply_to_message_id' => ['sometimes', 'integer'],
            'allow_sending_without_reply' => ['sometimes', 'boolean'],
            'reply_markup' => ['sometimes'],
        ];
    }

    /**
     * Get the validated data from the request.
     *
     * @param array|int|string|null $key
     * @param mixed $default
     * @return Dto\SendVenue|mixed
     */
    public function validated($key = null, $default = null): mixed
    {
        $validated = parent::validated($key, $default);
        if ($key === null) {
            return Dto\SendVenue::fromArray($validated);
        }

        return $validated;
    }
}
