<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Requests\OpenApi;

use App\Http\Dto\OpenApi as Dto;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Auto-generated form request from OpenAPI specification.
 */
abstract class SendPollRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'chat_id' => ['required'],
            'question' => ['required', 'string', 'min:1', 'max:300'],
            'options' => ['required', 'array'],
            'is_anonymous' => ['sometimes', 'boolean'],
            'type' => ['sometimes', 'string'],
            'allows_multiple_answers' => ['sometimes', 'boolean'],
            'correct_option_id' => ['sometimes', 'integer'],
            'explanation' => ['sometimes', 'string', 'max:200'],
            'explanation_parse_mode' => ['sometimes', 'string'],
            'explanation_entities' => ['sometimes', 'array'],
            'open_period' => ['sometimes', 'integer'],
            'close_date' => ['sometimes', 'integer'],
            'is_closed' => ['sometimes', 'boolean'],
            'disable_notification' => ['sometimes', 'boolean'],
            'protect_content' => ['sometimes', 'boolean'],
            'reply_to_message_id' => ['sometimes', 'integer'],
            'allow_sending_without_reply' => ['sometimes', 'boolean'],
            'reply_markup' => ['sometimes'],
        ];
    }

    /**
     * Get the validated data from the request.
     *
     * @param array|int|string|null $key
     * @param mixed $default
     * @return Dto\SendPoll|mixed
     */
    public function validated($key = null, $default = null): mixed
    {
        $validated = parent::validated($key, $default);
        if ($key === null) {
            return Dto\SendPoll::fromArray($validated);
        }

        return $validated;
    }
}
