<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Requests\OpenApi;

use App\Http\Dto\OpenApi as Dto;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Auto-generated form request from OpenAPI specification.
 */
abstract class SetGameScoreRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'user_id' => ['required', 'integer'],
            'score' => ['required', 'integer'],
            'force' => ['sometimes', 'boolean'],
            'disable_edit_message' => ['sometimes', 'boolean'],
            'chat_id' => ['sometimes', 'integer'],
            'message_id' => ['sometimes', 'integer'],
            'inline_message_id' => ['sometimes', 'string'],
        ];
    }

    /**
     * Get the validated data from the request.
     *
     * @param array|int|string|null $key
     * @param mixed $default
     * @return Dto\SetGameScore|mixed
     */
    public function validated($key = null, $default = null): mixed
    {
        $validated = parent::validated($key, $default);
        if ($key === null) {
            return Dto\SetGameScore::fromArray($validated);
        }

        return $validated;
    }
}
