<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Responses\OpenApi\EmojisGetResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class EmojiController extends Controller
{
    /**
     * GET /emojis
     *
     * Lists all the emojis available to use on GitHub.
     */
    abstract public function emojisGet(
    ): EmojisGetResponse;
}
