<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Responses\OpenApi\GitignoreGetAllTemplatesResponse;
use App\Http\Responses\OpenApi\GitignoreGetTemplateResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class GitignoreController extends Controller
{
    /**
     * GET /gitignore/templates
     *
     * List all templates available to pass as an option when [creating a repository](https://docs.github.
     * com/rest/reference/repos#create-a-repository-for-the-authenticated-user).
     */
    abstract public function gitignoreGetAllTemplates(
    ): GitignoreGetAllTemplatesResponse;

    /**
     * GET /gitignore/templates/{name}
     *
     * The API also allows fetching the source of a single template.
     * Use the raw [media type](https://docs.github.com/rest/overview/media-types/) to get the raw
     * contents.
     */
    abstract public function gitignoreGetTemplate(
        string $name,
    ): GitignoreGetTemplateResponse;
}
