<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\ActivityListPublicEventsForRepoNetworkRequest;
use App\Http\Responses\OpenApi\ActivityListPublicEventsForRepoNetworkResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class NetworkController extends Controller
{
    /**
     * GET /networks/{owner}/{repo}/events
     *
     * List public events for a network of repositories
     */
    abstract public function activityListPublicEventsForRepoNetwork(
        ActivityListPublicEventsForRepoNetworkRequest $request,
        string $owner,
        string $repo,
    ): ActivityListPublicEventsForRepoNetworkResponse;
}
