<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\OrgsListRequest;
use App\Http\Responses\OpenApi\OrgsListResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class OrganizationController extends Controller
{
    /**
     * GET /organizations
     *
     * Lists all organizations, in the order that they were created on GitHub.
     * **Note:** Pagination is powered exclusively by the `since` parameter. Use the [Link
     * header](https://docs.github.com/rest/overview/resources-in-the-rest-api#link-header) to get the
     * URL for the next page of organizations.
     */
    abstract public function orgsList(
        OrgsListRequest $request,
    ): OrgsListResponse;
}
