<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * EndpointSubset is a group of addresses with a common set of ports. The expanded set of endpoints
 * is the Cartesian product of Addresses x Ports. For example, given:
 * {
 * Addresses: [{"ip": "10.10.1.1"}, {"ip": "10.10.2.2"}],
 * Ports:     [{"name": "a", "port": 8675}, {"name": "b", "port": 309}]
 * }
 * The resulting set of endpoints can be viewed as:
 * a: [ 10.10.1.1:8675, 10.10.2.2:8675 ],
 * b: [ 10.10.1.1:309, 10.10.2.2:309 ].
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.EndpointSubset
 */
final readonly class IoK8sApiCoreV1EndpointSubset implements JsonSerializable
{
    public function __construct(
        /** @var IoK8sApiCoreV1EndpointAddress[] */
        public array $addresses,
        /** @var IoK8sApiCoreV1EndpointAddress[] */
        public array $notReadyAddresses,
        /** @var IoK8sApiCoreV1EndpointPort[] */
        public array $ports,
    ) {
        foreach ($this->addresses as $item) {
            if (!$item instanceof IoK8sApiCoreV1EndpointAddress) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApiCoreV1EndpointAddress');
            }
        }
        foreach ($this->notReadyAddresses as $item) {
            if (!$item instanceof IoK8sApiCoreV1EndpointAddress) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApiCoreV1EndpointAddress');
            }
        }
        foreach ($this->ports as $item) {
            if (!$item instanceof IoK8sApiCoreV1EndpointPort) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApiCoreV1EndpointPort');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['addresses'] = array_map(fn ($item) => $item->jsonSerialize(), $this->addresses);
        $result['notReadyAddresses'] = array_map(fn ($item) => $item->jsonSerialize(), $this->notReadyAddresses);
        $result['ports'] = array_map(fn ($item) => $item->jsonSerialize(), $this->ports);

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            addresses: array_map(IoK8sApiCoreV1EndpointAddress::fromArray(...), $data['addresses']),
            notReadyAddresses: array_map(IoK8sApiCoreV1EndpointAddress::fromArray(...), $data['notReadyAddresses']),
            ports: array_map(IoK8sApiCoreV1EndpointPort::fromArray(...), $data['ports']),
        );
    }
}
