<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * RuntimeClassSpec is a specification of a RuntimeClass. It contains parameters that are required to
 * describe the RuntimeClass to the Container Runtime Interface (CRI) implementation, as well as any
 * other components that need to understand how the pod will be run. The RuntimeClassSpec is
 * immutable.
 *
 * Ref: #/components/schemas/io.k8s.api.node.v1alpha1.RuntimeClassSpec
 */
final readonly class IoK8sApiNodeV1alpha1RuntimeClassSpec implements JsonSerializable
{
    public function __construct(
        public OptIoK8sApiNodeV1alpha1Overhead $overhead,
        public string $runtimeHandler,
        public OptIoK8sApiNodeV1alpha1Scheduling $scheduling,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->overhead->set) {
            $result['overhead'] = $this->overhead->value?->jsonSerialize();
        }
        $result['runtimeHandler'] = $this->runtimeHandler;
        if ($this->scheduling->set) {
            $result['scheduling'] = $this->scheduling->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            overhead: \array_key_exists('overhead', $data)
                ? OptIoK8sApiNodeV1alpha1Overhead::some(IoK8sApiNodeV1alpha1Overhead::fromArray($data['overhead']))
                : OptIoK8sApiNodeV1alpha1Overhead::none(),
            runtimeHandler: $data['runtimeHandler'],
            scheduling: \array_key_exists('scheduling', $data)
                ? OptIoK8sApiNodeV1alpha1Scheduling::some(IoK8sApiNodeV1alpha1Scheduling::fromArray($data['scheduling']))
                : OptIoK8sApiNodeV1alpha1Scheduling::none(),
        );
    }
}
