<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * ServiceBackendPort is the service port being referenced.
 *
 * Ref: #/components/schemas/io.k8s.api.networking.v1.ServiceBackendPort
 */
final readonly class IoK8sApiNetworkingV1ServiceBackendPort implements JsonSerializable
{
    public function __construct(
        public OptString $name,
        public OptInt32 $number,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->name->set) {
            $result['name'] = $this->name->value;
        }
        if ($this->number->set) {
            $result['number'] = $this->number->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            name: \array_key_exists('name', $data)
                ? OptString::some($data['name'])
                : OptString::none(),
            number: \array_key_exists('number', $data)
                ? OptInt32::some($data['number'])
                : OptInt32::none(),
        );
    }
}
