<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * ServerAddressByClientCIDR helps the client to determine the server address that they should use,
 * depending on the clientCIDR that they match.
 *
 * Ref: #/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.ServerAddressByClientCIDR
 */
final readonly class IoK8sApimachineryPkgApisMetaV1ServerAddressByClientCIDR implements JsonSerializable
{
    public function __construct(
        public string $clientCIDR,
        public string $serverAddress,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['clientCIDR'] = $this->clientCIDR;
        $result['serverAddress'] = $this->serverAddress;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            clientCIDR: $data['clientCIDR'],
            serverAddress: $data['serverAddress'],
        );
    }
}
