<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * MetricSpec specifies how to scale based on a single metric (only `type` and one other matching
 * field should be set at once).
 *
 * Ref: #/components/schemas/io.k8s.api.autoscaling.v2beta1.MetricSpec
 */
final readonly class IoK8sApiAutoscalingV2beta1MetricSpec implements JsonSerializable
{
    public function __construct(
        public OptIoK8sApiAutoscalingV2beta1ContainerResourceMetricSource $containerResource,
        public OptIoK8sApiAutoscalingV2beta1ExternalMetricSource $external,
        public OptIoK8sApiAutoscalingV2beta1ObjectMetricSource $object,
        public OptIoK8sApiAutoscalingV2beta1PodsMetricSource $pods,
        public OptIoK8sApiAutoscalingV2beta1ResourceMetricSource $resource,
        public string $type,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->containerResource->set) {
            $result['containerResource'] = $this->containerResource->value?->jsonSerialize();
        }
        if ($this->external->set) {
            $result['external'] = $this->external->value?->jsonSerialize();
        }
        if ($this->object->set) {
            $result['object'] = $this->object->value?->jsonSerialize();
        }
        if ($this->pods->set) {
            $result['pods'] = $this->pods->value?->jsonSerialize();
        }
        if ($this->resource->set) {
            $result['resource'] = $this->resource->value?->jsonSerialize();
        }
        $result['type'] = $this->type;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            containerResource: \array_key_exists('containerResource', $data)
                ? OptIoK8sApiAutoscalingV2beta1ContainerResourceMetricSource::some(IoK8sApiAutoscalingV2beta1ContainerResourceMetricSource::fromArray($data['containerResource']))
                : OptIoK8sApiAutoscalingV2beta1ContainerResourceMetricSource::none(),
            external: \array_key_exists('external', $data)
                ? OptIoK8sApiAutoscalingV2beta1ExternalMetricSource::some(IoK8sApiAutoscalingV2beta1ExternalMetricSource::fromArray($data['external']))
                : OptIoK8sApiAutoscalingV2beta1ExternalMetricSource::none(),
            object: \array_key_exists('object', $data)
                ? OptIoK8sApiAutoscalingV2beta1ObjectMetricSource::some(IoK8sApiAutoscalingV2beta1ObjectMetricSource::fromArray($data['object']))
                : OptIoK8sApiAutoscalingV2beta1ObjectMetricSource::none(),
            pods: \array_key_exists('pods', $data)
                ? OptIoK8sApiAutoscalingV2beta1PodsMetricSource::some(IoK8sApiAutoscalingV2beta1PodsMetricSource::fromArray($data['pods']))
                : OptIoK8sApiAutoscalingV2beta1PodsMetricSource::none(),
            resource: \array_key_exists('resource', $data)
                ? OptIoK8sApiAutoscalingV2beta1ResourceMetricSource::some(IoK8sApiAutoscalingV2beta1ResourceMetricSource::fromArray($data['resource']))
                : OptIoK8sApiAutoscalingV2beta1ResourceMetricSource::none(),
            type: $data['type'],
        );
    }
}
