<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * ContainerStateTerminated is a terminated state of a container.
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.ContainerStateTerminated
 */
final readonly class IoK8sApiCoreV1ContainerStateTerminated implements JsonSerializable
{
    public function __construct(
        public OptString $containerID,
        public int $exitCode,
        public OptIoK8sApimachineryPkgApisMetaV1Time $finishedAt,
        public OptString $message,
        public OptString $reason,
        public OptInt32 $signal,
        public OptIoK8sApimachineryPkgApisMetaV1Time $startedAt,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->containerID->set) {
            $result['containerID'] = $this->containerID->value;
        }
        $result['exitCode'] = $this->exitCode;
        if ($this->finishedAt->set) {
            $result['finishedAt'] = $this->finishedAt->value;
        }
        if ($this->message->set) {
            $result['message'] = $this->message->value;
        }
        if ($this->reason->set) {
            $result['reason'] = $this->reason->value;
        }
        if ($this->signal->set) {
            $result['signal'] = $this->signal->value;
        }
        if ($this->startedAt->set) {
            $result['startedAt'] = $this->startedAt->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            containerID: \array_key_exists('containerID', $data)
                ? OptString::some($data['containerID'])
                : OptString::none(),
            exitCode: $data['exitCode'],
            finishedAt: \array_key_exists('finishedAt', $data)
                ? OptIoK8sApimachineryPkgApisMetaV1Time::some($data['finishedAt'])
                : OptIoK8sApimachineryPkgApisMetaV1Time::none(),
            message: \array_key_exists('message', $data)
                ? OptString::some($data['message'])
                : OptString::none(),
            reason: \array_key_exists('reason', $data)
                ? OptString::some($data['reason'])
                : OptString::none(),
            signal: \array_key_exists('signal', $data)
                ? OptInt32::some($data['signal'])
                : OptInt32::none(),
            startedAt: \array_key_exists('startedAt', $data)
                ? OptIoK8sApimachineryPkgApisMetaV1Time::some($data['startedAt'])
                : OptIoK8sApimachineryPkgApisMetaV1Time::none(),
        );
    }
}
