<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * VolumeNodeAffinity defines constraints that limit what nodes this volume can be accessed from.
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.VolumeNodeAffinity
 */
final readonly class IoK8sApiCoreV1VolumeNodeAffinity implements JsonSerializable
{
    public function __construct(
        public OptIoK8sApiCoreV1NodeSelector $required,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->required->set) {
            $result['required'] = $this->required->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            required: \array_key_exists('required', $data)
                ? OptIoK8sApiCoreV1NodeSelector::some(IoK8sApiCoreV1NodeSelector::fromArray($data['required']))
                : OptIoK8sApiCoreV1NodeSelector::none(),
        );
    }
}
