<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * PersistentVolumeSpec is the specification of a persistent volume.
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.PersistentVolumeSpec
 */
final readonly class IoK8sApiCoreV1PersistentVolumeSpec implements JsonSerializable
{
    public function __construct(
        /** @var string[] */
        public array $accessModes,
        public OptIoK8sApiCoreV1AWSElasticBlockStoreVolumeSource $awsElasticBlockStore,
        public OptIoK8sApiCoreV1AzureDiskVolumeSource $azureDisk,
        public OptIoK8sApiCoreV1AzureFilePersistentVolumeSource $azureFile,
        public OptIoK8sApiCoreV1PersistentVolumeSpecCapacity $capacity,
        public OptIoK8sApiCoreV1CephFSPersistentVolumeSource $cephfs,
        public OptIoK8sApiCoreV1CinderPersistentVolumeSource $cinder,
        public OptIoK8sApiCoreV1ObjectReference $claimRef,
        public OptIoK8sApiCoreV1CSIPersistentVolumeSource $csi,
        public OptIoK8sApiCoreV1FCVolumeSource $fc,
        public OptIoK8sApiCoreV1FlexPersistentVolumeSource $flexVolume,
        public OptIoK8sApiCoreV1FlockerVolumeSource $flocker,
        public OptIoK8sApiCoreV1GCEPersistentDiskVolumeSource $gcePersistentDisk,
        public OptIoK8sApiCoreV1GlusterfsPersistentVolumeSource $glusterfs,
        public OptIoK8sApiCoreV1HostPathVolumeSource $hostPath,
        public OptIoK8sApiCoreV1ISCSIPersistentVolumeSource $iscsi,
        public OptIoK8sApiCoreV1LocalVolumeSource $local,
        /** @var string[] */
        public array $mountOptions,
        public OptIoK8sApiCoreV1NFSVolumeSource $nfs,
        public OptIoK8sApiCoreV1VolumeNodeAffinity $nodeAffinity,
        public OptString $persistentVolumeReclaimPolicy,
        public OptIoK8sApiCoreV1PhotonPersistentDiskVolumeSource $photonPersistentDisk,
        public OptIoK8sApiCoreV1PortworxVolumeSource $portworxVolume,
        public OptIoK8sApiCoreV1QuobyteVolumeSource $quobyte,
        public OptIoK8sApiCoreV1RBDPersistentVolumeSource $rbd,
        public OptIoK8sApiCoreV1ScaleIOPersistentVolumeSource $scaleIO,
        public OptString $storageClassName,
        public OptIoK8sApiCoreV1StorageOSPersistentVolumeSource $storageos,
        public OptString $volumeMode,
        public OptIoK8sApiCoreV1VsphereVirtualDiskVolumeSource $vsphereVolume,
    ) {
        foreach ($this->accessModes as $item) {
            if (!is_string($item)) {
                throw new \InvalidArgumentException('Expected string');
            }
        }
        foreach ($this->mountOptions as $item) {
            if (!is_string($item)) {
                throw new \InvalidArgumentException('Expected string');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['accessModes'] = $this->accessModes;
        if ($this->awsElasticBlockStore->set) {
            $result['awsElasticBlockStore'] = $this->awsElasticBlockStore->value?->jsonSerialize();
        }
        if ($this->azureDisk->set) {
            $result['azureDisk'] = $this->azureDisk->value?->jsonSerialize();
        }
        if ($this->azureFile->set) {
            $result['azureFile'] = $this->azureFile->value?->jsonSerialize();
        }
        if ($this->capacity->set) {
            $result['capacity'] = $this->capacity->value;
        }
        if ($this->cephfs->set) {
            $result['cephfs'] = $this->cephfs->value?->jsonSerialize();
        }
        if ($this->cinder->set) {
            $result['cinder'] = $this->cinder->value?->jsonSerialize();
        }
        if ($this->claimRef->set) {
            $result['claimRef'] = $this->claimRef->value?->jsonSerialize();
        }
        if ($this->csi->set) {
            $result['csi'] = $this->csi->value?->jsonSerialize();
        }
        if ($this->fc->set) {
            $result['fc'] = $this->fc->value?->jsonSerialize();
        }
        if ($this->flexVolume->set) {
            $result['flexVolume'] = $this->flexVolume->value?->jsonSerialize();
        }
        if ($this->flocker->set) {
            $result['flocker'] = $this->flocker->value?->jsonSerialize();
        }
        if ($this->gcePersistentDisk->set) {
            $result['gcePersistentDisk'] = $this->gcePersistentDisk->value?->jsonSerialize();
        }
        if ($this->glusterfs->set) {
            $result['glusterfs'] = $this->glusterfs->value?->jsonSerialize();
        }
        if ($this->hostPath->set) {
            $result['hostPath'] = $this->hostPath->value?->jsonSerialize();
        }
        if ($this->iscsi->set) {
            $result['iscsi'] = $this->iscsi->value?->jsonSerialize();
        }
        if ($this->local->set) {
            $result['local'] = $this->local->value?->jsonSerialize();
        }
        $result['mountOptions'] = $this->mountOptions;
        if ($this->nfs->set) {
            $result['nfs'] = $this->nfs->value?->jsonSerialize();
        }
        if ($this->nodeAffinity->set) {
            $result['nodeAffinity'] = $this->nodeAffinity->value?->jsonSerialize();
        }
        if ($this->persistentVolumeReclaimPolicy->set) {
            $result['persistentVolumeReclaimPolicy'] = $this->persistentVolumeReclaimPolicy->value;
        }
        if ($this->photonPersistentDisk->set) {
            $result['photonPersistentDisk'] = $this->photonPersistentDisk->value?->jsonSerialize();
        }
        if ($this->portworxVolume->set) {
            $result['portworxVolume'] = $this->portworxVolume->value?->jsonSerialize();
        }
        if ($this->quobyte->set) {
            $result['quobyte'] = $this->quobyte->value?->jsonSerialize();
        }
        if ($this->rbd->set) {
            $result['rbd'] = $this->rbd->value?->jsonSerialize();
        }
        if ($this->scaleIO->set) {
            $result['scaleIO'] = $this->scaleIO->value?->jsonSerialize();
        }
        if ($this->storageClassName->set) {
            $result['storageClassName'] = $this->storageClassName->value;
        }
        if ($this->storageos->set) {
            $result['storageos'] = $this->storageos->value?->jsonSerialize();
        }
        if ($this->volumeMode->set) {
            $result['volumeMode'] = $this->volumeMode->value;
        }
        if ($this->vsphereVolume->set) {
            $result['vsphereVolume'] = $this->vsphereVolume->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            accessModes: $data['accessModes'],
            awsElasticBlockStore: \array_key_exists('awsElasticBlockStore', $data)
                ? OptIoK8sApiCoreV1AWSElasticBlockStoreVolumeSource::some(IoK8sApiCoreV1AWSElasticBlockStoreVolumeSource::fromArray($data['awsElasticBlockStore']))
                : OptIoK8sApiCoreV1AWSElasticBlockStoreVolumeSource::none(),
            azureDisk: \array_key_exists('azureDisk', $data)
                ? OptIoK8sApiCoreV1AzureDiskVolumeSource::some(IoK8sApiCoreV1AzureDiskVolumeSource::fromArray($data['azureDisk']))
                : OptIoK8sApiCoreV1AzureDiskVolumeSource::none(),
            azureFile: \array_key_exists('azureFile', $data)
                ? OptIoK8sApiCoreV1AzureFilePersistentVolumeSource::some(IoK8sApiCoreV1AzureFilePersistentVolumeSource::fromArray($data['azureFile']))
                : OptIoK8sApiCoreV1AzureFilePersistentVolumeSource::none(),
            capacity: \array_key_exists('capacity', $data)
                ? OptIoK8sApiCoreV1PersistentVolumeSpecCapacity::some($data['capacity'])
                : OptIoK8sApiCoreV1PersistentVolumeSpecCapacity::none(),
            cephfs: \array_key_exists('cephfs', $data)
                ? OptIoK8sApiCoreV1CephFSPersistentVolumeSource::some(IoK8sApiCoreV1CephFSPersistentVolumeSource::fromArray($data['cephfs']))
                : OptIoK8sApiCoreV1CephFSPersistentVolumeSource::none(),
            cinder: \array_key_exists('cinder', $data)
                ? OptIoK8sApiCoreV1CinderPersistentVolumeSource::some(IoK8sApiCoreV1CinderPersistentVolumeSource::fromArray($data['cinder']))
                : OptIoK8sApiCoreV1CinderPersistentVolumeSource::none(),
            claimRef: \array_key_exists('claimRef', $data)
                ? OptIoK8sApiCoreV1ObjectReference::some(IoK8sApiCoreV1ObjectReference::fromArray($data['claimRef']))
                : OptIoK8sApiCoreV1ObjectReference::none(),
            csi: \array_key_exists('csi', $data)
                ? OptIoK8sApiCoreV1CSIPersistentVolumeSource::some(IoK8sApiCoreV1CSIPersistentVolumeSource::fromArray($data['csi']))
                : OptIoK8sApiCoreV1CSIPersistentVolumeSource::none(),
            fc: \array_key_exists('fc', $data)
                ? OptIoK8sApiCoreV1FCVolumeSource::some(IoK8sApiCoreV1FCVolumeSource::fromArray($data['fc']))
                : OptIoK8sApiCoreV1FCVolumeSource::none(),
            flexVolume: \array_key_exists('flexVolume', $data)
                ? OptIoK8sApiCoreV1FlexPersistentVolumeSource::some(IoK8sApiCoreV1FlexPersistentVolumeSource::fromArray($data['flexVolume']))
                : OptIoK8sApiCoreV1FlexPersistentVolumeSource::none(),
            flocker: \array_key_exists('flocker', $data)
                ? OptIoK8sApiCoreV1FlockerVolumeSource::some(IoK8sApiCoreV1FlockerVolumeSource::fromArray($data['flocker']))
                : OptIoK8sApiCoreV1FlockerVolumeSource::none(),
            gcePersistentDisk: \array_key_exists('gcePersistentDisk', $data)
                ? OptIoK8sApiCoreV1GCEPersistentDiskVolumeSource::some(IoK8sApiCoreV1GCEPersistentDiskVolumeSource::fromArray($data['gcePersistentDisk']))
                : OptIoK8sApiCoreV1GCEPersistentDiskVolumeSource::none(),
            glusterfs: \array_key_exists('glusterfs', $data)
                ? OptIoK8sApiCoreV1GlusterfsPersistentVolumeSource::some(IoK8sApiCoreV1GlusterfsPersistentVolumeSource::fromArray($data['glusterfs']))
                : OptIoK8sApiCoreV1GlusterfsPersistentVolumeSource::none(),
            hostPath: \array_key_exists('hostPath', $data)
                ? OptIoK8sApiCoreV1HostPathVolumeSource::some(IoK8sApiCoreV1HostPathVolumeSource::fromArray($data['hostPath']))
                : OptIoK8sApiCoreV1HostPathVolumeSource::none(),
            iscsi: \array_key_exists('iscsi', $data)
                ? OptIoK8sApiCoreV1ISCSIPersistentVolumeSource::some(IoK8sApiCoreV1ISCSIPersistentVolumeSource::fromArray($data['iscsi']))
                : OptIoK8sApiCoreV1ISCSIPersistentVolumeSource::none(),
            local: \array_key_exists('local', $data)
                ? OptIoK8sApiCoreV1LocalVolumeSource::some(IoK8sApiCoreV1LocalVolumeSource::fromArray($data['local']))
                : OptIoK8sApiCoreV1LocalVolumeSource::none(),
            mountOptions: $data['mountOptions'],
            nfs: \array_key_exists('nfs', $data)
                ? OptIoK8sApiCoreV1NFSVolumeSource::some(IoK8sApiCoreV1NFSVolumeSource::fromArray($data['nfs']))
                : OptIoK8sApiCoreV1NFSVolumeSource::none(),
            nodeAffinity: \array_key_exists('nodeAffinity', $data)
                ? OptIoK8sApiCoreV1VolumeNodeAffinity::some(IoK8sApiCoreV1VolumeNodeAffinity::fromArray($data['nodeAffinity']))
                : OptIoK8sApiCoreV1VolumeNodeAffinity::none(),
            persistentVolumeReclaimPolicy: \array_key_exists('persistentVolumeReclaimPolicy', $data)
                ? OptString::some($data['persistentVolumeReclaimPolicy'])
                : OptString::none(),
            photonPersistentDisk: \array_key_exists('photonPersistentDisk', $data)
                ? OptIoK8sApiCoreV1PhotonPersistentDiskVolumeSource::some(IoK8sApiCoreV1PhotonPersistentDiskVolumeSource::fromArray($data['photonPersistentDisk']))
                : OptIoK8sApiCoreV1PhotonPersistentDiskVolumeSource::none(),
            portworxVolume: \array_key_exists('portworxVolume', $data)
                ? OptIoK8sApiCoreV1PortworxVolumeSource::some(IoK8sApiCoreV1PortworxVolumeSource::fromArray($data['portworxVolume']))
                : OptIoK8sApiCoreV1PortworxVolumeSource::none(),
            quobyte: \array_key_exists('quobyte', $data)
                ? OptIoK8sApiCoreV1QuobyteVolumeSource::some(IoK8sApiCoreV1QuobyteVolumeSource::fromArray($data['quobyte']))
                : OptIoK8sApiCoreV1QuobyteVolumeSource::none(),
            rbd: \array_key_exists('rbd', $data)
                ? OptIoK8sApiCoreV1RBDPersistentVolumeSource::some(IoK8sApiCoreV1RBDPersistentVolumeSource::fromArray($data['rbd']))
                : OptIoK8sApiCoreV1RBDPersistentVolumeSource::none(),
            scaleIO: \array_key_exists('scaleIO', $data)
                ? OptIoK8sApiCoreV1ScaleIOPersistentVolumeSource::some(IoK8sApiCoreV1ScaleIOPersistentVolumeSource::fromArray($data['scaleIO']))
                : OptIoK8sApiCoreV1ScaleIOPersistentVolumeSource::none(),
            storageClassName: \array_key_exists('storageClassName', $data)
                ? OptString::some($data['storageClassName'])
                : OptString::none(),
            storageos: \array_key_exists('storageos', $data)
                ? OptIoK8sApiCoreV1StorageOSPersistentVolumeSource::some(IoK8sApiCoreV1StorageOSPersistentVolumeSource::fromArray($data['storageos']))
                : OptIoK8sApiCoreV1StorageOSPersistentVolumeSource::none(),
            volumeMode: \array_key_exists('volumeMode', $data)
                ? OptString::some($data['volumeMode'])
                : OptString::none(),
            vsphereVolume: \array_key_exists('vsphereVolume', $data)
                ? OptIoK8sApiCoreV1VsphereVirtualDiskVolumeSource::some(IoK8sApiCoreV1VsphereVirtualDiskVolumeSource::fromArray($data['vsphereVolume']))
                : OptIoK8sApiCoreV1VsphereVirtualDiskVolumeSource::none(),
        );
    }
}
