<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * ResourceFieldSelector represents container resources (cpu, memory) and their output format.
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.ResourceFieldSelector
 */
final readonly class IoK8sApiCoreV1ResourceFieldSelector implements JsonSerializable
{
    public function __construct(
        public OptString $containerName,
        public OptIoK8sApimachineryPkgApiResourceQuantity $divisor,
        public string $resource,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->containerName->set) {
            $result['containerName'] = $this->containerName->value;
        }
        if ($this->divisor->set) {
            $result['divisor'] = $this->divisor->value;
        }
        $result['resource'] = $this->resource;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            containerName: \array_key_exists('containerName', $data)
                ? OptString::some($data['containerName'])
                : OptString::none(),
            divisor: \array_key_exists('divisor', $data)
                ? OptIoK8sApimachineryPkgApiResourceQuantity::some($data['divisor'])
                : OptIoK8sApimachineryPkgApiResourceQuantity::none(),
            resource: $data['resource'],
        );
    }
}
