<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * A StatefulSetSpec is the specification of a StatefulSet.
 *
 * Ref: #/components/schemas/io.k8s.api.apps.v1.StatefulSetSpec
 */
final readonly class IoK8sApiAppsV1StatefulSetSpec implements JsonSerializable
{
    public function __construct(
        public OptInt32 $minReadySeconds,
        public OptString $podManagementPolicy,
        public OptInt32 $replicas,
        public OptInt32 $revisionHistoryLimit,
        public IoK8sApimachineryPkgApisMetaV1LabelSelector $selector,
        public string $serviceName,
        public IoK8sApiCoreV1PodTemplateSpec $template,
        public OptIoK8sApiAppsV1StatefulSetUpdateStrategy $updateStrategy,
        /** @var IoK8sApiCoreV1PersistentVolumeClaim[] */
        public array $volumeClaimTemplates,
    ) {
        foreach ($this->volumeClaimTemplates as $item) {
            if (!$item instanceof IoK8sApiCoreV1PersistentVolumeClaim) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApiCoreV1PersistentVolumeClaim');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->minReadySeconds->set) {
            $result['minReadySeconds'] = $this->minReadySeconds->value;
        }
        if ($this->podManagementPolicy->set) {
            $result['podManagementPolicy'] = $this->podManagementPolicy->value;
        }
        if ($this->replicas->set) {
            $result['replicas'] = $this->replicas->value;
        }
        if ($this->revisionHistoryLimit->set) {
            $result['revisionHistoryLimit'] = $this->revisionHistoryLimit->value;
        }
        $result['selector'] = $this->selector->jsonSerialize();
        $result['serviceName'] = $this->serviceName;
        $result['template'] = $this->template->jsonSerialize();
        if ($this->updateStrategy->set) {
            $result['updateStrategy'] = $this->updateStrategy->value?->jsonSerialize();
        }
        $result['volumeClaimTemplates'] = array_map(fn ($item) => $item->jsonSerialize(), $this->volumeClaimTemplates);

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            minReadySeconds: \array_key_exists('minReadySeconds', $data)
                ? OptInt32::some($data['minReadySeconds'])
                : OptInt32::none(),
            podManagementPolicy: \array_key_exists('podManagementPolicy', $data)
                ? OptString::some($data['podManagementPolicy'])
                : OptString::none(),
            replicas: \array_key_exists('replicas', $data)
                ? OptInt32::some($data['replicas'])
                : OptInt32::none(),
            revisionHistoryLimit: \array_key_exists('revisionHistoryLimit', $data)
                ? OptInt32::some($data['revisionHistoryLimit'])
                : OptInt32::none(),
            selector: IoK8sApimachineryPkgApisMetaV1LabelSelector::fromArray($data['selector']),
            serviceName: $data['serviceName'],
            template: IoK8sApiCoreV1PodTemplateSpec::fromArray($data['template']),
            updateStrategy: \array_key_exists('updateStrategy', $data)
                ? OptIoK8sApiAppsV1StatefulSetUpdateStrategy::some(IoK8sApiAppsV1StatefulSetUpdateStrategy::fromArray($data['updateStrategy']))
                : OptIoK8sApiAppsV1StatefulSetUpdateStrategy::none(),
            volumeClaimTemplates: array_map(IoK8sApiCoreV1PersistentVolumeClaim::fromArray(...), $data['volumeClaimTemplates']),
        );
    }
}
