<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * ServiceAccountSubject holds detailed information for service-account-kind subject.
 *
 * Ref: #/components/schemas/io.k8s.api.flowcontrol.v1beta1.ServiceAccountSubject
 */
final readonly class IoK8sApiFlowcontrolV1beta1ServiceAccountSubject implements JsonSerializable
{
    public function __construct(
        public string $name,
        public string $namespace,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['name'] = $this->name;
        $result['namespace'] = $this->namespace;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            name: $data['name'],
            namespace: $data['namespace'],
        );
    }
}
