<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * NetworkPolicyPort describes a port to allow traffic on.
 *
 * Ref: #/components/schemas/io.k8s.api.networking.v1.NetworkPolicyPort
 */
final readonly class IoK8sApiNetworkingV1NetworkPolicyPort implements JsonSerializable
{
    public function __construct(
        public OptInt32 $endPort,
        public OptIoK8sApimachineryPkgUtilIntstrIntOrString $port,
        public OptString $protocol,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->endPort->set) {
            $result['endPort'] = $this->endPort->value;
        }
        if ($this->port->set) {
            $result['port'] = $this->port->value;
        }
        if ($this->protocol->set) {
            $result['protocol'] = $this->protocol->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            endPort: \array_key_exists('endPort', $data)
                ? OptInt32::some($data['endPort'])
                : OptInt32::none(),
            port: \array_key_exists('port', $data)
                ? OptIoK8sApimachineryPkgUtilIntstrIntOrString::some($data['port'])
                : OptIoK8sApimachineryPkgUtilIntstrIntOrString::none(),
            protocol: \array_key_exists('protocol', $data)
                ? OptString::some($data['protocol'])
                : OptString::none(),
        );
    }
}
