<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * CustomResourceDefinitionStatus indicates the state of the CustomResourceDefinition.
 *
 * Ref: #/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionStatus
 */
final readonly class IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionStatus implements JsonSerializable
{
    public function __construct(
        public OptIoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionNames $acceptedNames,
        /** @var IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionCondition[] */
        public array $conditions,
        /** @var string[] */
        public array $storedVersions,
    ) {
        foreach ($this->conditions as $item) {
            if (!$item instanceof IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionCondition) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionCondition');
            }
        }
        foreach ($this->storedVersions as $item) {
            if (!is_string($item)) {
                throw new \InvalidArgumentException('Expected string');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->acceptedNames->set) {
            $result['acceptedNames'] = $this->acceptedNames->value?->jsonSerialize();
        }
        $result['conditions'] = array_map(fn ($item) => $item->jsonSerialize(), $this->conditions);
        $result['storedVersions'] = $this->storedVersions;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            acceptedNames: \array_key_exists('acceptedNames', $data)
                ? OptIoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionNames::some(IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionNames::fromArray($data['acceptedNames']))
                : OptIoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionNames::none(),
            conditions: array_map(IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionCondition::fromArray(...), $data['conditions']),
            storedVersions: $data['storedVersions'],
        );
    }
}
