<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * CustomResourceDefinition represents a resource that should be exposed on the API server.  Its name
 * MUST be in the format <.spec.name>.<.spec.group>.
 *
 * Ref: #/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition
 */
final readonly class IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinition implements JsonSerializable
{
    public function __construct(
        public OptString $apiVersion,
        public OptString $kind,
        public OptIoK8sApimachineryPkgApisMetaV1ObjectMeta $metadata,
        public IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionSpec $spec,
        public OptIoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionStatus $status,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->apiVersion->set) {
            $result['apiVersion'] = $this->apiVersion->value;
        }
        if ($this->kind->set) {
            $result['kind'] = $this->kind->value;
        }
        if ($this->metadata->set) {
            $result['metadata'] = $this->metadata->value?->jsonSerialize();
        }
        $result['spec'] = $this->spec->jsonSerialize();
        if ($this->status->set) {
            $result['status'] = $this->status->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            apiVersion: \array_key_exists('apiVersion', $data)
                ? OptString::some($data['apiVersion'])
                : OptString::none(),
            kind: \array_key_exists('kind', $data)
                ? OptString::some($data['kind'])
                : OptString::none(),
            metadata: \array_key_exists('metadata', $data)
                ? OptIoK8sApimachineryPkgApisMetaV1ObjectMeta::some(IoK8sApimachineryPkgApisMetaV1ObjectMeta::fromArray($data['metadata']))
                : OptIoK8sApimachineryPkgApisMetaV1ObjectMeta::none(),
            spec: IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionSpec::fromArray($data['spec']),
            status: \array_key_exists('status', $data)
                ? OptIoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionStatus::some(IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionStatus::fromArray($data['status']))
                : OptIoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionStatus::none(),
        );
    }
}
