<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Event is a report of an event somewhere in the cluster. It generally denotes some state change in
 * the system. Events have a limited retention time and triggers and messages may evolve with time. 
 * Event consumers should not rely on the timing of an event with a given Reason reflecting a
 * consistent underlying trigger, or the continued existence of events with that Reason.  Events
 * should be treated as informative, best-effort, supplemental data.
 *
 * Ref: #/components/schemas/io.k8s.api.events.v1beta1.Event
 */
final readonly class IoK8sApiEventsV1beta1Event implements JsonSerializable
{
    public function __construct(
        public OptString $action,
        public OptString $apiVersion,
        public OptInt32 $deprecatedCount,
        public OptIoK8sApimachineryPkgApisMetaV1Time $deprecatedFirstTimestamp,
        public OptIoK8sApimachineryPkgApisMetaV1Time $deprecatedLastTimestamp,
        public OptIoK8sApiCoreV1EventSource $deprecatedSource,
        public string $eventTime,
        public OptString $kind,
        public OptIoK8sApimachineryPkgApisMetaV1ObjectMeta $metadata,
        public OptString $note,
        public OptString $reason,
        public OptIoK8sApiCoreV1ObjectReference $regarding,
        public OptIoK8sApiCoreV1ObjectReference $related,
        public OptString $reportingController,
        public OptString $reportingInstance,
        public OptIoK8sApiEventsV1beta1EventSeries $series,
        public OptString $type,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->action->set) {
            $result['action'] = $this->action->value;
        }
        if ($this->apiVersion->set) {
            $result['apiVersion'] = $this->apiVersion->value;
        }
        if ($this->deprecatedCount->set) {
            $result['deprecatedCount'] = $this->deprecatedCount->value;
        }
        if ($this->deprecatedFirstTimestamp->set) {
            $result['deprecatedFirstTimestamp'] = $this->deprecatedFirstTimestamp->value;
        }
        if ($this->deprecatedLastTimestamp->set) {
            $result['deprecatedLastTimestamp'] = $this->deprecatedLastTimestamp->value;
        }
        if ($this->deprecatedSource->set) {
            $result['deprecatedSource'] = $this->deprecatedSource->value?->jsonSerialize();
        }
        $result['eventTime'] = $this->eventTime;
        if ($this->kind->set) {
            $result['kind'] = $this->kind->value;
        }
        if ($this->metadata->set) {
            $result['metadata'] = $this->metadata->value?->jsonSerialize();
        }
        if ($this->note->set) {
            $result['note'] = $this->note->value;
        }
        if ($this->reason->set) {
            $result['reason'] = $this->reason->value;
        }
        if ($this->regarding->set) {
            $result['regarding'] = $this->regarding->value?->jsonSerialize();
        }
        if ($this->related->set) {
            $result['related'] = $this->related->value?->jsonSerialize();
        }
        if ($this->reportingController->set) {
            $result['reportingController'] = $this->reportingController->value;
        }
        if ($this->reportingInstance->set) {
            $result['reportingInstance'] = $this->reportingInstance->value;
        }
        if ($this->series->set) {
            $result['series'] = $this->series->value?->jsonSerialize();
        }
        if ($this->type->set) {
            $result['type'] = $this->type->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            action: \array_key_exists('action', $data)
                ? OptString::some($data['action'])
                : OptString::none(),
            apiVersion: \array_key_exists('apiVersion', $data)
                ? OptString::some($data['apiVersion'])
                : OptString::none(),
            deprecatedCount: \array_key_exists('deprecatedCount', $data)
                ? OptInt32::some($data['deprecatedCount'])
                : OptInt32::none(),
            deprecatedFirstTimestamp: \array_key_exists('deprecatedFirstTimestamp', $data)
                ? OptIoK8sApimachineryPkgApisMetaV1Time::some($data['deprecatedFirstTimestamp'])
                : OptIoK8sApimachineryPkgApisMetaV1Time::none(),
            deprecatedLastTimestamp: \array_key_exists('deprecatedLastTimestamp', $data)
                ? OptIoK8sApimachineryPkgApisMetaV1Time::some($data['deprecatedLastTimestamp'])
                : OptIoK8sApimachineryPkgApisMetaV1Time::none(),
            deprecatedSource: \array_key_exists('deprecatedSource', $data)
                ? OptIoK8sApiCoreV1EventSource::some(IoK8sApiCoreV1EventSource::fromArray($data['deprecatedSource']))
                : OptIoK8sApiCoreV1EventSource::none(),
            eventTime: $data['eventTime'],
            kind: \array_key_exists('kind', $data)
                ? OptString::some($data['kind'])
                : OptString::none(),
            metadata: \array_key_exists('metadata', $data)
                ? OptIoK8sApimachineryPkgApisMetaV1ObjectMeta::some(IoK8sApimachineryPkgApisMetaV1ObjectMeta::fromArray($data['metadata']))
                : OptIoK8sApimachineryPkgApisMetaV1ObjectMeta::none(),
            note: \array_key_exists('note', $data)
                ? OptString::some($data['note'])
                : OptString::none(),
            reason: \array_key_exists('reason', $data)
                ? OptString::some($data['reason'])
                : OptString::none(),
            regarding: \array_key_exists('regarding', $data)
                ? OptIoK8sApiCoreV1ObjectReference::some(IoK8sApiCoreV1ObjectReference::fromArray($data['regarding']))
                : OptIoK8sApiCoreV1ObjectReference::none(),
            related: \array_key_exists('related', $data)
                ? OptIoK8sApiCoreV1ObjectReference::some(IoK8sApiCoreV1ObjectReference::fromArray($data['related']))
                : OptIoK8sApiCoreV1ObjectReference::none(),
            reportingController: \array_key_exists('reportingController', $data)
                ? OptString::some($data['reportingController'])
                : OptString::none(),
            reportingInstance: \array_key_exists('reportingInstance', $data)
                ? OptString::some($data['reportingInstance'])
                : OptString::none(),
            series: \array_key_exists('series', $data)
                ? OptIoK8sApiEventsV1beta1EventSeries::some(IoK8sApiEventsV1beta1EventSeries::fromArray($data['series']))
                : OptIoK8sApiEventsV1beta1EventSeries::none(),
            type: \array_key_exists('type', $data)
                ? OptString::some($data['type'])
                : OptString::none(),
        );
    }
}
