<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * HTTPGetAction describes an action based on HTTP Get requests.
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.HTTPGetAction
 */
final readonly class IoK8sApiCoreV1HTTPGetAction implements JsonSerializable
{
    public function __construct(
        public OptString $host,
        /** @var IoK8sApiCoreV1HTTPHeader[] */
        public array $httpHeaders,
        public OptString $path,
        public string $port,
        public OptString $scheme,
    ) {
        foreach ($this->httpHeaders as $item) {
            if (!$item instanceof IoK8sApiCoreV1HTTPHeader) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApiCoreV1HTTPHeader');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->host->set) {
            $result['host'] = $this->host->value;
        }
        $result['httpHeaders'] = array_map(fn ($item) => $item->jsonSerialize(), $this->httpHeaders);
        if ($this->path->set) {
            $result['path'] = $this->path->value;
        }
        $result['port'] = $this->port;
        if ($this->scheme->set) {
            $result['scheme'] = $this->scheme->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            host: \array_key_exists('host', $data)
                ? OptString::some($data['host'])
                : OptString::none(),
            httpHeaders: array_map(IoK8sApiCoreV1HTTPHeader::fromArray(...), $data['httpHeaders']),
            path: \array_key_exists('path', $data)
                ? OptString::some($data['path'])
                : OptString::none(),
            port: $data['port'],
            scheme: \array_key_exists('scheme', $data)
                ? OptString::some($data['scheme'])
                : OptString::none(),
        );
    }
}
