<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * ExternalMetricStatus indicates the current value of a global metric not associated with any
 * Kubernetes object.
 *
 * Ref: #/components/schemas/io.k8s.api.autoscaling.v2beta1.ExternalMetricStatus
 */
final readonly class IoK8sApiAutoscalingV2beta1ExternalMetricStatus implements JsonSerializable
{
    public function __construct(
        public OptIoK8sApimachineryPkgApiResourceQuantity $currentAverageValue,
        public string $currentValue,
        public string $metricName,
        public OptIoK8sApimachineryPkgApisMetaV1LabelSelector $metricSelector,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->currentAverageValue->set) {
            $result['currentAverageValue'] = $this->currentAverageValue->value;
        }
        $result['currentValue'] = $this->currentValue;
        $result['metricName'] = $this->metricName;
        if ($this->metricSelector->set) {
            $result['metricSelector'] = $this->metricSelector->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            currentAverageValue: \array_key_exists('currentAverageValue', $data)
                ? OptIoK8sApimachineryPkgApiResourceQuantity::some($data['currentAverageValue'])
                : OptIoK8sApimachineryPkgApiResourceQuantity::none(),
            currentValue: $data['currentValue'],
            metricName: $data['metricName'],
            metricSelector: \array_key_exists('metricSelector', $data)
                ? OptIoK8sApimachineryPkgApisMetaV1LabelSelector::some(IoK8sApimachineryPkgApisMetaV1LabelSelector::fromArray($data['metricSelector']))
                : OptIoK8sApimachineryPkgApisMetaV1LabelSelector::none(),
        );
    }
}
