<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * EnvVarSource represents a source for the value of an EnvVar.
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.EnvVarSource
 */
final readonly class IoK8sApiCoreV1EnvVarSource implements JsonSerializable
{
    public function __construct(
        public OptIoK8sApiCoreV1ConfigMapKeySelector $configMapKeyRef,
        public OptIoK8sApiCoreV1ObjectFieldSelector $fieldRef,
        public OptIoK8sApiCoreV1ResourceFieldSelector $resourceFieldRef,
        public OptIoK8sApiCoreV1SecretKeySelector $secretKeyRef,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->configMapKeyRef->set) {
            $result['configMapKeyRef'] = $this->configMapKeyRef->value?->jsonSerialize();
        }
        if ($this->fieldRef->set) {
            $result['fieldRef'] = $this->fieldRef->value?->jsonSerialize();
        }
        if ($this->resourceFieldRef->set) {
            $result['resourceFieldRef'] = $this->resourceFieldRef->value?->jsonSerialize();
        }
        if ($this->secretKeyRef->set) {
            $result['secretKeyRef'] = $this->secretKeyRef->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            configMapKeyRef: \array_key_exists('configMapKeyRef', $data)
                ? OptIoK8sApiCoreV1ConfigMapKeySelector::some(IoK8sApiCoreV1ConfigMapKeySelector::fromArray($data['configMapKeyRef']))
                : OptIoK8sApiCoreV1ConfigMapKeySelector::none(),
            fieldRef: \array_key_exists('fieldRef', $data)
                ? OptIoK8sApiCoreV1ObjectFieldSelector::some(IoK8sApiCoreV1ObjectFieldSelector::fromArray($data['fieldRef']))
                : OptIoK8sApiCoreV1ObjectFieldSelector::none(),
            resourceFieldRef: \array_key_exists('resourceFieldRef', $data)
                ? OptIoK8sApiCoreV1ResourceFieldSelector::some(IoK8sApiCoreV1ResourceFieldSelector::fromArray($data['resourceFieldRef']))
                : OptIoK8sApiCoreV1ResourceFieldSelector::none(),
            secretKeyRef: \array_key_exists('secretKeyRef', $data)
                ? OptIoK8sApiCoreV1SecretKeySelector::some(IoK8sApiCoreV1SecretKeySelector::fromArray($data['secretKeyRef']))
                : OptIoK8sApiCoreV1SecretKeySelector::none(),
        );
    }
}
