<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Represents a host path mapped into a pod. Host path volumes do not support ownership management or
 * SELinux relabeling.
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.HostPathVolumeSource
 */
final readonly class IoK8sApiCoreV1HostPathVolumeSource implements JsonSerializable
{
    public function __construct(
        public string $path,
        public OptString $type,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['path'] = $this->path;
        if ($this->type->set) {
            $result['type'] = $this->type->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            path: $data['path'],
            type: \array_key_exists('type', $data)
                ? OptString::some($data['type'])
                : OptString::none(),
        );
    }
}
