<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * WebhookClientConfig contains the information to make a TLS connection with the webhook.
 *
 * Ref: #/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.WebhookClientConfig
 */
final readonly class IoK8sApiextensionsApiserverPkgApisApiextensionsV1WebhookClientConfig implements JsonSerializable
{
    public function __construct(
        public string $caBundle,
        public OptIoK8sApiextensionsApiserverPkgApisApiextensionsV1ServiceReference $service,
        public OptString $url,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['caBundle'] = $this->caBundle;
        if ($this->service->set) {
            $result['service'] = $this->service->value?->jsonSerialize();
        }
        if ($this->url->set) {
            $result['url'] = $this->url->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            caBundle: $data['caBundle'],
            service: \array_key_exists('service', $data)
                ? OptIoK8sApiextensionsApiserverPkgApisApiextensionsV1ServiceReference::some(IoK8sApiextensionsApiserverPkgApisApiextensionsV1ServiceReference::fromArray($data['service']))
                : OptIoK8sApiextensionsApiserverPkgApisApiextensionsV1ServiceReference::none(),
            url: \array_key_exists('url', $data)
                ? OptString::some($data['url'])
                : OptString::none(),
        );
    }
}
