<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * A scope selector represents the AND of the selectors represented by the scoped-resource selector
 * requirements.
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.ScopeSelector
 */
final readonly class IoK8sApiCoreV1ScopeSelector implements JsonSerializable
{
    public function __construct(
        /** @var IoK8sApiCoreV1ScopedResourceSelectorRequirement[] */
        public array $matchExpressions,
    ) {
        foreach ($this->matchExpressions as $item) {
            if (!$item instanceof IoK8sApiCoreV1ScopedResourceSelectorRequirement) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApiCoreV1ScopedResourceSelectorRequirement');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['matchExpressions'] = array_map(fn ($item) => $item->jsonSerialize(), $this->matchExpressions);

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            matchExpressions: array_map(IoK8sApiCoreV1ScopedResourceSelectorRequirement::fromArray(...), $data['matchExpressions']),
        );
    }
}
