<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Local represents directly-attached storage with node affinity (Beta feature).
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.LocalVolumeSource
 */
final readonly class IoK8sApiCoreV1LocalVolumeSource implements JsonSerializable
{
    public function __construct(
        public OptString $fsType,
        public string $path,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->fsType->set) {
            $result['fsType'] = $this->fsType->value;
        }
        $result['path'] = $this->path;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            fsType: \array_key_exists('fsType', $data)
                ? OptString::some($data['fsType'])
                : OptString::none(),
            path: $data['path'],
        );
    }
}
