<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * CSINodeSpec holds information about the specification of all CSI drivers installed on a node.
 *
 * Ref: #/components/schemas/io.k8s.api.storage.v1.CSINodeSpec
 */
final readonly class IoK8sApiStorageV1CSINodeSpec implements JsonSerializable
{
    public function __construct(
        /** @var IoK8sApiStorageV1CSINodeDriver[] */
        public array $drivers,
    ) {
        foreach ($this->drivers as $item) {
            if (!$item instanceof IoK8sApiStorageV1CSINodeDriver) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApiStorageV1CSINodeDriver');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['drivers'] = array_map(fn ($item) => $item->jsonSerialize(), $this->drivers);

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            drivers: array_map(IoK8sApiStorageV1CSINodeDriver::fromArray(...), $data['drivers']),
        );
    }
}
