<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * DeploymentSpec is the specification of the desired behavior of the Deployment.
 *
 * Ref: #/components/schemas/io.k8s.api.apps.v1.DeploymentSpec
 */
final readonly class IoK8sApiAppsV1DeploymentSpec implements JsonSerializable
{
    public function __construct(
        public OptInt32 $minReadySeconds,
        public OptBool $paused,
        public OptInt32 $progressDeadlineSeconds,
        public OptInt32 $replicas,
        public OptInt32 $revisionHistoryLimit,
        public IoK8sApimachineryPkgApisMetaV1LabelSelector $selector,
        public OptIoK8sApiAppsV1DeploymentStrategy $strategy,
        public IoK8sApiCoreV1PodTemplateSpec $template,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->minReadySeconds->set) {
            $result['minReadySeconds'] = $this->minReadySeconds->value;
        }
        if ($this->paused->set) {
            $result['paused'] = $this->paused->value;
        }
        if ($this->progressDeadlineSeconds->set) {
            $result['progressDeadlineSeconds'] = $this->progressDeadlineSeconds->value;
        }
        if ($this->replicas->set) {
            $result['replicas'] = $this->replicas->value;
        }
        if ($this->revisionHistoryLimit->set) {
            $result['revisionHistoryLimit'] = $this->revisionHistoryLimit->value;
        }
        $result['selector'] = $this->selector->jsonSerialize();
        if ($this->strategy->set) {
            $result['strategy'] = $this->strategy->value?->jsonSerialize();
        }
        $result['template'] = $this->template->jsonSerialize();

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            minReadySeconds: \array_key_exists('minReadySeconds', $data)
                ? OptInt32::some($data['minReadySeconds'])
                : OptInt32::none(),
            paused: \array_key_exists('paused', $data)
                ? OptBool::some($data['paused'])
                : OptBool::none(),
            progressDeadlineSeconds: \array_key_exists('progressDeadlineSeconds', $data)
                ? OptInt32::some($data['progressDeadlineSeconds'])
                : OptInt32::none(),
            replicas: \array_key_exists('replicas', $data)
                ? OptInt32::some($data['replicas'])
                : OptInt32::none(),
            revisionHistoryLimit: \array_key_exists('revisionHistoryLimit', $data)
                ? OptInt32::some($data['revisionHistoryLimit'])
                : OptInt32::none(),
            selector: IoK8sApimachineryPkgApisMetaV1LabelSelector::fromArray($data['selector']),
            strategy: \array_key_exists('strategy', $data)
                ? OptIoK8sApiAppsV1DeploymentStrategy::some(IoK8sApiAppsV1DeploymentStrategy::fromArray($data['strategy']))
                : OptIoK8sApiAppsV1DeploymentStrategy::none(),
            template: IoK8sApiCoreV1PodTemplateSpec::fromArray($data['template']),
        );
    }
}
