<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * NodeDaemonEndpoints lists ports opened by daemons running on the Node.
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.NodeDaemonEndpoints
 */
final readonly class IoK8sApiCoreV1NodeDaemonEndpoints implements JsonSerializable
{
    public function __construct(
        public OptIoK8sApiCoreV1DaemonEndpoint $kubeletEndpoint,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->kubeletEndpoint->set) {
            $result['kubeletEndpoint'] = $this->kubeletEndpoint->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            kubeletEndpoint: \array_key_exists('kubeletEndpoint', $data)
                ? OptIoK8sApiCoreV1DaemonEndpoint::some(IoK8sApiCoreV1DaemonEndpoint::fromArray($data['kubeletEndpoint']))
                : OptIoK8sApiCoreV1DaemonEndpoint::none(),
        );
    }
}
