<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Information about the condition of a component.
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.ComponentCondition
 */
final readonly class IoK8sApiCoreV1ComponentCondition implements JsonSerializable
{
    public function __construct(
        public OptString $error,
        public OptString $message,
        public string $status,
        public string $type,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->error->set) {
            $result['error'] = $this->error->value;
        }
        if ($this->message->set) {
            $result['message'] = $this->message->value;
        }
        $result['status'] = $this->status;
        $result['type'] = $this->type;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            error: \array_key_exists('error', $data)
                ? OptString::some($data['error'])
                : OptString::none(),
            message: \array_key_exists('message', $data)
                ? OptString::some($data['message'])
                : OptString::none(),
            status: $data['status'],
            type: $data['type'],
        );
    }
}
