<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * ServiceStatus represents the current status of a service.
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.ServiceStatus
 */
final readonly class IoK8sApiCoreV1ServiceStatus implements JsonSerializable
{
    public function __construct(
        /** @var IoK8sApimachineryPkgApisMetaV1Condition[] */
        public array $conditions,
        public OptIoK8sApiCoreV1LoadBalancerStatus $loadBalancer,
    ) {
        foreach ($this->conditions as $item) {
            if (!$item instanceof IoK8sApimachineryPkgApisMetaV1Condition) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApimachineryPkgApisMetaV1Condition');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['conditions'] = array_map(fn ($item) => $item->jsonSerialize(), $this->conditions);
        if ($this->loadBalancer->set) {
            $result['loadBalancer'] = $this->loadBalancer->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            conditions: array_map(IoK8sApimachineryPkgApisMetaV1Condition::fromArray(...), $data['conditions']),
            loadBalancer: \array_key_exists('loadBalancer', $data)
                ? OptIoK8sApiCoreV1LoadBalancerStatus::some(IoK8sApiCoreV1LoadBalancerStatus::fromArray($data['loadBalancer']))
                : OptIoK8sApiCoreV1LoadBalancerStatus::none(),
        );
    }
}
