<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Subject contains a reference to the object or user identities a role binding applies to.  This can
 * either hold a direct API object reference, or a value for non-objects such as user and group names.
 *
 * Ref: #/components/schemas/io.k8s.api.rbac.v1.Subject
 */
final readonly class IoK8sApiRbacV1Subject implements JsonSerializable
{
    public function __construct(
        public OptString $apiGroup,
        public string $kind,
        public string $name,
        public OptString $namespace,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->apiGroup->set) {
            $result['apiGroup'] = $this->apiGroup->value;
        }
        $result['kind'] = $this->kind;
        $result['name'] = $this->name;
        if ($this->namespace->set) {
            $result['namespace'] = $this->namespace->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            apiGroup: \array_key_exists('apiGroup', $data)
                ? OptString::some($data['apiGroup'])
                : OptString::none(),
            kind: $data['kind'],
            name: $data['name'],
            namespace: \array_key_exists('namespace', $data)
                ? OptString::some($data['namespace'])
                : OptString::none(),
        );
    }
}
