<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * CertificateSigningRequestStatus contains conditions used to indicate approved/denied/failed status
 * of the request, and the issued certificate.
 *
 * Ref: #/components/schemas/io.k8s.api.certificates.v1.CertificateSigningRequestStatus
 */
final readonly class IoK8sApiCertificatesV1CertificateSigningRequestStatus implements JsonSerializable
{
    public function __construct(
        public string $certificate,
        /** @var IoK8sApiCertificatesV1CertificateSigningRequestCondition[] */
        public array $conditions,
    ) {
        foreach ($this->conditions as $item) {
            if (!$item instanceof IoK8sApiCertificatesV1CertificateSigningRequestCondition) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApiCertificatesV1CertificateSigningRequestCondition');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['certificate'] = $this->certificate;
        $result['conditions'] = array_map(fn ($item) => $item->jsonSerialize(), $this->conditions);

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            certificate: $data['certificate'],
            conditions: array_map(IoK8sApiCertificatesV1CertificateSigningRequestCondition::fromArray(...), $data['conditions']),
        );
    }
}
