<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * EventSeries contain information on series of events, i.e. thing that was/is happening continuously
 * for some time.
 *
 * Ref: #/components/schemas/io.k8s.api.events.v1beta1.EventSeries
 */
final readonly class IoK8sApiEventsV1beta1EventSeries implements JsonSerializable
{
    public function __construct(
        public int $count,
        public string $lastObservedTime,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['count'] = $this->count;
        $result['lastObservedTime'] = $this->lastObservedTime;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            count: $data['count'],
            lastObservedTime: $data['lastObservedTime'],
        );
    }
}
