<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * A list of StorageVersions.
 *
 * Ref: #/components/schemas/io.k8s.api.apiserverinternal.v1alpha1.StorageVersionList
 */
final readonly class IoK8sApiApiserverinternalV1alpha1StorageVersionList implements JsonSerializable
{
    public function __construct(
        public OptString $apiVersion,
        /** @var IoK8sApiApiserverinternalV1alpha1StorageVersion[] */
        public array $items,
        public OptString $kind,
        public OptIoK8sApimachineryPkgApisMetaV1ListMeta $metadata,
    ) {
        foreach ($this->items as $item) {
            if (!$item instanceof IoK8sApiApiserverinternalV1alpha1StorageVersion) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApiApiserverinternalV1alpha1StorageVersion');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->apiVersion->set) {
            $result['apiVersion'] = $this->apiVersion->value;
        }
        $result['items'] = array_map(fn ($item) => $item->jsonSerialize(), $this->items);
        if ($this->kind->set) {
            $result['kind'] = $this->kind->value;
        }
        if ($this->metadata->set) {
            $result['metadata'] = $this->metadata->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            apiVersion: \array_key_exists('apiVersion', $data)
                ? OptString::some($data['apiVersion'])
                : OptString::none(),
            items: array_map(IoK8sApiApiserverinternalV1alpha1StorageVersion::fromArray(...), $data['items']),
            kind: \array_key_exists('kind', $data)
                ? OptString::some($data['kind'])
                : OptString::none(),
            metadata: \array_key_exists('metadata', $data)
                ? OptIoK8sApimachineryPkgApisMetaV1ListMeta::some(IoK8sApimachineryPkgApisMetaV1ListMeta::fromArray($data['metadata']))
                : OptIoK8sApimachineryPkgApisMetaV1ListMeta::none(),
        );
    }
}
