<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * NodeCondition contains condition information for a node.
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.NodeCondition
 */
final readonly class IoK8sApiCoreV1NodeCondition implements JsonSerializable
{
    public function __construct(
        public OptIoK8sApimachineryPkgApisMetaV1Time $lastHeartbeatTime,
        public OptIoK8sApimachineryPkgApisMetaV1Time $lastTransitionTime,
        public OptString $message,
        public OptString $reason,
        public string $status,
        public string $type,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->lastHeartbeatTime->set) {
            $result['lastHeartbeatTime'] = $this->lastHeartbeatTime->value;
        }
        if ($this->lastTransitionTime->set) {
            $result['lastTransitionTime'] = $this->lastTransitionTime->value;
        }
        if ($this->message->set) {
            $result['message'] = $this->message->value;
        }
        if ($this->reason->set) {
            $result['reason'] = $this->reason->value;
        }
        $result['status'] = $this->status;
        $result['type'] = $this->type;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            lastHeartbeatTime: \array_key_exists('lastHeartbeatTime', $data)
                ? OptIoK8sApimachineryPkgApisMetaV1Time::some($data['lastHeartbeatTime'])
                : OptIoK8sApimachineryPkgApisMetaV1Time::none(),
            lastTransitionTime: \array_key_exists('lastTransitionTime', $data)
                ? OptIoK8sApimachineryPkgApisMetaV1Time::some($data['lastTransitionTime'])
                : OptIoK8sApimachineryPkgApisMetaV1Time::none(),
            message: \array_key_exists('message', $data)
                ? OptString::some($data['message'])
                : OptString::none(),
            reason: \array_key_exists('reason', $data)
                ? OptString::some($data['reason'])
                : OptString::none(),
            status: $data['status'],
            type: $data['type'],
        );
    }
}
