<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * JobSpec describes how the job execution will look like.
 *
 * Ref: #/components/schemas/io.k8s.api.batch.v1.JobSpec
 */
final readonly class IoK8sApiBatchV1JobSpec implements JsonSerializable
{
    public function __construct(
        public OptInt64 $activeDeadlineSeconds,
        public OptInt32 $backoffLimit,
        public OptString $completionMode,
        public OptInt32 $completions,
        public OptBool $manualSelector,
        public OptInt32 $parallelism,
        public OptIoK8sApimachineryPkgApisMetaV1LabelSelector $selector,
        public OptBool $suspend,
        public IoK8sApiCoreV1PodTemplateSpec $template,
        public OptInt32 $ttlSecondsAfterFinished,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->activeDeadlineSeconds->set) {
            $result['activeDeadlineSeconds'] = $this->activeDeadlineSeconds->value;
        }
        if ($this->backoffLimit->set) {
            $result['backoffLimit'] = $this->backoffLimit->value;
        }
        if ($this->completionMode->set) {
            $result['completionMode'] = $this->completionMode->value;
        }
        if ($this->completions->set) {
            $result['completions'] = $this->completions->value;
        }
        if ($this->manualSelector->set) {
            $result['manualSelector'] = $this->manualSelector->value;
        }
        if ($this->parallelism->set) {
            $result['parallelism'] = $this->parallelism->value;
        }
        if ($this->selector->set) {
            $result['selector'] = $this->selector->value?->jsonSerialize();
        }
        if ($this->suspend->set) {
            $result['suspend'] = $this->suspend->value;
        }
        $result['template'] = $this->template->jsonSerialize();
        if ($this->ttlSecondsAfterFinished->set) {
            $result['ttlSecondsAfterFinished'] = $this->ttlSecondsAfterFinished->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            activeDeadlineSeconds: \array_key_exists('activeDeadlineSeconds', $data)
                ? OptInt64::some($data['activeDeadlineSeconds'])
                : OptInt64::none(),
            backoffLimit: \array_key_exists('backoffLimit', $data)
                ? OptInt32::some($data['backoffLimit'])
                : OptInt32::none(),
            completionMode: \array_key_exists('completionMode', $data)
                ? OptString::some($data['completionMode'])
                : OptString::none(),
            completions: \array_key_exists('completions', $data)
                ? OptInt32::some($data['completions'])
                : OptInt32::none(),
            manualSelector: \array_key_exists('manualSelector', $data)
                ? OptBool::some($data['manualSelector'])
                : OptBool::none(),
            parallelism: \array_key_exists('parallelism', $data)
                ? OptInt32::some($data['parallelism'])
                : OptInt32::none(),
            selector: \array_key_exists('selector', $data)
                ? OptIoK8sApimachineryPkgApisMetaV1LabelSelector::some(IoK8sApimachineryPkgApisMetaV1LabelSelector::fromArray($data['selector']))
                : OptIoK8sApimachineryPkgApisMetaV1LabelSelector::none(),
            suspend: \array_key_exists('suspend', $data)
                ? OptBool::some($data['suspend'])
                : OptBool::none(),
            template: IoK8sApiCoreV1PodTemplateSpec::fromArray($data['template']),
            ttlSecondsAfterFinished: \array_key_exists('ttlSecondsAfterFinished', $data)
                ? OptInt32::some($data['ttlSecondsAfterFinished'])
                : OptInt32::none(),
        );
    }
}
