<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * OwnerReference contains enough information to let you identify an owning object. An owning object
 * must be in the same namespace as the dependent, or be cluster-scoped, so there is no namespace
 * field.
 *
 * Ref: #/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
 */
final readonly class IoK8sApimachineryPkgApisMetaV1OwnerReference implements JsonSerializable
{
    public function __construct(
        public string $apiVersion,
        public OptBool $blockOwnerDeletion,
        public OptBool $controller,
        public string $kind,
        public string $name,
        public string $uid,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['apiVersion'] = $this->apiVersion;
        if ($this->blockOwnerDeletion->set) {
            $result['blockOwnerDeletion'] = $this->blockOwnerDeletion->value;
        }
        if ($this->controller->set) {
            $result['controller'] = $this->controller->value;
        }
        $result['kind'] = $this->kind;
        $result['name'] = $this->name;
        $result['uid'] = $this->uid;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            apiVersion: $data['apiVersion'],
            blockOwnerDeletion: \array_key_exists('blockOwnerDeletion', $data)
                ? OptBool::some($data['blockOwnerDeletion'])
                : OptBool::none(),
            controller: \array_key_exists('controller', $data)
                ? OptBool::some($data['controller'])
                : OptBool::none(),
            kind: $data['kind'],
            name: $data['name'],
            uid: $data['uid'],
        );
    }
}
