<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * An EphemeralContainer is a container that may be added temporarily to an existing pod for
 * user-initiated activities such as debugging. Ephemeral containers have no resource or scheduling
 * guarantees, and they will not be restarted when they exit or when a pod is removed or restarted.
 * If an ephemeral container causes a pod to exceed its resource allocation, the pod may be evicted.
 * Ephemeral containers may not be added by directly updating the pod spec. They must be added via
 * the pod's ephemeralcontainers subresource, and they will appear in the pod spec once added. This
 * is an alpha feature enabled by the EphemeralContainers feature flag.
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.EphemeralContainer
 */
final readonly class IoK8sApiCoreV1EphemeralContainer implements JsonSerializable
{
    public function __construct(
        /** @var string[] */
        public array $args,
        /** @var string[] */
        public array $command,
        /** @var IoK8sApiCoreV1EnvVar[] */
        public array $env,
        /** @var IoK8sApiCoreV1EnvFromSource[] */
        public array $envFrom,
        public OptString $image,
        public OptString $imagePullPolicy,
        public OptIoK8sApiCoreV1Lifecycle $lifecycle,
        public OptIoK8sApiCoreV1Probe $livenessProbe,
        public string $name,
        /** @var IoK8sApiCoreV1ContainerPort[] */
        public array $ports,
        public OptIoK8sApiCoreV1Probe $readinessProbe,
        public OptIoK8sApiCoreV1ResourceRequirements $resources,
        public OptIoK8sApiCoreV1SecurityContext $securityContext,
        public OptIoK8sApiCoreV1Probe $startupProbe,
        public OptBool $stdin,
        public OptBool $stdinOnce,
        public OptString $targetContainerName,
        public OptString $terminationMessagePath,
        public OptString $terminationMessagePolicy,
        public OptBool $tty,
        /** @var IoK8sApiCoreV1VolumeDevice[] */
        public array $volumeDevices,
        /** @var IoK8sApiCoreV1VolumeMount[] */
        public array $volumeMounts,
        public OptString $workingDir,
    ) {
        foreach ($this->args as $item) {
            if (!is_string($item)) {
                throw new \InvalidArgumentException('Expected string');
            }
        }
        foreach ($this->command as $item) {
            if (!is_string($item)) {
                throw new \InvalidArgumentException('Expected string');
            }
        }
        foreach ($this->env as $item) {
            if (!$item instanceof IoK8sApiCoreV1EnvVar) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApiCoreV1EnvVar');
            }
        }
        foreach ($this->envFrom as $item) {
            if (!$item instanceof IoK8sApiCoreV1EnvFromSource) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApiCoreV1EnvFromSource');
            }
        }
        foreach ($this->ports as $item) {
            if (!$item instanceof IoK8sApiCoreV1ContainerPort) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApiCoreV1ContainerPort');
            }
        }
        foreach ($this->volumeDevices as $item) {
            if (!$item instanceof IoK8sApiCoreV1VolumeDevice) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApiCoreV1VolumeDevice');
            }
        }
        foreach ($this->volumeMounts as $item) {
            if (!$item instanceof IoK8sApiCoreV1VolumeMount) {
                throw new \InvalidArgumentException('Expected instance of IoK8sApiCoreV1VolumeMount');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['args'] = $this->args;
        $result['command'] = $this->command;
        $result['env'] = array_map(fn ($item) => $item->jsonSerialize(), $this->env);
        $result['envFrom'] = array_map(fn ($item) => $item->jsonSerialize(), $this->envFrom);
        if ($this->image->set) {
            $result['image'] = $this->image->value;
        }
        if ($this->imagePullPolicy->set) {
            $result['imagePullPolicy'] = $this->imagePullPolicy->value;
        }
        if ($this->lifecycle->set) {
            $result['lifecycle'] = $this->lifecycle->value?->jsonSerialize();
        }
        if ($this->livenessProbe->set) {
            $result['livenessProbe'] = $this->livenessProbe->value?->jsonSerialize();
        }
        $result['name'] = $this->name;
        $result['ports'] = array_map(fn ($item) => $item->jsonSerialize(), $this->ports);
        if ($this->readinessProbe->set) {
            $result['readinessProbe'] = $this->readinessProbe->value?->jsonSerialize();
        }
        if ($this->resources->set) {
            $result['resources'] = $this->resources->value?->jsonSerialize();
        }
        if ($this->securityContext->set) {
            $result['securityContext'] = $this->securityContext->value?->jsonSerialize();
        }
        if ($this->startupProbe->set) {
            $result['startupProbe'] = $this->startupProbe->value?->jsonSerialize();
        }
        if ($this->stdin->set) {
            $result['stdin'] = $this->stdin->value;
        }
        if ($this->stdinOnce->set) {
            $result['stdinOnce'] = $this->stdinOnce->value;
        }
        if ($this->targetContainerName->set) {
            $result['targetContainerName'] = $this->targetContainerName->value;
        }
        if ($this->terminationMessagePath->set) {
            $result['terminationMessagePath'] = $this->terminationMessagePath->value;
        }
        if ($this->terminationMessagePolicy->set) {
            $result['terminationMessagePolicy'] = $this->terminationMessagePolicy->value;
        }
        if ($this->tty->set) {
            $result['tty'] = $this->tty->value;
        }
        $result['volumeDevices'] = array_map(fn ($item) => $item->jsonSerialize(), $this->volumeDevices);
        $result['volumeMounts'] = array_map(fn ($item) => $item->jsonSerialize(), $this->volumeMounts);
        if ($this->workingDir->set) {
            $result['workingDir'] = $this->workingDir->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            args: $data['args'],
            command: $data['command'],
            env: array_map(IoK8sApiCoreV1EnvVar::fromArray(...), $data['env']),
            envFrom: array_map(IoK8sApiCoreV1EnvFromSource::fromArray(...), $data['envFrom']),
            image: \array_key_exists('image', $data)
                ? OptString::some($data['image'])
                : OptString::none(),
            imagePullPolicy: \array_key_exists('imagePullPolicy', $data)
                ? OptString::some($data['imagePullPolicy'])
                : OptString::none(),
            lifecycle: \array_key_exists('lifecycle', $data)
                ? OptIoK8sApiCoreV1Lifecycle::some(IoK8sApiCoreV1Lifecycle::fromArray($data['lifecycle']))
                : OptIoK8sApiCoreV1Lifecycle::none(),
            livenessProbe: \array_key_exists('livenessProbe', $data)
                ? OptIoK8sApiCoreV1Probe::some(IoK8sApiCoreV1Probe::fromArray($data['livenessProbe']))
                : OptIoK8sApiCoreV1Probe::none(),
            name: $data['name'],
            ports: array_map(IoK8sApiCoreV1ContainerPort::fromArray(...), $data['ports']),
            readinessProbe: \array_key_exists('readinessProbe', $data)
                ? OptIoK8sApiCoreV1Probe::some(IoK8sApiCoreV1Probe::fromArray($data['readinessProbe']))
                : OptIoK8sApiCoreV1Probe::none(),
            resources: \array_key_exists('resources', $data)
                ? OptIoK8sApiCoreV1ResourceRequirements::some(IoK8sApiCoreV1ResourceRequirements::fromArray($data['resources']))
                : OptIoK8sApiCoreV1ResourceRequirements::none(),
            securityContext: \array_key_exists('securityContext', $data)
                ? OptIoK8sApiCoreV1SecurityContext::some(IoK8sApiCoreV1SecurityContext::fromArray($data['securityContext']))
                : OptIoK8sApiCoreV1SecurityContext::none(),
            startupProbe: \array_key_exists('startupProbe', $data)
                ? OptIoK8sApiCoreV1Probe::some(IoK8sApiCoreV1Probe::fromArray($data['startupProbe']))
                : OptIoK8sApiCoreV1Probe::none(),
            stdin: \array_key_exists('stdin', $data)
                ? OptBool::some($data['stdin'])
                : OptBool::none(),
            stdinOnce: \array_key_exists('stdinOnce', $data)
                ? OptBool::some($data['stdinOnce'])
                : OptBool::none(),
            targetContainerName: \array_key_exists('targetContainerName', $data)
                ? OptString::some($data['targetContainerName'])
                : OptString::none(),
            terminationMessagePath: \array_key_exists('terminationMessagePath', $data)
                ? OptString::some($data['terminationMessagePath'])
                : OptString::none(),
            terminationMessagePolicy: \array_key_exists('terminationMessagePolicy', $data)
                ? OptString::some($data['terminationMessagePolicy'])
                : OptString::none(),
            tty: \array_key_exists('tty', $data)
                ? OptBool::some($data['tty'])
                : OptBool::none(),
            volumeDevices: array_map(IoK8sApiCoreV1VolumeDevice::fromArray(...), $data['volumeDevices']),
            volumeMounts: array_map(IoK8sApiCoreV1VolumeMount::fromArray(...), $data['volumeMounts']),
            workingDir: \array_key_exists('workingDir', $data)
                ? OptString::some($data['workingDir'])
                : OptString::none(),
        );
    }
}
