<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * PodsMetricStatus indicates the current value of a metric describing each pod in the current scale
 * target (for example, transactions-processed-per-second).
 *
 * Ref: #/components/schemas/io.k8s.api.autoscaling.v2beta2.PodsMetricStatus
 */
final readonly class IoK8sApiAutoscalingV2beta2PodsMetricStatus implements JsonSerializable
{
    public function __construct(
        public IoK8sApiAutoscalingV2beta2MetricValueStatus $current,
        public IoK8sApiAutoscalingV2beta2MetricIdentifier $metric,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['current'] = $this->current->jsonSerialize();
        $result['metric'] = $this->metric->jsonSerialize();

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            current: IoK8sApiAutoscalingV2beta2MetricValueStatus::fromArray($data['current']),
            metric: IoK8sApiAutoscalingV2beta2MetricIdentifier::fromArray($data['metric']),
        );
    }
}
