<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Affinity is a group of affinity scheduling rules.
 *
 * Ref: #/components/schemas/io.k8s.api.core.v1.Affinity
 */
final readonly class IoK8sApiCoreV1Affinity implements JsonSerializable
{
    public function __construct(
        public OptIoK8sApiCoreV1NodeAffinity $nodeAffinity,
        public OptIoK8sApiCoreV1PodAffinity $podAffinity,
        public OptIoK8sApiCoreV1PodAntiAffinity $podAntiAffinity,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->nodeAffinity->set) {
            $result['nodeAffinity'] = $this->nodeAffinity->value?->jsonSerialize();
        }
        if ($this->podAffinity->set) {
            $result['podAffinity'] = $this->podAffinity->value?->jsonSerialize();
        }
        if ($this->podAntiAffinity->set) {
            $result['podAntiAffinity'] = $this->podAntiAffinity->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            nodeAffinity: \array_key_exists('nodeAffinity', $data)
                ? OptIoK8sApiCoreV1NodeAffinity::some(IoK8sApiCoreV1NodeAffinity::fromArray($data['nodeAffinity']))
                : OptIoK8sApiCoreV1NodeAffinity::none(),
            podAffinity: \array_key_exists('podAffinity', $data)
                ? OptIoK8sApiCoreV1PodAffinity::some(IoK8sApiCoreV1PodAffinity::fromArray($data['podAffinity']))
                : OptIoK8sApiCoreV1PodAffinity::none(),
            podAntiAffinity: \array_key_exists('podAntiAffinity', $data)
                ? OptIoK8sApiCoreV1PodAntiAffinity::some(IoK8sApiCoreV1PodAntiAffinity::fromArray($data['podAntiAffinity']))
                : OptIoK8sApiCoreV1PodAntiAffinity::none(),
        );
    }
}
