<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * OptIoK8sApiCoreV1ServiceAccountTokenProjection is optional IoK8sApiCoreV1ServiceAccountTokenProjection.
 */
final readonly class OptIoK8sApiCoreV1ServiceAccountTokenProjection
{
    public function __construct(
        public ?IoK8sApiCoreV1ServiceAccountTokenProjection $value,
        public bool $set,
    ) {}

    /**
     * Create an unset optional.
     */
    public static function none(): self
    {
        return new self(null, false);
    }

    /**
     * Create a set optional with the given value.
     */
    public static function some(IoK8sApiCoreV1ServiceAccountTokenProjection $value): self
    {
        return new self($value, true);
    }
}
