<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * OptIoK8sApiAutoscalingV2beta1ExternalMetricStatus is optional IoK8sApiAutoscalingV2beta1ExternalMetricStatus.
 */
final readonly class OptIoK8sApiAutoscalingV2beta1ExternalMetricStatus
{
    public function __construct(
        public ?IoK8sApiAutoscalingV2beta1ExternalMetricStatus $value,
        public bool $set,
    ) {}

    /**
     * Create an unset optional.
     */
    public static function none(): self
    {
        return new self(null, false);
    }

    /**
     * Create a set optional with the given value.
     */
    public static function some(IoK8sApiAutoscalingV2beta1ExternalMetricStatus $value): self
    {
        return new self($value, true);
    }
}
