<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * OptIoK8sApiAppsV1StatefulSetSpec is optional IoK8sApiAppsV1StatefulSetSpec.
 */
final readonly class OptIoK8sApiAppsV1StatefulSetSpec
{
    public function __construct(
        public ?IoK8sApiAppsV1StatefulSetSpec $value,
        public bool $set,
    ) {}

    /**
     * Create an unset optional.
     */
    public static function none(): self
    {
        return new self(null, false);
    }

    /**
     * Create a set optional with the given value.
     */
    public static function some(IoK8sApiAppsV1StatefulSetSpec $value): self
    {
        return new self($value, true);
    }
}
