<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * OptIoK8sKubeAggregatorPkgApisApiregistrationV1ServiceReference is optional IoK8sKubeAggregatorPkgApisApiregistrationV1ServiceReference.
 */
final readonly class OptIoK8sKubeAggregatorPkgApisApiregistrationV1ServiceReference
{
    public function __construct(
        public ?IoK8sKubeAggregatorPkgApisApiregistrationV1ServiceReference $value,
        public bool $set,
    ) {}

    /**
     * Create an unset optional.
     */
    public static function none(): self
    {
        return new self(null, false);
    }

    /**
     * Create a set optional with the given value.
     */
    public static function some(IoK8sKubeAggregatorPkgApisApiregistrationV1ServiceReference $value): self
    {
        return new self($value, true);
    }
}
