<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated Params DTO from OpenAPI specification.
 */
final readonly class WatchBatchV1NamespacedCronJobParams
{
    public function __construct(
        public OptBool $allowWatchBookmarks,
        public OptString $continue,
        public OptString $fieldSelector,
        public OptString $labelSelector,
        public OptInt $limit,
        public OptString $pretty,
        public OptString $resourceVersion,
        public OptString $resourceVersionMatch,
        public OptInt $timeoutSeconds,
        public OptBool $watch,
    ) {}

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            allowWatchBookmarks: \array_key_exists('allowWatchBookmarks', $data)
                ? OptBool::some($data['allowWatchBookmarks'])
                : OptBool::none(),
            continue: \array_key_exists('continue', $data)
                ? OptString::some($data['continue'])
                : OptString::none(),
            fieldSelector: \array_key_exists('fieldSelector', $data)
                ? OptString::some($data['fieldSelector'])
                : OptString::none(),
            labelSelector: \array_key_exists('labelSelector', $data)
                ? OptString::some($data['labelSelector'])
                : OptString::none(),
            limit: \array_key_exists('limit', $data)
                ? OptInt::some($data['limit'])
                : OptInt::none(),
            pretty: \array_key_exists('pretty', $data)
                ? OptString::some($data['pretty'])
                : OptString::none(),
            resourceVersion: \array_key_exists('resourceVersion', $data)
                ? OptString::some($data['resourceVersion'])
                : OptString::none(),
            resourceVersionMatch: \array_key_exists('resourceVersionMatch', $data)
                ? OptString::some($data['resourceVersionMatch'])
                : OptString::none(),
            timeoutSeconds: \array_key_exists('timeoutSeconds', $data)
                ? OptInt::some($data['timeoutSeconds'])
                : OptInt::none(),
            watch: \array_key_exists('watch', $data)
                ? OptBool::some($data['watch'])
                : OptBool::none(),
        );
    }
}
