<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 */
final readonly class ListPetCategoriesOKApplicationJson implements JsonSerializable
{
    /**
     * @param PetCategoriesList[] $items
     */
    public function __construct(
        public array $items,
    ) {
        foreach ($this->items as $item) {
            if (!$item instanceof PetCategoriesList) {
                throw new \InvalidArgumentException('Expected instance of PetCategoriesList');
            }
        }
    }

    /**
     * @return array<int, mixed>
     */
    public function jsonSerialize(): array
    {
        return array_map(fn (PetCategoriesList $item) => $item->jsonSerialize(), $this->items);
    }

    /**
     * @param array<int, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(array_map(PetCategoriesList::fromArray(...), $data));
    }
}
