<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\AnswerShippingQueryRequest;
use App\Http\Responses\OpenApi\AnswerShippingQueryResponse;
use App\Http\Responses\OpenApi\ErrorResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class AnswerShippingQueryController extends Controller
{
    /**
     * POST /answerShippingQuery
     */
    abstract public function answerShippingQuery(
        AnswerShippingQueryRequest $request,
    ): AnswerShippingQueryResponse|ErrorResponse;
}
