<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\AnswerWebAppQueryRequest;
use App\Http\Responses\OpenApi\AnswerWebAppQueryResponse;
use App\Http\Responses\OpenApi\ErrorResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class AnswerWebAppQueryController extends Controller
{
    /**
     * POST /answerWebAppQuery
     */
    abstract public function answerWebAppQuery(
        AnswerWebAppQueryRequest $request,
    ): AnswerWebAppQueryResponse|ErrorResponse;
}
