<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\EditMessageMediaRequest;
use App\Http\Responses\OpenApi\EditMessageMediaResponse;
use App\Http\Responses\OpenApi\ErrorResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class EditMessageMediumController extends Controller
{
    /**
     * POST /editMessageMedia
     */
    abstract public function editMessageMedia(
        EditMessageMediaRequest $request,
    ): EditMessageMediaResponse|ErrorResponse;
}
