<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\ForwardMessageRequest;
use App\Http\Responses\OpenApi\ForwardMessageResponse;
use App\Http\Responses\OpenApi\ErrorResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class ForwardMessageController extends Controller
{
    /**
     * POST /forwardMessage
     */
    abstract public function forwardMessage(
        ForwardMessageRequest $request,
    ): ForwardMessageResponse|ErrorResponse;
}
