<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\SendVideoNoteRequest;
use App\Http\Responses\OpenApi\SendVideoNoteResponse;
use App\Http\Responses\OpenApi\ErrorResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class SendVideoNoteController extends Controller
{
    /**
     * POST /sendVideoNote
     */
    abstract public function sendVideoNote(
        SendVideoNoteRequest $request,
    ): SendVideoNoteResponse|ErrorResponse;
}
