<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\SendInvoiceRequest;
use App\Http\Responses\OpenApi\SendInvoiceResponse;
use App\Http\Responses\OpenApi\ErrorResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class SendInvoiceController extends Controller
{
    /**
     * POST /sendInvoice
     */
    abstract public function sendInvoice(
        SendInvoiceRequest $request,
    ): SendInvoiceResponse|ErrorResponse;
}
