<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * Auto-generated enum from OpenAPI specification.
 * Type of chat, can be either “private”, “group”, “supergroup” or “channel”.
 */
enum ChatType: string
{
    case ChatTypePrivate = 'private';
    case ChatTypeGroup = 'group';
    case ChatTypeSupergroup = 'supergroup';
    case ChatTypeChannel = 'channel';
}
