<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Describes actions that a non-administrator user is allowed to take in a chat.
 *
 * Ref: #/components/schemas/ChatPermissions
 */
final readonly class ChatPermissions implements JsonSerializable
{
    public function __construct(
        public OptBool $canSendMessages,
        public OptBool $canSendMediaMessages,
        public OptBool $canSendPolls,
        public OptBool $canSendOtherMessages,
        public OptBool $canAddWebPagePreviews,
        public OptBool $canChangeInfo,
        public OptBool $canInviteUsers,
        public OptBool $canPinMessages,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->canSendMessages->set) {
            $result['can_send_messages'] = $this->canSendMessages->value;
        }
        if ($this->canSendMediaMessages->set) {
            $result['can_send_media_messages'] = $this->canSendMediaMessages->value;
        }
        if ($this->canSendPolls->set) {
            $result['can_send_polls'] = $this->canSendPolls->value;
        }
        if ($this->canSendOtherMessages->set) {
            $result['can_send_other_messages'] = $this->canSendOtherMessages->value;
        }
        if ($this->canAddWebPagePreviews->set) {
            $result['can_add_web_page_previews'] = $this->canAddWebPagePreviews->value;
        }
        if ($this->canChangeInfo->set) {
            $result['can_change_info'] = $this->canChangeInfo->value;
        }
        if ($this->canInviteUsers->set) {
            $result['can_invite_users'] = $this->canInviteUsers->value;
        }
        if ($this->canPinMessages->set) {
            $result['can_pin_messages'] = $this->canPinMessages->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            canSendMessages: \array_key_exists('can_send_messages', $data)
                ? OptBool::some($data['can_send_messages'])
                : OptBool::none(),
            canSendMediaMessages: \array_key_exists('can_send_media_messages', $data)
                ? OptBool::some($data['can_send_media_messages'])
                : OptBool::none(),
            canSendPolls: \array_key_exists('can_send_polls', $data)
                ? OptBool::some($data['can_send_polls'])
                : OptBool::none(),
            canSendOtherMessages: \array_key_exists('can_send_other_messages', $data)
                ? OptBool::some($data['can_send_other_messages'])
                : OptBool::none(),
            canAddWebPagePreviews: \array_key_exists('can_add_web_page_previews', $data)
                ? OptBool::some($data['can_add_web_page_previews'])
                : OptBool::none(),
            canChangeInfo: \array_key_exists('can_change_info', $data)
                ? OptBool::some($data['can_change_info'])
                : OptBool::none(),
            canInviteUsers: \array_key_exists('can_invite_users', $data)
                ? OptBool::some($data['can_invite_users'])
                : OptBool::none(),
            canPinMessages: \array_key_exists('can_pin_messages', $data)
                ? OptBool::some($data['can_pin_messages'])
                : OptBool::none(),
        );
    }
}
