<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Input for editMessageText.
 *
 * Ref: #/components/schemas/editMessageText
 */
final readonly class EditMessageText implements JsonSerializable
{
    public function __construct(
        public OptID $chatId,
        public OptInt $messageId,
        public OptString $inlineMessageId,
        public string $text,
        public OptString $parseMode,
        /** @var MessageEntity[] */
        public array $entities,
        public OptBool $disableWebPagePreview,
        public OptInlineKeyboardMarkup $replyMarkup,
    ) {
        foreach ($this->entities as $item) {
            if (!$item instanceof MessageEntity) {
                throw new \InvalidArgumentException('Expected instance of MessageEntity');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->chatId->set) {
            $result['chat_id'] = $this->chatId->value;
        }
        if ($this->messageId->set) {
            $result['message_id'] = $this->messageId->value;
        }
        if ($this->inlineMessageId->set) {
            $result['inline_message_id'] = $this->inlineMessageId->value;
        }
        $result['text'] = $this->text;
        if ($this->parseMode->set) {
            $result['parse_mode'] = $this->parseMode->value;
        }
        $result['entities'] = array_map(fn ($item) => $item->jsonSerialize(), $this->entities);
        if ($this->disableWebPagePreview->set) {
            $result['disable_web_page_preview'] = $this->disableWebPagePreview->value;
        }
        if ($this->replyMarkup->set) {
            $result['reply_markup'] = $this->replyMarkup->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            chatId: \array_key_exists('chat_id', $data)
                ? OptID::some($data['chat_id'])
                : OptID::none(),
            messageId: \array_key_exists('message_id', $data)
                ? OptInt::some($data['message_id'])
                : OptInt::none(),
            inlineMessageId: \array_key_exists('inline_message_id', $data)
                ? OptString::some($data['inline_message_id'])
                : OptString::none(),
            text: $data['text'],
            parseMode: \array_key_exists('parse_mode', $data)
                ? OptString::some($data['parse_mode'])
                : OptString::none(),
            entities: array_map(MessageEntity::fromArray(...), $data['entities']),
            disableWebPagePreview: \array_key_exists('disable_web_page_preview', $data)
                ? OptBool::some($data['disable_web_page_preview'])
                : OptBool::none(),
            replyMarkup: \array_key_exists('reply_markup', $data)
                ? OptInlineKeyboardMarkup::some(InlineKeyboardMarkup::fromArray($data['reply_markup']))
                : OptInlineKeyboardMarkup::none(),
        );
    }
}
