<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Upon receiving a message with this object, Telegram clients will display a reply interface to the
 * user (act as if the user has selected the bot's message and tapped 'Reply'). This can be extremely
 * useful if you want to create user-friendly step-by-step interfaces without having to sacrifice
 * privacy mode.
 *
 * Ref: #/components/schemas/ForceReply
 */
final readonly class ForceReply implements JsonSerializable
{
    public function __construct(
        public bool $forceReply,
        public OptString $inputFieldPlaceholder,
        public OptBool $selective,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['force_reply'] = $this->forceReply;
        if ($this->inputFieldPlaceholder->set) {
            $result['input_field_placeholder'] = $this->inputFieldPlaceholder->value;
        }
        if ($this->selective->set) {
            $result['selective'] = $this->selective->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            forceReply: $data['force_reply'],
            inputFieldPlaceholder: \array_key_exists('input_field_placeholder', $data)
                ? OptString::some($data['input_field_placeholder'])
                : OptString::none(),
            selective: \array_key_exists('selective', $data)
                ? OptBool::some($data['selective'])
                : OptBool::none(),
        );
    }
}
