<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Represents a link to an article or web page.
 *
 * Ref: #/components/schemas/InlineQueryResultArticle
 */
final readonly class InlineQueryResultArticle implements JsonSerializable
{
    public function __construct(
        public string $type,
        public string $id,
        public string $title,
        public InputTextMessageContent|InputLocationMessageContent|InputVenueMessageContent|InputContactMessageContent|InputInvoiceMessageContent $inputMessageContent,
        public OptInlineKeyboardMarkup $replyMarkup,
        public OptURI $url,
        public OptBool $hideUrl,
        public OptString $description,
        public OptURI $thumbUrl,
        public OptInt $thumbWidth,
        public OptInt $thumbHeight,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['type'] = $this->type;
        $result['id'] = $this->id;
        $result['title'] = $this->title;
        $result['input_message_content'] = $this->inputMessageContent;
        if ($this->replyMarkup->set) {
            $result['reply_markup'] = $this->replyMarkup->value?->jsonSerialize();
        }
        if ($this->url->set) {
            $result['url'] = $this->url->value;
        }
        if ($this->hideUrl->set) {
            $result['hide_url'] = $this->hideUrl->value;
        }
        if ($this->description->set) {
            $result['description'] = $this->description->value;
        }
        if ($this->thumbUrl->set) {
            $result['thumb_url'] = $this->thumbUrl->value;
        }
        if ($this->thumbWidth->set) {
            $result['thumb_width'] = $this->thumbWidth->value;
        }
        if ($this->thumbHeight->set) {
            $result['thumb_height'] = $this->thumbHeight->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            type: $data['type'],
            id: $data['id'],
            title: $data['title'],
            inputMessageContent: $data['input_message_content'],
            replyMarkup: \array_key_exists('reply_markup', $data)
                ? OptInlineKeyboardMarkup::some(InlineKeyboardMarkup::fromArray($data['reply_markup']))
                : OptInlineKeyboardMarkup::none(),
            url: \array_key_exists('url', $data)
                ? OptURI::some($data['url'])
                : OptURI::none(),
            hideUrl: \array_key_exists('hide_url', $data)
                ? OptBool::some($data['hide_url'])
                : OptBool::none(),
            description: \array_key_exists('description', $data)
                ? OptString::some($data['description'])
                : OptString::none(),
            thumbUrl: \array_key_exists('thumb_url', $data)
                ? OptURI::some($data['thumb_url'])
                : OptURI::none(),
            thumbWidth: \array_key_exists('thumb_width', $data)
                ? OptInt::some($data['thumb_width'])
                : OptInt::none(),
            thumbHeight: \array_key_exists('thumb_height', $data)
                ? OptInt::some($data['thumb_height'])
                : OptInt::none(),
        );
    }
}
