<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Represents a link to a voice message stored on the Telegram servers. By default, this voice
 * message will be sent by the user. Alternatively, you can use input_message_content to send a
 * message with the specified content instead of the voice message.
 *
 * Ref: #/components/schemas/InlineQueryResultCachedVoice
 */
final readonly class InlineQueryResultCachedVoice implements JsonSerializable
{
    public function __construct(
        public string $type,
        public string $id,
        public string $voiceFileId,
        public string $title,
        public OptString $caption,
        public OptString $parseMode,
        /** @var MessageEntity[] */
        public array $captionEntities,
        public OptInlineKeyboardMarkup $replyMarkup,
        public OptInputMessageContent $inputMessageContent,
    ) {
        foreach ($this->captionEntities as $item) {
            if (!$item instanceof MessageEntity) {
                throw new \InvalidArgumentException('Expected instance of MessageEntity');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['type'] = $this->type;
        $result['id'] = $this->id;
        $result['voice_file_id'] = $this->voiceFileId;
        $result['title'] = $this->title;
        if ($this->caption->set) {
            $result['caption'] = $this->caption->value;
        }
        if ($this->parseMode->set) {
            $result['parse_mode'] = $this->parseMode->value;
        }
        $result['caption_entities'] = array_map(fn ($item) => $item->jsonSerialize(), $this->captionEntities);
        if ($this->replyMarkup->set) {
            $result['reply_markup'] = $this->replyMarkup->value?->jsonSerialize();
        }
        if ($this->inputMessageContent->set) {
            $result['input_message_content'] = $this->inputMessageContent->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            type: $data['type'],
            id: $data['id'],
            voiceFileId: $data['voice_file_id'],
            title: $data['title'],
            caption: \array_key_exists('caption', $data)
                ? OptString::some($data['caption'])
                : OptString::none(),
            parseMode: \array_key_exists('parse_mode', $data)
                ? OptString::some($data['parse_mode'])
                : OptString::none(),
            captionEntities: array_map(MessageEntity::fromArray(...), $data['caption_entities']),
            replyMarkup: \array_key_exists('reply_markup', $data)
                ? OptInlineKeyboardMarkup::some(InlineKeyboardMarkup::fromArray($data['reply_markup']))
                : OptInlineKeyboardMarkup::none(),
            inputMessageContent: \array_key_exists('input_message_content', $data)
                ? OptInputMessageContent::some($data['input_message_content'])
                : OptInputMessageContent::none(),
        );
    }
}
