<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

/**
 * OptVoiceChatScheduled is optional VoiceChatScheduled.
 */
final readonly class OptVoiceChatScheduled
{
    public function __construct(
        public ?VoiceChatScheduled $value,
        public bool $set,
    ) {}

    /**
     * Create an unset optional.
     */
    public static function none(): self
    {
        return new self(null, false);
    }

    /**
     * Create a set optional with the given value.
     */
    public static function some(VoiceChatScheduled $value): self
    {
        return new self($value, true);
    }
}
