<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * This object represents information about an order.
 *
 * Ref: #/components/schemas/OrderInfo
 */
final readonly class OrderInfo implements JsonSerializable
{
    public function __construct(
        public OptString $name,
        public OptString $phoneNumber,
        public OptString $email,
        public OptShippingAddress $shippingAddress,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->name->set) {
            $result['name'] = $this->name->value;
        }
        if ($this->phoneNumber->set) {
            $result['phone_number'] = $this->phoneNumber->value;
        }
        if ($this->email->set) {
            $result['email'] = $this->email->value;
        }
        if ($this->shippingAddress->set) {
            $result['shipping_address'] = $this->shippingAddress->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            name: \array_key_exists('name', $data)
                ? OptString::some($data['name'])
                : OptString::none(),
            phoneNumber: \array_key_exists('phone_number', $data)
                ? OptString::some($data['phone_number'])
                : OptString::none(),
            email: \array_key_exists('email', $data)
                ? OptString::some($data['email'])
                : OptString::none(),
            shippingAddress: \array_key_exists('shipping_address', $data)
                ? OptShippingAddress::some(ShippingAddress::fromArray($data['shipping_address']))
                : OptShippingAddress::none(),
        );
    }
}
