<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Contains information about Telegram Passport data shared with the bot by the user.
 *
 * Ref: #/components/schemas/PassportData
 */
final readonly class PassportData implements JsonSerializable
{
    public function __construct(
        /** @var EncryptedPassportElement[] */
        public array $data,
        public EncryptedCredentials $credentials,
    ) {
        foreach ($this->data as $item) {
            if (!$item instanceof EncryptedPassportElement) {
                throw new \InvalidArgumentException('Expected instance of EncryptedPassportElement');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['data'] = array_map(fn ($item) => $item->jsonSerialize(), $this->data);
        $result['credentials'] = $this->credentials->jsonSerialize();

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            data: array_map(EncryptedPassportElement::fromArray(...), $data['data']),
            credentials: EncryptedCredentials::fromArray($data['credentials']),
        );
    }
}
