<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Upon receiving a message with this object, Telegram clients will remove the current custom
 * keyboard and display the default letter-keyboard. By default, custom keyboards are displayed until
 * a new keyboard is sent by a bot. An exception is made for one-time keyboards that are hidden
 * immediately after the user presses a button (see ReplyKeyboardMarkup).
 *
 * Ref: #/components/schemas/ReplyKeyboardRemove
 */
final readonly class ReplyKeyboardRemove implements JsonSerializable
{
    public function __construct(
        public bool $removeKeyboard,
        public OptBool $selective,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['remove_keyboard'] = $this->removeKeyboard;
        if ($this->selective->set) {
            $result['selective'] = $this->selective->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            removeKeyboard: $data['remove_keyboard'],
            selective: \array_key_exists('selective', $data)
                ? OptBool::some($data['selective'])
                : OptBool::none(),
        );
    }
}
