<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 *
 * Ref: #/components/schemas/ResultArrayOfUpdate
 */
final readonly class ResultArrayOfUpdate implements JsonSerializable
{
    public function __construct(
        /** @var Update[] */
        public array $result,
        public bool $ok,
    ) {
        foreach ($this->result as $item) {
            if (!$item instanceof Update) {
                throw new \InvalidArgumentException('Expected instance of Update');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['result'] = array_map(fn ($item) => $item->jsonSerialize(), $this->result);
        $result['ok'] = $this->ok;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            result: array_map(Update::fromArray(...), $data['result']),
            ok: $data['ok'],
        );
    }
}
