<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 *
 * Ref: #/components/schemas/ResultUser
 */
final readonly class ResultUser implements JsonSerializable
{
    public function __construct(
        public OptUser $result,
        public bool $ok,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->result->set) {
            $result['result'] = $this->result->value?->jsonSerialize();
        }
        $result['ok'] = $this->ok;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            result: \array_key_exists('result', $data)
                ? OptUser::some(User::fromArray($data['result']))
                : OptUser::none(),
            ok: $data['ok'],
        );
    }
}
