<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Input for sendChatAction.
 *
 * Ref: #/components/schemas/sendChatAction
 */
final readonly class SendChatAction implements JsonSerializable
{
    public function __construct(
        public string|int $chatId,
        public string $action,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['chat_id'] = $this->chatId;
        $result['action'] = $this->action;

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            chatId: $data['chat_id'],
            action: $data['action'],
        );
    }
}
