<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * Input for setWebhook.
 *
 * Ref: #/components/schemas/setWebhook
 */
final readonly class SetWebhook implements JsonSerializable
{
    public function __construct(
        public string $url,
        public OptString $certificate,
        public OptString $ipAddress,
        public OptInt $maxConnections,
        /** @var string[] */
        public array $allowedUpdates,
        public OptBool $dropPendingUpdates,
    ) {
        foreach ($this->allowedUpdates as $item) {
            if (!is_string($item)) {
                throw new \InvalidArgumentException('Expected string');
            }
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['url'] = $this->url;
        if ($this->certificate->set) {
            $result['certificate'] = $this->certificate->value;
        }
        if ($this->ipAddress->set) {
            $result['ip_address'] = $this->ipAddress->value;
        }
        if ($this->maxConnections->set) {
            $result['max_connections'] = $this->maxConnections->value;
        }
        $result['allowed_updates'] = $this->allowedUpdates;
        if ($this->dropPendingUpdates->set) {
            $result['drop_pending_updates'] = $this->dropPendingUpdates->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            url: $data['url'],
            certificate: \array_key_exists('certificate', $data)
                ? OptString::some($data['certificate'])
                : OptString::none(),
            ipAddress: \array_key_exists('ip_address', $data)
                ? OptString::some($data['ip_address'])
                : OptString::none(),
            maxConnections: \array_key_exists('max_connections', $data)
                ? OptInt::some($data['max_connections'])
                : OptInt::none(),
            allowedUpdates: $data['allowed_updates'],
            dropPendingUpdates: \array_key_exists('drop_pending_updates', $data)
                ? OptBool::some($data['drop_pending_updates'])
                : OptBool::none(),
        );
    }
}
