<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 * This object represents an incoming update.At most one of the optional parameters can be present in
 * any given update.
 *
 * Ref: #/components/schemas/Update
 */
final readonly class Update implements JsonSerializable
{
    public function __construct(
        public int $updateId,
        public OptMessage $message,
        public OptMessage $editedMessage,
        public OptMessage $channelPost,
        public OptMessage $editedChannelPost,
        public OptInlineQuery $inlineQuery,
        public OptChosenInlineResult $chosenInlineResult,
        public OptCallbackQuery $callbackQuery,
        public OptShippingQuery $shippingQuery,
        public OptPreCheckoutQuery $preCheckoutQuery,
        public OptPoll $poll,
        public OptPollAnswer $pollAnswer,
        public OptChatMemberUpdated $myChatMember,
        public OptChatMemberUpdated $chatMember,
        public OptChatJoinRequest $chatJoinRequest,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        $result['update_id'] = $this->updateId;
        if ($this->message->set) {
            $result['message'] = $this->message->value?->jsonSerialize();
        }
        if ($this->editedMessage->set) {
            $result['edited_message'] = $this->editedMessage->value?->jsonSerialize();
        }
        if ($this->channelPost->set) {
            $result['channel_post'] = $this->channelPost->value?->jsonSerialize();
        }
        if ($this->editedChannelPost->set) {
            $result['edited_channel_post'] = $this->editedChannelPost->value?->jsonSerialize();
        }
        if ($this->inlineQuery->set) {
            $result['inline_query'] = $this->inlineQuery->value?->jsonSerialize();
        }
        if ($this->chosenInlineResult->set) {
            $result['chosen_inline_result'] = $this->chosenInlineResult->value?->jsonSerialize();
        }
        if ($this->callbackQuery->set) {
            $result['callback_query'] = $this->callbackQuery->value?->jsonSerialize();
        }
        if ($this->shippingQuery->set) {
            $result['shipping_query'] = $this->shippingQuery->value?->jsonSerialize();
        }
        if ($this->preCheckoutQuery->set) {
            $result['pre_checkout_query'] = $this->preCheckoutQuery->value?->jsonSerialize();
        }
        if ($this->poll->set) {
            $result['poll'] = $this->poll->value?->jsonSerialize();
        }
        if ($this->pollAnswer->set) {
            $result['poll_answer'] = $this->pollAnswer->value?->jsonSerialize();
        }
        if ($this->myChatMember->set) {
            $result['my_chat_member'] = $this->myChatMember->value?->jsonSerialize();
        }
        if ($this->chatMember->set) {
            $result['chat_member'] = $this->chatMember->value?->jsonSerialize();
        }
        if ($this->chatJoinRequest->set) {
            $result['chat_join_request'] = $this->chatJoinRequest->value?->jsonSerialize();
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            updateId: $data['update_id'],
            message: \array_key_exists('message', $data)
                ? OptMessage::some(Message::fromArray($data['message']))
                : OptMessage::none(),
            editedMessage: \array_key_exists('edited_message', $data)
                ? OptMessage::some(Message::fromArray($data['edited_message']))
                : OptMessage::none(),
            channelPost: \array_key_exists('channel_post', $data)
                ? OptMessage::some(Message::fromArray($data['channel_post']))
                : OptMessage::none(),
            editedChannelPost: \array_key_exists('edited_channel_post', $data)
                ? OptMessage::some(Message::fromArray($data['edited_channel_post']))
                : OptMessage::none(),
            inlineQuery: \array_key_exists('inline_query', $data)
                ? OptInlineQuery::some(InlineQuery::fromArray($data['inline_query']))
                : OptInlineQuery::none(),
            chosenInlineResult: \array_key_exists('chosen_inline_result', $data)
                ? OptChosenInlineResult::some(ChosenInlineResult::fromArray($data['chosen_inline_result']))
                : OptChosenInlineResult::none(),
            callbackQuery: \array_key_exists('callback_query', $data)
                ? OptCallbackQuery::some(CallbackQuery::fromArray($data['callback_query']))
                : OptCallbackQuery::none(),
            shippingQuery: \array_key_exists('shipping_query', $data)
                ? OptShippingQuery::some(ShippingQuery::fromArray($data['shipping_query']))
                : OptShippingQuery::none(),
            preCheckoutQuery: \array_key_exists('pre_checkout_query', $data)
                ? OptPreCheckoutQuery::some(PreCheckoutQuery::fromArray($data['pre_checkout_query']))
                : OptPreCheckoutQuery::none(),
            poll: \array_key_exists('poll', $data)
                ? OptPoll::some(Poll::fromArray($data['poll']))
                : OptPoll::none(),
            pollAnswer: \array_key_exists('poll_answer', $data)
                ? OptPollAnswer::some(PollAnswer::fromArray($data['poll_answer']))
                : OptPollAnswer::none(),
            myChatMember: \array_key_exists('my_chat_member', $data)
                ? OptChatMemberUpdated::some(ChatMemberUpdated::fromArray($data['my_chat_member']))
                : OptChatMemberUpdated::none(),
            chatMember: \array_key_exists('chat_member', $data)
                ? OptChatMemberUpdated::some(ChatMemberUpdated::fromArray($data['chat_member']))
                : OptChatMemberUpdated::none(),
            chatJoinRequest: \array_key_exists('chat_join_request', $data)
                ? OptChatJoinRequest::some(ChatJoinRequest::fromArray($data['chat_join_request']))
                : OptChatJoinRequest::none(),
        );
    }
}
