<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Responses\OpenApi;

use Illuminate\Contracts\Support\Responsable;
use Illuminate\Http\JsonResponse;
use App\Http\Dto\OpenApi as Dto;

/**
 * Auto-generated error response from OpenAPI specification.
 * Represents the default error response type.
 *
 * unexpected error
 */
final readonly class ErrorResponse implements Responsable
{
    public function __construct(
        private Dto\ErrorStatusCode $data,
    ) {}

    public function toResponse($request): JsonResponse
    {
        return response()->json($this->data->response, $this->data->statusCode);
    }
}
