<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Responses\OpenApi;

use Illuminate\Contracts\Support\Responsable;
use Illuminate\Http\JsonResponse;
use App\Http\Dto\OpenApi as Dto;

/**
 * Auto-generated response from OpenAPI specification.
 *
 * Result of method invocation
 */
final readonly class SendGameResponse implements Responsable
{
    private const HTTP_STATUS = 200;

    public function __construct(
        private Dto\ResultMessage $data,
    ) {}

    public function toResponse($request): JsonResponse
    {
        return response()->json($this->data, self::HTTP_STATUS);
    }
}
