<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Dto\OpenApi;

use JsonSerializable;

/**
 * Auto-generated DTO from OpenAPI specification.
 *
 * Ref: #/components/schemas/Image
 */
final readonly class Image implements JsonSerializable
{
    public function __construct(
        public OptString $t,
        public OptInt $w,
        public OptInt $h,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        $result = [];
        if ($this->t->set) {
            $result['t'] = $this->t->value;
        }
        if ($this->w->set) {
            $result['w'] = $this->w->value;
        }
        if ($this->h->set) {
            $result['h'] = $this->h->value;
        }

        return $result;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            t: \array_key_exists('t', $data)
                ? OptString::some($data['t'])
                : OptString::none(),
            w: \array_key_exists('w', $data)
                ? OptInt::some($data['w'])
                : OptInt::none(),
            h: \array_key_exists('h', $data)
                ? OptInt::some($data['h'])
                : OptInt::none(),
        );
    }
}
