<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\SandboxClearPostRequest;
use App\Http\Requests\SandboxCurrenciesBalancePostRequest;
use App\Http\Requests\SandboxPositionsBalancePostRequest;
use App\Http\Requests\SandboxRegisterPostRequest;
use App\Http\Requests\SandboxRemovePostRequest;
use App\Http\Responses\OpenApi\SandboxClearPostResponse;
use App\Http\Responses\OpenApi\SandboxCurrenciesBalancePostResponse;
use App\Http\Responses\OpenApi\SandboxPositionsBalancePostResponse;
use App\Http\Responses\OpenApi\SandboxRegisterPostResponse;
use App\Http\Responses\OpenApi\SandboxRemovePostResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class SandboxController extends Controller
{
    /**
     * POST /sandbox/clear
     *
     * Удаление всех позиций клиента.
     */
    abstract public function sandboxClearPost(
        SandboxClearPostRequest $request,
    ): SandboxClearPostResponse;

    /**
     * POST /sandbox/currencies/balance
     *
     * Выставление баланса по валютным позициям
     */
    abstract public function sandboxCurrenciesBalancePost(
        SandboxCurrenciesBalancePostRequest $request,
    ): SandboxCurrenciesBalancePostResponse;

    /**
     * POST /sandbox/positions/balance
     *
     * Выставление баланса по инструментным позициям
     */
    abstract public function sandboxPositionsBalancePost(
        SandboxPositionsBalancePostRequest $request,
    ): SandboxPositionsBalancePostResponse;

    /**
     * POST /sandbox/register
     *
     * Создание счета и валютных позиций для клиента.
     */
    abstract public function sandboxRegisterPost(
        SandboxRegisterPostRequest $request,
    ): SandboxRegisterPostResponse;

    /**
     * POST /sandbox/remove
     *
     * Удаление счета клиента.
     */
    abstract public function sandboxRemovePost(
        SandboxRemovePostRequest $request,
    ): SandboxRemovePostResponse;
}
