<?php

// Code generated by lcodegen, DO NOT EDIT.

namespace App\Http\Controllers\OpenApi;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateImageRequest;
use App\Http\Requests\CreateImageEditRequest;
use App\Http\Requests\CreateImageVariationRequest;
use App\Http\Responses\OpenApi\CreateImageEditResponse;
use App\Http\Responses\OpenApi\CreateImageResponse;
use App\Http\Responses\OpenApi\CreateImageVariationResponse;

/**
 * Auto-generated abstract controller from OpenAPI specification.
 * Extend this class and implement the abstract methods.
 */
abstract class ImageController extends Controller
{
    /**
     * POST /images/generations
     *
     * Creates an image given a prompt.
     */
    abstract public function createImage(
        CreateImageRequest $request,
    ): CreateImageResponse;

    /**
     * POST /images/edits
     *
     * Creates an edited or extended image given an original image and a prompt.
     */
    abstract public function createImageEdit(
        CreateImageEditRequest $request,
    ): CreateImageEditResponse;

    /**
     * POST /images/variations
     *
     * Creates a variation of a given image.
     */
    abstract public function createImageVariation(
        CreateImageVariationRequest $request,
    ): CreateImageVariationResponse;
}
